# Analysis of Cysteine Environment

In [2]:
import numpy as np
import pandas as pd
import requests
import json
import shutil
import pickle
import io
from pathlib import Path
from Bio import PDB

## 1 - Import data

Input file should be located in the /res subfolder and have one column with accession number of the proteins and another column with position of the cysteines.

In [3]:
filename = "MS-data"
accession_column = "protein accession number"
cysteine_column = "cysteine site"

input_data = pd.read_excel(f"res/{filename}.xlsx")
print(f"{len(input_data)} cysteines in {len(list(np.unique(input_data[accession_column])))} proteins")
input_data

1724 cysteines in 1166 proteins

     protein accession number gene name cysteine site
0                      P49588     AARS1          C773
1                      P49588     AARS1          C903
2                      P33527     ABCC1          C744
3                      Q8NE71     ABCF1          C655
4                      Q9NUJ1    ABHD10          C100
...                       ...       ...           ...
1719                   Q96KR1       ZFR          C922
1720                   Q8N5A5     ZGPAT          C377
1721                   Q8TF68    ZNF384          C435
1722                   Q2TB10    ZNF800          C359
1723                   Q15942       ZYX          C384

[1724 rows x 3 columns]

## 2 -  Create a chunked list of proteins and download new data from AIUPRED and EBI
Needs to run just once, then all the data can be easily retrieved from pickle.<br>

### 2.1 - Create a list of new unique accessions
Avoids downloading twice when two cysteines are in the same protein.

In [4]:
new_accessions = list(accession.split(";")[0] for accession in np.unique(input_data[accession_column]))

### 2.2 - Retrieve old outputs (if present) from pickle and make a list of old accessions

In [5]:
if Path("res/AIUPred_proteins.pkl").exists() and Path("res/EBI_proteins.pkl").exists():
    # Create copies of the old pickle files
    shutil.copy("res/AIUPred_proteins.pkl", "res/AIUPred_proteins_old.pkl")
    shutil.copy("res/EBI_proteins.pkl", "res/EBI_proteins_old.pkl")

    with open("res/AIUPred_proteins_old.pkl", "rb") as f:
        AIUPred_proteins_old = pickle.load(f)
    with open("res/EBI_proteins_old.pkl", "rb") as f:
        EBI_proteins_old = pickle.load(f)
else:
    AIUPred_proteins_old = pd.DataFrame(columns=["accession"])
    EBI_proteins_old = pd.DataFrame(columns=["accession"])

old_accessions_a = list(np.unique(AIUPred_proteins_old["accession"]))
old_accessions_e = list(np.unique(EBI_proteins_old["accession"]))
print(f"Old pickles have same number of accessions: {old_accessions_a == old_accessions_e}")
print(f"{len(old_accessions_a)} proteins in old pickles")

Old pickles have same number of accessions: True
0 proteins in old pickles

### 2.3 - Combine new and old accessions in a comprehensive new list

In [6]:
all_accessions = sorted(list(set(new_accessions + old_accessions_a)), key=str.lower)
print(f"{len(all_accessions)} accessions in the combined list")
all_accessions

1166 accessions in the combined list

['A0AVT1',
 'A6NDU8',
 'A6NHR9',
 'A6NKF1',
 'B2RTY4',
 'O00116',
 'O00151',
 'O00159',
 'O00170',
 'O00186',
 'O00231',
 'O00233',
 'O00267',
 'O00299',
 'O00303',
 'O00400',
 'O00410',
 'O00425',
 'O00429',
 'O00462',
 'O00469',
 'O00471',
 'O00541',
 'O00567',
 'O00571',
 'O00629',
 'O00743',
 'O14524',
 'O14530',
 'O14617',
 'O14682',
 'O14744',
 'O14787',
 'O14818',
 'O14867',
 'O14879',
 'O14929',
 'O14950',
 'O14964',
 'O14967',
 'O14974',
 'O14979',
 'O14981',
 'O15056',
 'O15067',
 'O15078',
 'O15131',
 'O15144',
 'O15228',
 'O15269',
 'O15357',
 'O15371',
 'O15400',
 'O15498',
 'O43143',
 'O43242',
 'O43299',
 'O43447',
 'O43592',
 'O43660',
 'O43663',
 'O43707',
 'O43747',
 'O43765',
 'O43795',
 'O43837',
 'O60216',
 'O60231',
 'O60244',
 'O60292',
 'O60306',
 'O60343',
 'O60508',
 'O60610',
 'O60664',
 'O60701',
 'O60716',
 'O60826',
 'O60832',
 'O60884',
 'O60890',
 'O60936',
 'O75083',
 'O75116',
 'O75122',
 'O75131',
 'O75147',
 'O75165',
 'O75179',
 'O75326',
 'O75347',
 'O75351',
 'O75367',
 'O75369',
 'O75390',
 'O75439',
 'O75503',
 'O75521',
 'O75530',
 'O75531',
 'O75533',
 'O75534',
 'O75607',
 'O75643',
 'O75663',
 'O75694',
 'O75821',
 'O75822',
 'O75828',
 'O75832',
 'O75874',
 'O75923',
 'O75947',
 'O75953',
 'O76021',
 'O76094',
 'O94760',
 'O94763',
 'O94776',
 'O94804',
 'O94808',
 'O94826',
 'O94855',
 'O94874',
 'O94876',
 'O94901',
 'O94905',
 'O94906',
 'O94919',
 'O94979',
 'O95059',
 'O95155',
 'O95163',
 'O95202',
 'O95210',
 'O95260',
 'O95292',
 'O95336',
 'O95373',
 'O95394',
 'O95478',
 'O95571',
 'O95573',
 'O95757',
 'O95758',
 'O95782',
 'O95831',
 'O95861',
 'O95881',
 'O95905',
 'O96019',
 'P00338',
 'P00367',
 'P00387',
 'P00491',
 'P00492',
 'P00505',
 'P00558',
 'P00749',
 'P01889',
 'P02545',
 'P02751',
 'P02795',
 'P04040',
 'P04049',
 'P04075',
 'P04083',
 'P04181',
 'P04216',
 'P04406',
 'P04632',
 'P04843',
 'P04844',
 'P04899',
 'P05062',
 'P05120',
 'P05141',
 'P05198',
 'P05388',
 'P05455',
 'P05556',
 'P06132',
 'P06400',
 'P06733',
 'P06746',
 'P07237',
 'P07355',
 'P07384',
 'P07437',
 'P07602',
 'P07737',
 'P07814',
 'P07858',
 'P07900',
 'P07954',
 'P07992',
 'P08133',
 'P08174',
 'P08237',
 'P08240',
 'P08559',
 'P08572',
 'P08670',
 'P08754',
 'P08758',
 'P09038',
 'P09104',
 'P09132',
 'P09211',
 'P09234',
 'P09382',
 'P09496',
 'P09497',
 'P09543',
 'P09651',
 'P09936',
 'P09972',
 'P0CG39',
 'P10155',
 'P10301',
 'P10589',
 'P10619',
 'P10644',
 'P10768',
 'P10809',
 'P11142',
 'P11216',
 'P11274',
 'P11413',
 'P11586',
 'P11766',
 'P11802',
 'P11908',
 'P12004',
 'P12081',
 'P12270',
 'P12814',
 'P12955',
 'P13489',
 'P13611',
 'P13639',
 'P13693',
 'P13716',
 'P13726',
 'P13797',
 'P13798',
 'P13987',
 'P14174',
 'P14314',
 'P14618',
 'P14649',
 'P15121',
 'P15170',
 'P15531',
 'P15924',
 'P16070',
 'P16615',
 'P16930',
 'P17050',
 'P17066',
 'P17301',
 'P17655',
 'P17812',
 'P17844',
 'P18031',
 'P18077',
 'P18085',
 'P18206',
 'P18583',
 'P18669',
 'P19338',
 'P19367',
 'P20020',
 'P20042',
 'P20073',
 'P20337',
 'P20585',
 'P20645',
 'P20936',
 'P21281',
 'P21291',
 'P21333',
 'P21399',
 'P21589',
 'P21796',
 'P21964',
 'P21980',
 'P22033',
 'P22061',
 'P22102',
 'P22234',
 'P22314',
 'P22626',
 'P22695',
 'P22830',
 'P23193',
 'P23229',
 'P23258',
 'P23284',
 'P23381',
 'P23396',
 'P23434',
 'P23458',
 'P23467',
 'P23526',
 'P23528',
 'P23634',
 'P23743',
 'P23921',
 'P24666',
 'P24752',
 'P24844',
 'P25205',
 'P25398',
 'P25685',
 'P25786',
 'P25789',
 'P26006',
 'P26232',
 'P26440',
 'P26599',
 'P26639',
 'P26640',
 'P27348',
 'P27635',
 'P27707',
 'P27797',
 'P28070',
 'P28072',
 'P28161',
 'P28300',
 'P28340',
 'P28838',
 'P29144',
 'P29317',
 'P29353',
 'P29401',
 'P29692',
 'P29992',
 'P30041',
 'P30050',
 'P30084',
 'P30086',
 'P30101',
 'P30153',
 'P30260',
 'P30281',
 'P30519',
 'P30530',
 'P30626',
 'P31040',
 'P31153',
 'P31323',
 'P31327',
 'P31751',
 'P31930',
 'P31939',
 'P31943',
 'P31948',
 'P32969',
 'P33121',
 'P33316',
 'P33527',
 'P33993',
 'P34896',
 'P34897',
 'P34932',
 'P35237',
 'P35555',
 'P35579',
 'P35606',
 'P35613',
 'P35637',
 'P35659',
 'P35754',
 'P35914',
 'P36776',
 'P36915',
 'P36957',
 'P36959',
 'P37268',
 'P37837',
 'P38646',
 'P38936',
 'P39023',
 'P39656',
 'P40123',
 'P40227',
 'P40429',
 'P40692',
 'P40925',
 'P40926',
 'P40939',
 'P41223',
 'P41229',
 'P41250',
 'P41252',
 'P42166',
 'P42285',
 'P42336',
 'P42345',
 'P42677',
 'P42704',
 'P42858',
 'P43034',
 'P43243',
 'P43304',
 'P43490',
 'P43897',
 'P45880',
 'P45973',
 'P46013',
 'P46020',
 'P46060',
 'P46063',
 'P46776',
 'P46777',
 'P46779',
 'P46782',
 'P46821',
 'P46939',
 'P46940',
 'P47756',
 'P47897',
 'P48059',
 'P48444',
 'P48449',
 'P48509',
 'P48556',
 'P48643',
 'P48735',
 'P48739',
 'P49023',
 'P49189',
 'P49327',
 'P49368',
 'P49454',
 'P49458',
 'P49588',
 'P49643',
 'P49720',
 'P49721',
 'P49736',
 'P49748',
 'P49773',
 'P49792',
 'P49821',
 'P49841',
 'P49915',
 'P50053',
 'P50148',
 'P50213',
 'P50395',
 'P50416',
 'P50440',
 'P50552',
 'P50750',
 'P50851',
 'P50914',
 'P50990',
 'P50991',
 'P50995',
 'P51114',
 'P51398',
 'P51610',
 'P51858',
 'P51991',
 'P52209',
 'P52294',
 'P52306',
 'P52594',
 'P52597',
 'P52701',
 'P52758',
 'P52788',
 'P52789',
 'P52907',
 'P53041',
 'P53384',
 'P53396',
 'P53618',
 'P53621',
 'P53634',
 'P53990',
 'P53992',
 'P54136',
 'P54278',
 'P54577',
 'P54687',
 'P54709',
 'P54886',
 'P54920',
 'P55036',
 'P55060',
 'P55072',
 'P55145',
 'P55209',
 'P55735',
 'P55795',
 'P55884',
 'P56589',
 'P57721',
 'P60174',
 'P60709',
 'P60866',
 'P60891',
 'P60900',
 'P60953',
 'P60981',
 'P61011',
 'P61081',
 'P61086',
 'P61088',
 'P61158',
 'P61160',
 'P61224',
 'P61247',
 'P61964',
 'P61970',
 'P61978',
 'P62072',
 'P62136',
 'P62195',
 'P62241',
 'P62249',
 'P62263',
 'P62316',
 'P62318',
 'P62333',
 'P62495',
 'P62633',
 'P62701',
 'P62714',
 'P62826',
 'P62829',
 'P62834',
 'P62857',
 'P62873',
 'P62879',
 'P62888',
 'P62910',
 'P62937',
 'P63010',
 'P63096',
 'P63104',
 'P63167',
 'P63208',
 'P63220',
 'P63244',
 'P67870',
 'P67936',
 'P68104',
 'P78371',
 'P78417',
 'P78527',
 'P78559',
 'P83731',
 'P84090',
 'P84103',
 'Q00534',
 'Q00537',
 'Q00610',
 'Q00653',
 'Q00839',
 'Q01082',
 'Q01469',
 'Q01484',
 'Q01518',
 'Q01658',
 'Q01780',
 'Q01813',
 'Q01844',
 'Q01970',
 'Q01995',
 'Q02218',
 'Q02241',
 'Q02252',
 'Q02543',
 'Q02790',
 'Q02809',
 'Q03001',
 'Q03426',
 'Q03519',
 'Q04446',
 'Q04637',
 'Q04760',
 'Q04771',
 'Q04917',
 'Q06124',
 'Q06136',
 'Q06210',
 'Q06278',
 'Q06546',
 'Q06609',
 'Q07065',
 'Q07866',
 'Q07954',
 'Q07955',
 'Q08170',
 'Q08211',
 'Q08257',
 'Q08AF3',
 'Q08AM6',
 'Q09666',
 'Q0ZGT2',
 'Q10567',
 'Q12765',
 'Q12769',
 'Q12792',
 'Q12800',
 'Q12846',
 'Q12874',
 'Q12888',
 'Q12904',
 'Q12931',
 'Q12974',
 'Q12979',
 'Q13011',
 'Q13042',
 'Q13045',
 'Q13085',
 'Q13098',
 'Q13126',
 'Q13148',
 'Q13153',
 'Q13155',
 'Q13158',
 'Q13162',
 'Q13190',
 'Q13200',
 'Q13242',
 'Q13310',
 'Q13325',
 'Q13418',
 'Q13423',
 'Q13426',
 'Q13439',
 'Q13443',
 'Q13501',
 'Q13505',
 'Q13526',
 'Q13555',
 'Q13557',
 'Q13596',
 'Q13610',
 'Q13616',
 'Q13617',
 'Q13620',
 'Q13630',
 'Q13637',
 'Q13740',
 'Q13795',
 'Q13813',
 'Q13838',
 'Q13867',
 'Q13868',
 'Q13907',
 'Q14008',
 'Q14019',
 'Q14108',
 'Q14126',
 'Q14152',
 'Q14155',
 'Q14192',
 'Q14197',
 'Q14203',
 'Q14204',
 'Q14315',
 'Q14318',
 'Q14376',
 'Q14558',
 'Q14566',
 'Q14644',
 'Q14683',
 'Q14690',
 'Q14692',
 'Q14697',
 'Q14764',
 'Q14847',
 'Q14974',
 'Q14980',
 'Q14C86',
 'Q15008',
 'Q15018',
 'Q15019',
 'Q15020',
 'Q15024',
 'Q15029',
 'Q15041',
 'Q15042',
 'Q15047',
 'Q15056',
 'Q15075',
 'Q15102',
 'Q15147',
 'Q15149',
 'Q15154',
 'Q15181',
 'Q15185',
 'Q15311',
 'Q15345',
 'Q15361',
 'Q15365',
 'Q15366',
 'Q15386',
 'Q15392',
 'Q15428',
 'Q15435',
 'Q15437',
 'Q15459',
 'Q15643',
 'Q15678',
 'Q15738',
 'Q15746',
 'Q15811',
 'Q15814',
 'Q15942',
 'Q16181',
 'Q16270',
 'Q16531',
 'Q16543',
 'Q16555',
 'Q16576',
 'Q16630',
 'Q16643',
 'Q16658',
 'Q16762',
 'Q16775',
 'Q16891',
 'Q1KMD3',
 'Q27J81',
 'Q2M389',
 'Q2TB10',
 'Q32P28',
 'Q3MHD2',
 'Q4G148',
 'Q4VC31',
 'Q52LJ0',
 'Q52LW3',
 'Q53EP0',
 'Q53FA7',
 'Q53H12',
 'Q58WW2',
 'Q5BJF6',
 'Q5JRA6',
 'Q5JSH3',
 'Q5JTH9',
 'Q5JWF2',
 'Q5K651',
 'Q5M775',
 'Q5MIZ7',
 'Q5R3I4',
 'Q5RKV6',
 'Q5SRE5',
 'Q5T0D9',
 'Q5T4S7',
 'Q5T653',
 'Q5T8P6',
 'Q5TFE4',
 'Q5VU43',
 'Q5VYK3',
 'Q5W0V3',
 'Q63ZY3',
 'Q658Y4',
 'Q66K74',
 'Q676U5',
 'Q68D91',
 'Q68EM7',
 'Q69YN2',
 'Q6AI12',
 'Q6DD88',
 'Q6I9Y2',
 'Q6NUK1',
 'Q6NUQ4',
 'Q6P158',
 'Q6P1N0',
 'Q6P2E9',
 'Q6P2H3',
 'Q6P587',
 'Q6PCE3',
 'Q6PD62',
 'Q6PFW1',
 'Q6PI48',
 'Q6QNY1',
 'Q6R327',
 'Q6SZW1',
 'Q6UXH8',
 'Q6UXV4',
 'Q6YN16',
 'Q6ZRS2',
 'Q6ZUT6',
 'Q6ZW76',
 'Q7KZF4',
 'Q7L014',
 'Q7L1Q6',
 'Q7L273',
 'Q7L2H7',
 'Q7L5N7',
 'Q7RTS9',
 'Q7Z2W4',
 'Q7Z2Z2',
 'Q7Z4Q2',
 'Q7Z4V5',
 'Q7Z6Z7',
 'Q86U42',
 'Q86UP2',
 'Q86VI3',
 'Q86VP6',
 'Q86VU5',
 'Q86X55',
 'Q86XZ4',
 'Q86Y37',
 'Q86Y82',
 'Q86YH6',
 'Q8IU81',
 'Q8IUR7',
 'Q8IWA0',
 'Q8IWB7',
 'Q8IWE2',
 'Q8IWR0',
 'Q8IX04',
 'Q8IXK0',
 'Q8IXY8',
 'Q8IY81',
 'Q8IYD1',
 'Q8IYS1',
 'Q8IYS2',
 'Q8IZ83',
 'Q8IZH2',
 'Q8IZP0',
 'Q8N0V3',
 'Q8N163',
 'Q8N1F7',
 'Q8N392',
 'Q8N3C0',
 'Q8N3Y1',
 'Q8N556',
 'Q8N5A5',
 'Q8N5L8',
 'Q8N806',
 'Q8NAP3',
 'Q8NAV1',
 'Q8NB16',
 'Q8NB49',
 'Q8NE71',
 'Q8NEN9',
 'Q8NEW0',
 'Q8NF37',
 'Q8NF91',
 'Q8NFH4',
 'Q8NG68',
 'Q8TAE8',
 'Q8TB52',
 'Q8TBC4',
 'Q8TCG1',
 'Q8TCS8',
 'Q8TDD1',
 'Q8TDX7',
 'Q8TEQ6',
 'Q8TEX9',
 'Q8TF42',
 'Q8TF68',
 'Q8WTW4',
 'Q8WUM4',
 'Q8WUP2',
 'Q8WV93',
 'Q8WVM7',
 'Q8WVT3',
 'Q8WWI1',
 'Q8WX92',
 'Q8WX93',
 'Q92499',
 'Q92538',
 'Q92547',
 'Q92598',
 'Q92614',
 'Q92616',
 'Q92685',
 'Q92688',
 'Q92747',
 'Q92791',
 'Q92841',
 'Q92870',
 'Q92878',
 'Q92888',
 'Q92896',
 'Q92900',
 'Q92905',
 'Q92945',
 'Q92973',
 'Q92974',
 'Q93008',
 'Q93009',
 'Q93034',
 'Q93073',
 'Q969F9',
 'Q969Q5',
 'Q969R2',
 'Q969V5',
 'Q96A33',
 'Q96A65',
 'Q96AC1',
 'Q96AE4',
 'Q96AG4',
 'Q96AT9',
 'Q96BY6',
 'Q96C90',
 'Q96CS3',
 'Q96CV9',
 'Q96CW6',
 'Q96DG6',
 'Q96ED9',
 'Q96EL3',
 'Q96FJ2',
 'Q96FW1',
 'Q96FX7',
 'Q96FZ7',
 'Q96GG9',
 'Q96GX9',
 'Q96HC4',
 'Q96HE7',
 'Q96I24',
 'Q96I25',
 'Q96II8',
 'Q96JB2',
 'Q96JB5',
 'Q96K76',
 'Q96KR1',
 'Q96ME1',
 'Q96MX6',
 'Q96N67',
 'Q96P48',
 'Q96P50',
 'Q96PK6',
 'Q96Q15',
 'Q96QB1',
 'Q96QK1',
 'Q96RS6',
 'Q96RU3',
 'Q96T21',
 'Q96T76',
 'Q96T88',
 'Q96TA1',
 'Q99426',
 'Q99439',
 'Q99442',
 'Q99459',
 'Q99471',
 'Q99536',
 'Q99567',
 'Q99575',
 'Q99598',
 'Q99741',
 'Q99797',
 'Q99805',
 'Q99832',
 'Q99873',
 'Q99942',
 'Q99961',
 'Q9BPW8',
 'Q9BPX3',
 'Q9BQ52',
 'Q9BQ70',
 'Q9BQB6',
 'Q9BRP1',
 'Q9BRX2',
 'Q9BSH4',
 'Q9BSJ8',
 'Q9BSL1',
 'Q9BTT0',
 'Q9BTV5',
 'Q9BTW9',
 'Q9BU76',
 'Q9BUF5',
 'Q9BUJ2',
 'Q9BV81',
 'Q9BVP2',
 'Q9BW19',
 'Q9BWU0',
 'Q9BXF6',
 'Q9BXJ9',
 'Q9BXK5',
 'Q9BXP5',
 'Q9BXR0',
 'Q9BXY0',
 'Q9BY32',
 'Q9BY44',
 'Q9BYT8',
 'Q9BYX2',
 'Q9BZ29',
 'Q9BZE1',
 'Q9BZF1',
 'Q9BZF9',
 'Q9BZH6',
 'Q9BZL4',
 'Q9C0B1',
 'Q9C0D5',
 'Q9GZN8',
 'Q9GZR7',
 'Q9GZS1',
 ...]

### 2.4 -  Divide accessions into chunks
Smaller chunks make it possible to download one bit at a time and save along the way.

In [7]:
chunk_size = 100

accessions = [all_accessions[i : i+chunk_size] for i in range(0, len(all_accessions), chunk_size)]
print(f"Number of chunks: {len(accessions)}")

Number of chunks: 12

###  2.5 - Download redox and disorder data, save pickle chunk files
Takes about 45 minutes for 1000 new proteins.<br>
Retrieve data that are already in the old pickle, saving the time to download them again.<br>
Logging allows following the download as it progresses.

In [8]:
def AIUPred_download(accession, parameters={}):
    ### Access AIUPRED's API and download information
    url = "https://aiupred.elte.hu/rest_api"
    parameters["accession"] = accession 
    try:    # try to download page
        AIUPred_res = session.get(url, params=parameters)
        AIUPred_res.raise_for_status()
    except:
        print(f"Impossible to download AIUPred data for accession {accession}")
        return {"regions": "NaN", "AIUPred": "NaN"}
    return json.loads(AIUPred_res.text)

In [9]:
with requests.Session() as session:
    for i in range(len(accessions)):  # Loop over chunks
    # for i in range(6, len(accessions)):  # in case first 6 chunks already done
        redox = []
        disorder = []

        # Either copy data from old pickle or download disorder and redox data from AIUPred's API
        for accession in accessions[i]:  # Loop over accessions in the chunk
            if accession in AIUPred_proteins_old["accession"].values:   # if accession is already in the old pickle
                redox_old = AIUPred_proteins_old.loc[AIUPred_proteins_old["accession"] == accession, "redox"].iloc[0]
                disorder_old = AIUPred_proteins_old.loc[AIUPred_proteins_old["accession"] == accession, "disorder"].iloc[0]
                redox.append(redox_old)
                disorder.append(disorder_old)
                print(f"AIUPred data for accession {accession} copied from old pickle")
            else:   # if new data need to be downloaded
                # redox
                redox_new = AIUPred_download(accession, {"analysis_type": "redox", "smoothing": "default"})
                redox.append(redox_new["regions"])
                print(f"Redox data for accession {accession} downloaded")
                # disorder
                disorder_new = AIUPred_download(accession)
                disorder.append(disorder_new["AIUPred"])
                print(f"Disorder data for accession {accession} downloaded")

        # Assemble all data for a chunk of accessions in a DataFrame
        AIUPred_chunk = pd.DataFrame({"accession": accessions[i], "redox": redox, "disorder": disorder})
        print(AIUPred_chunk)

        # Save chunk as pickle
        with open(f"res/AIUPred_proteins_chunk_{i+1}.pkl", "wb") as f:
            pickle.dump(AIUPred_chunk, f)
        print(f"AIUPred pickle chunk {i+1} saved\n")

Redox data for accession A0AVT1 downloaded
Disorder data for accession A0AVT1 downloaded
Redox data for accession A6NDU8 downloaded
Disorder data for accession A6NDU8 downloaded
Redox data for accession A6NHR9 downloaded
Disorder data for accession A6NHR9 downloaded
Redox data for accession A6NKF1 downloaded
Disorder data for accession A6NKF1 downloaded
Redox data for accession B2RTY4 downloaded
Disorder data for accession B2RTY4 downloaded
Redox data for accession O00116 downloaded
Disorder data for accession O00116 downloaded
Redox data for accession O00151 downloaded
Disorder data for accession O00151 downloaded
Redox data for accession O00159 downloaded
Disorder data for accession O00159 downloaded
Redox data for accession O00170 downloaded
Disorder data for accession O00170 downloaded
Redox data for accession O00186 downloaded
Disorder data for accession O00186 downloaded
Redox data for accession O00231 downloaded
Disorder data for accession O00231 downloaded
Redox data for accession O00233 downloaded
Disorder data for accession O00233 downloaded
Redox data for accession O00267 downloaded
Disorder data for accession O00267 downloaded
Redox data for accession O00299 downloaded
Disorder data for accession O00299 downloaded
Redox data for accession O00303 downloaded
Disorder data for accession O00303 downloaded
Redox data for accession O00400 downloaded
Disorder data for accession O00400 downloaded
Redox data for accession O00410 downloaded
Disorder data for accession O00410 downloaded
Redox data for accession O00425 downloaded
Disorder data for accession O00425 downloaded
Redox data for accession O00429 downloaded
Disorder data for accession O00429 downloaded
Redox data for accession O00462 downloaded
Disorder data for accession O00462 downloaded
Redox data for accession O00469 downloaded
Disorder data for accession O00469 downloaded
Redox data for accession O00471 downloaded
Disorder data for accession O00471 downloaded
Redox data for accession O00541 downloaded
Disorder data for accession O00541 downloaded
Redox data for accession O00567 downloaded
Disorder data for accession O00567 downloaded
Redox data for accession O00571 downloaded
Disorder data for accession O00571 downloaded
Redox data for accession O00629 downloaded
Disorder data for accession O00629 downloaded
Redox data for accession O00743 downloaded
Disorder data for accession O00743 downloaded
Redox data for accession O14524 downloaded
Disorder data for accession O14524 downloaded
Redox data for accession O14530 downloaded
Disorder data for accession O14530 downloaded
Redox data for accession O14617 downloaded
Disorder data for accession O14617 downloaded
Redox data for accession O14682 downloaded
Disorder data for accession O14682 downloaded
Redox data for accession O14744 downloaded
Disorder data for accession O14744 downloaded
Redox data for accession O14787 downloaded
Disorder data for accession O14787 downloaded
Redox data for accession O14818 downloaded
Disorder data for accession O14818 downloaded
Redox data for accession O14867 downloaded
Disorder data for accession O14867 downloaded
Redox data for accession O14879 downloaded
Disorder data for accession O14879 downloaded
Redox data for accession O14929 downloaded
Disorder data for accession O14929 downloaded
Redox data for accession O14950 downloaded
Disorder data for accession O14950 downloaded
Redox data for accession O14964 downloaded
Disorder data for accession O14964 downloaded
Redox data for accession O14967 downloaded
Disorder data for accession O14967 downloaded
Redox data for accession O14974 downloaded
Disorder data for accession O14974 downloaded
Redox data for accession O14979 downloaded
Disorder data for accession O14979 downloaded
Redox data for accession O14981 downloaded
Disorder data for accession O14981 downloaded
Redox data for accession O15056 downloaded
Disorder data for accession O15056 downloaded
Redox data for accession O15067 downloaded
Disorder data for accession O15067 downloaded
Redox data for accession O15078 downloaded
Disorder data for accession O15078 downloaded
Redox data for accession O15131 downloaded
Disorder data for accession O15131 downloaded
Redox data for accession O15144 downloaded
Disorder data for accession O15144 downloaded
Redox data for accession O15228 downloaded
Disorder data for accession O15228 downloaded
Redox data for accession O15269 downloaded
Disorder data for accession O15269 downloaded
Redox data for accession O15357 downloaded
Disorder data for accession O15357 downloaded
Redox data for accession O15371 downloaded
Disorder data for accession O15371 downloaded
Redox data for accession O15400 downloaded
Disorder data for accession O15400 downloaded
Redox data for accession O15498 downloaded
Disorder data for accession O15498 downloaded
Redox data for accession O43143 downloaded
Disorder data for accession O43143 downloaded
Redox data for accession O43242 downloaded
Disorder data for accession O43242 downloaded
Redox data for accession O43299 downloaded
Disorder data for accession O43299 downloaded
Redox data for accession O43447 downloaded
Disorder data for accession O43447 downloaded
Redox data for accession O43592 downloaded
Disorder data for accession O43592 downloaded
Redox data for accession O43660 downloaded
Disorder data for accession O43660 downloaded
Redox data for accession O43663 downloaded
Disorder data for accession O43663 downloaded
Redox data for accession O43707 downloaded
Disorder data for accession O43707 downloaded
Redox data for accession O43747 downloaded
Disorder data for accession O43747 downloaded
Redox data for accession O43765 downloaded
Disorder data for accession O43765 downloaded
Redox data for accession O43795 downloaded
Disorder data for accession O43795 downloaded
Redox data for accession O43837 downloaded
Disorder data for accession O43837 downloaded
Redox data for accession O60216 downloaded
Disorder data for accession O60216 downloaded
Redox data for accession O60231 downloaded
Impossible to download AIUPred data for accession O60231
Disorder data for accession O60231 downloaded
Redox data for accession O60244 downloaded
Disorder data for accession O60244 downloaded
Redox data for accession O60292 downloaded
Disorder data for accession O60292 downloaded
Redox data for accession O60306 downloaded
Disorder data for accession O60306 downloaded
Redox data for accession O60343 downloaded
Disorder data for accession O60343 downloaded
Redox data for accession O60508 downloaded
Disorder data for accession O60508 downloaded
Redox data for accession O60610 downloaded
Disorder data for accession O60610 downloaded
Redox data for accession O60664 downloaded
Disorder data for accession O60664 downloaded
Redox data for accession O60701 downloaded
Disorder data for accession O60701 downloaded
Redox data for accession O60716 downloaded
Disorder data for accession O60716 downloaded
Redox data for accession O60826 downloaded
Disorder data for accession O60826 downloaded
Redox data for accession O60832 downloaded
Disorder data for accession O60832 downloaded
Redox data for accession O60884 downloaded
Disorder data for accession O60884 downloaded
Redox data for accession O60890 downloaded
Disorder data for accession O60890 downloaded
Redox data for accession O60936 downloaded
Disorder data for accession O60936 downloaded
Redox data for accession O75083 downloaded
Disorder data for accession O75083 downloaded
Redox data for accession O75116 downloaded
Disorder data for accession O75116 downloaded
Redox data for accession O75122 downloaded
Disorder data for accession O75122 downloaded
Redox data for accession O75131 downloaded
Disorder data for accession O75131 downloaded
Redox data for accession O75147 downloaded
Disorder data for accession O75147 downloaded
Redox data for accession O75165 downloaded
Disorder data for accession O75165 downloaded
Redox data for accession O75179 downloaded
Disorder data for accession O75179 downloaded
Redox data for accession O75326 downloaded
Disorder data for accession O75326 downloaded
Redox data for accession O75347 downloaded
Disorder data for accession O75347 downloaded
Redox data for accession O75351 downloaded

Disorder data for accession O75351 downloaded
Redox data for accession O75367 downloaded
Disorder data for accession O75367 downloaded
Redox data for accession O75369 downloaded
Disorder data for accession O75369 downloaded
Redox data for accession O75390 downloaded
Disorder data for accession O75390 downloaded
Redox data for accession O75439 downloaded
Disorder data for accession O75439 downloaded
Redox data for accession O75503 downloaded
Disorder data for accession O75503 downloaded
Redox data for accession O75521 downloaded
Disorder data for accession O75521 downloaded
Redox data for accession O75530 downloaded
Disorder data for accession O75530 downloaded
Redox data for accession O75531 downloaded
Disorder data for accession O75531 downloaded
   accession                                              redox  \
0     A0AVT1                                       [[582, 624]]
1     A6NDU8                                       [[223, 250]]
2     A6NHR9                                     [[1868, 1900]]
3     A6NKF1                                                 []
4     B2RTY4  [[723, 741], [755, 787], [1170, 1224], [2030, ...
..       ...                                                ...
95    O75439                                                 []
96    O75503                                                 []
97    O75521                                                 []
98    O75530                                                 []
99    O75531                                                 []

                                             disorder
0   [0.9659407138824463, 0.9646615386009216, 0.968...
1   [0.3372959494590759, 0.32355791330337524, 0.34...
2   [0.9728986024856567, 0.9776636362075806, 0.978...
3   [0.9777251482009888, 0.9779385328292847, 0.978...
4   [0.672510027885437, 0.7656236290931702, 0.5662...
..                                                ...
95  [0.8278506994247437, 0.8473942279815674, 0.616...
96  [0.9541643261909485, 0.9550487995147705, 0.956...
97  [0.7442921996116638, 0.9398834109306335, 0.943...
98  [0.9756829738616943, 0.9770538210868835, 0.977...
99  [0.8182505369186401, 0.8040775060653687, 0.881...

[100 rows x 3 columns]
AIUPred pickle chunk 1 saved

Redox data for accession O75533 downloaded
Disorder data for accession O75533 downloaded
Redox data for accession O75534 downloaded
Disorder data for accession O75534 downloaded
Redox data for accession O75607 downloaded
Disorder data for accession O75607 downloaded
Redox data for accession O75643 downloaded
Disorder data for accession O75643 downloaded
Redox data for accession O75663 downloaded
Disorder data for accession O75663 downloaded
Redox data for accession O75694 downloaded
Disorder data for accession O75694 downloaded
Redox data for accession O75821 downloaded
Disorder data for accession O75821 downloaded
Redox data for accession O75822 downloaded
Disorder data for accession O75822 downloaded
Redox data for accession O75828 downloaded
Disorder data for accession O75828 downloaded
Redox data for accession O75832 downloaded
Disorder data for accession O75832 downloaded
Redox data for accession O75874 downloaded
Disorder data for accession O75874 downloaded
Redox data for accession O75923 downloaded
Disorder data for accession O75923 downloaded
Redox data for accession O75947 downloaded
Disorder data for accession O75947 downloaded
Redox data for accession O75953 downloaded
Disorder data for accession O75953 downloaded
Redox data for accession O76021 downloaded
Disorder data for accession O76021 downloaded
Redox data for accession O76094 downloaded
Disorder data for accession O76094 downloaded
Redox data for accession O94760 downloaded
Disorder data for accession O94760 downloaded
Redox data for accession O94763 downloaded
Disorder data for accession O94763 downloaded
Redox data for accession O94776 downloaded
Disorder data for accession O94776 downloaded
Redox data for accession O94804 downloaded
Disorder data for accession O94804 downloaded
Redox data for accession O94808 downloaded
Disorder data for accession O94808 downloaded
Redox data for accession O94826 downloaded
Disorder data for accession O94826 downloaded
Redox data for accession O94855 downloaded
Disorder data for accession O94855 downloaded
Redox data for accession O94874 downloaded
Disorder data for accession O94874 downloaded
Redox data for accession O94876 downloaded
Disorder data for accession O94876 downloaded
Redox data for accession O94901 downloaded
Disorder data for accession O94901 downloaded
Redox data for accession O94905 downloaded
Disorder data for accession O94905 downloaded
Redox data for accession O94906 downloaded
Disorder data for accession O94906 downloaded
Redox data for accession O94919 downloaded
Disorder data for accession O94919 downloaded
Redox data for accession O94979 downloaded
Disorder data for accession O94979 downloaded
Redox data for accession O95059 downloaded
Disorder data for accession O95059 downloaded
Redox data for accession O95155 downloaded
Disorder data for accession O95155 downloaded
Redox data for accession O95163 downloaded
Disorder data for accession O95163 downloaded
Redox data for accession O95202 downloaded
Disorder data for accession O95202 downloaded
Redox data for accession O95210 downloaded
Disorder data for accession O95210 downloaded
Redox data for accession O95260 downloaded
Disorder data for accession O95260 downloaded
Redox data for accession O95292 downloaded
Disorder data for accession O95292 downloaded
Redox data for accession O95336 downloaded
Disorder data for accession O95336 downloaded
Redox data for accession O95373 downloaded
Disorder data for accession O95373 downloaded
Redox data for accession O95394 downloaded
Disorder data for accession O95394 downloaded
Redox data for accession O95478 downloaded
Disorder data for accession O95478 downloaded
Redox data for accession O95571 downloaded
Disorder data for accession O95571 downloaded
Redox data for accession O95573 downloaded
Disorder data for accession O95573 downloaded
Redox data for accession O95757 downloaded
Disorder data for accession O95757 downloaded
Redox data for accession O95758 downloaded
Disorder data for accession O95758 downloaded
Redox data for accession O95782 downloaded
Disorder data for accession O95782 downloaded
Redox data for accession O95831 downloaded
Disorder data for accession O95831 downloaded
Redox data for accession O95861 downloaded
Disorder data for accession O95861 downloaded
Redox data for accession O95881 downloaded
Disorder data for accession O95881 downloaded
Redox data for accession O95905 downloaded
Disorder data for accession O95905 downloaded
Redox data for accession O96019 downloaded
Disorder data for accession O96019 downloaded
Redox data for accession P00338 downloaded
Disorder data for accession P00338 downloaded
Redox data for accession P00367 downloaded
Disorder data for accession P00367 downloaded
Redox data for accession P00387 downloaded
Disorder data for accession P00387 downloaded
Redox data for accession P00491 downloaded
Disorder data for accession P00491 downloaded
Redox data for accession P00492 downloaded
Disorder data for accession P00492 downloaded
Redox data for accession P00505 downloaded
Disorder data for accession P00505 downloaded
Redox data for accession P00558 downloaded
Disorder data for accession P00558 downloaded
Redox data for accession P00749 downloaded
Impossible to download AIUPred data for accession P00749
Disorder data for accession P00749 downloaded
Redox data for accession P01889 downloaded
Disorder data for accession P01889 downloaded
Redox data for accession P02545 downloaded
Disorder data for accession P02545 downloaded
Redox data for accession P02751 downloaded
Disorder data for accession P02751 downloaded
Redox data for accession P02795 downloaded
Disorder data for accession P02795 downloaded
Redox data for accession P04040 downloaded
Disorder data for accession P04040 downloaded
Redox data for accession P04049 downloaded
Disorder data for accession P04049 downloaded
Redox data for accession P04075 downloaded
Disorder data for accession P04075 downloaded

Redox data for accession P04083 downloaded
Disorder data for accession P04083 downloaded
Redox data for accession P04181 downloaded
Disorder data for accession P04181 downloaded
Redox data for accession P04216 downloaded
Disorder data for accession P04216 downloaded
Redox data for accession P04406 downloaded
Disorder data for accession P04406 downloaded
Redox data for accession P04632 downloaded
Disorder data for accession P04632 downloaded
Redox data for accession P04843 downloaded
Disorder data for accession P04843 downloaded
Redox data for accession P04844 downloaded
Disorder data for accession P04844 downloaded
Redox data for accession P04899 downloaded
Disorder data for accession P04899 downloaded
Redox data for accession P05062 downloaded
Disorder data for accession P05062 downloaded
Redox data for accession P05120 downloaded
Disorder data for accession P05120 downloaded
Redox data for accession P05141 downloaded
Disorder data for accession P05141 downloaded
Redox data for accession P05198 downloaded
Disorder data for accession P05198 downloaded
Redox data for accession P05388 downloaded
Disorder data for accession P05388 downloaded
Redox data for accession P05455 downloaded
Disorder data for accession P05455 downloaded
Redox data for accession P05556 downloaded
Disorder data for accession P05556 downloaded
Redox data for accession P06132 downloaded
Disorder data for accession P06132 downloaded
Redox data for accession P06400 downloaded
Disorder data for accession P06400 downloaded
Redox data for accession P06733 downloaded
Disorder data for accession P06733 downloaded
Redox data for accession P06746 downloaded
Disorder data for accession P06746 downloaded
Redox data for accession P07237 downloaded
Disorder data for accession P07237 downloaded
Redox data for accession P07355 downloaded
Disorder data for accession P07355 downloaded
Redox data for accession P07384 downloaded
Disorder data for accession P07384 downloaded
Redox data for accession P07437 downloaded
Disorder data for accession P07437 downloaded
Redox data for accession P07602 downloaded
Disorder data for accession P07602 downloaded
Redox data for accession P07737 downloaded
Disorder data for accession P07737 downloaded
Redox data for accession P07814 downloaded
Disorder data for accession P07814 downloaded
Redox data for accession P07858 downloaded
Disorder data for accession P07858 downloaded
Redox data for accession P07900 downloaded
Disorder data for accession P07900 downloaded
Redox data for accession P07954 downloaded
Disorder data for accession P07954 downloaded
Redox data for accession P07992 downloaded
Disorder data for accession P07992 downloaded
Redox data for accession P08133 downloaded
Disorder data for accession P08133 downloaded
Redox data for accession P08174 downloaded
Disorder data for accession P08174 downloaded
Redox data for accession P08237 downloaded
Disorder data for accession P08237 downloaded
Redox data for accession P08240 downloaded
Disorder data for accession P08240 downloaded
   accession                    redox  \
0     O75533                       []
1     O75534             [[103, 125]]
2     O75607              [[93, 132]]
3     O75643                       []
4     O75663             [[233, 253]]
..       ...                      ...
95    P07992                       []
96    P08133                       []
97    P08174  [[74, 130], [213, 282]]
98    P08237                       []
99    P08240                       []

                                             disorder
0   [0.5703356862068176, 0.5710870623588562, 0.570...
1   [0.40651726722717285, 0.6512625217437744, 0.61...
2   [0.9321572780609131, 0.9250213503837585, 0.938...
3   [0.7981631755828857, 0.8476518988609314, 0.848...
4   [0.9217513203620911, 0.9330849051475525, 0.925...
..                                                ...
95  [0.975849449634552, 0.976045548915863, 0.97986...
96  [0.9185391068458557, 0.9011653661727905, 0.919...
97  [0.9799044132232666, 0.9761133790016174, 0.971...
98  [0.8202720284461975, 0.8268101811408997, 0.728...
99  [0.20879030227661133, 0.18515841662883759, 0.1...

[100 rows x 3 columns]
AIUPred pickle chunk 2 saved

Redox data for accession P08559 downloaded
Disorder data for accession P08559 downloaded
Redox data for accession P08572 downloaded
Disorder data for accession P08572 downloaded
Redox data for accession P08670 downloaded
Disorder data for accession P08670 downloaded
Redox data for accession P08754 downloaded
Disorder data for accession P08754 downloaded
Redox data for accession P08758 downloaded
Disorder data for accession P08758 downloaded
Redox data for accession P09038 downloaded
Disorder data for accession P09038 downloaded
Redox data for accession P09104 downloaded
Disorder data for accession P09104 downloaded
Redox data for accession P09132 downloaded
Disorder data for accession P09132 downloaded
Redox data for accession P09211 downloaded
Disorder data for accession P09211 downloaded
Redox data for accession P09234 downloaded
Disorder data for accession P09234 downloaded
Redox data for accession P09382 downloaded
Disorder data for accession P09382 downloaded
Redox data for accession P09496 downloaded
Disorder data for accession P09496 downloaded
Redox data for accession P09497 downloaded
Disorder data for accession P09497 downloaded
Redox data for accession P09543 downloaded
Disorder data for accession P09543 downloaded
Redox data for accession P09651 downloaded
Disorder data for accession P09651 downloaded
Redox data for accession P09936 downloaded
Disorder data for accession P09936 downloaded
Redox data for accession P09972 downloaded
Disorder data for accession P09972 downloaded
Redox data for accession P0CG39 downloaded
Disorder data for accession P0CG39 downloaded
Redox data for accession P10155 downloaded
Disorder data for accession P10155 downloaded
Redox data for accession P10301 downloaded
Disorder data for accession P10301 downloaded
Redox data for accession P10589 downloaded
Disorder data for accession P10589 downloaded
Redox data for accession P10619 downloaded
Disorder data for accession P10619 downloaded
Redox data for accession P10644 downloaded
Disorder data for accession P10644 downloaded
Redox data for accession P10768 downloaded
Disorder data for accession P10768 downloaded
Redox data for accession P10809 downloaded
Disorder data for accession P10809 downloaded
Redox data for accession P11142 downloaded
Disorder data for accession P11142 downloaded
Redox data for accession P11216 downloaded
Disorder data for accession P11216 downloaded
Redox data for accession P11274 downloaded
Disorder data for accession P11274 downloaded
Redox data for accession P11413 downloaded
Disorder data for accession P11413 downloaded
Redox data for accession P11586 downloaded
Disorder data for accession P11586 downloaded
Redox data for accession P11766 downloaded
Disorder data for accession P11766 downloaded
Redox data for accession P11802 downloaded
Disorder data for accession P11802 downloaded
Redox data for accession P11908 downloaded
Disorder data for accession P11908 downloaded
Redox data for accession P12004 downloaded
Disorder data for accession P12004 downloaded
Redox data for accession P12081 downloaded
Disorder data for accession P12081 downloaded
Redox data for accession P12270 downloaded
Disorder data for accession P12270 downloaded
Redox data for accession P12814 downloaded
Disorder data for accession P12814 downloaded
Redox data for accession P12955 downloaded
Disorder data for accession P12955 downloaded
Redox data for accession P13489 downloaded
Disorder data for accession P13489 downloaded
Redox data for accession P13611 downloaded
Disorder data for accession P13611 downloaded
Redox data for accession P13639 downloaded
Disorder data for accession P13639 downloaded
Redox data for accession P13693 downloaded
Disorder data for accession P13693 downloaded
Redox data for accession P13716 downloaded
Disorder data for accession P13716 downloaded
Redox data for accession P13726 downloaded
Disorder data for accession P13726 downloaded
Redox data for accession P13797 downloaded

Disorder data for accession P13797 downloaded
Redox data for accession P13798 downloaded
Disorder data for accession P13798 downloaded
Redox data for accession P13987 downloaded
Disorder data for accession P13987 downloaded
Redox data for accession P14174 downloaded
Disorder data for accession P14174 downloaded
Redox data for accession P14314 downloaded
Disorder data for accession P14314 downloaded
Redox data for accession P14618 downloaded
Disorder data for accession P14618 downloaded
Redox data for accession P14649 downloaded
Disorder data for accession P14649 downloaded
Redox data for accession P15121 downloaded
Disorder data for accession P15121 downloaded
Redox data for accession P15170 downloaded
Disorder data for accession P15170 downloaded
Redox data for accession P15531 downloaded
Disorder data for accession P15531 downloaded
Redox data for accession P15924 downloaded
Disorder data for accession P15924 downloaded
Redox data for accession P16070 downloaded
Disorder data for accession P16070 downloaded
Redox data for accession P16615 downloaded
Disorder data for accession P16615 downloaded
Redox data for accession P16930 downloaded
Disorder data for accession P16930 downloaded
Redox data for accession P17050 downloaded
Disorder data for accession P17050 downloaded
Redox data for accession P17066 downloaded
Disorder data for accession P17066 downloaded
Redox data for accession P17301 downloaded
Disorder data for accession P17301 downloaded
Redox data for accession P17655 downloaded
Disorder data for accession P17655 downloaded
Redox data for accession P17812 downloaded
Disorder data for accession P17812 downloaded
Redox data for accession P17844 downloaded
Disorder data for accession P17844 downloaded
Redox data for accession P18031 downloaded
Disorder data for accession P18031 downloaded
Redox data for accession P18077 downloaded
Disorder data for accession P18077 downloaded
Redox data for accession P18085 downloaded
Disorder data for accession P18085 downloaded
Redox data for accession P18206 downloaded
Disorder data for accession P18206 downloaded
Redox data for accession P18583 downloaded
Disorder data for accession P18583 downloaded
Redox data for accession P18669 downloaded
Disorder data for accession P18669 downloaded
Redox data for accession P19338 downloaded
Disorder data for accession P19338 downloaded
Redox data for accession P19367 downloaded
Disorder data for accession P19367 downloaded
Redox data for accession P20020 downloaded
Disorder data for accession P20020 downloaded
Redox data for accession P20042 downloaded
Disorder data for accession P20042 downloaded
Redox data for accession P20073 downloaded
Disorder data for accession P20073 downloaded
Redox data for accession P20337 downloaded
Disorder data for accession P20337 downloaded
Redox data for accession P20585 downloaded
Disorder data for accession P20585 downloaded
Redox data for accession P20645 downloaded
Disorder data for accession P20645 downloaded
Redox data for accession P20936 downloaded
Disorder data for accession P20936 downloaded
Redox data for accession P21281 downloaded
Disorder data for accession P21281 downloaded
Redox data for accession P21291 downloaded
Disorder data for accession P21291 downloaded
Redox data for accession P21333 downloaded
Disorder data for accession P21333 downloaded
Redox data for accession P21399 downloaded
Disorder data for accession P21399 downloaded
Redox data for accession P21589 downloaded
Disorder data for accession P21589 downloaded
Redox data for accession P21796 downloaded
Disorder data for accession P21796 downloaded
Redox data for accession P21964 downloaded
Disorder data for accession P21964 downloaded
Redox data for accession P21980 downloaded
Disorder data for accession P21980 downloaded
Redox data for accession P22033 downloaded
Disorder data for accession P22033 downloaded
Redox data for accession P22061 downloaded
Disorder data for accession P22061 downloaded
Redox data for accession P22102 downloaded
Disorder data for accession P22102 downloaded
Redox data for accession P22234 downloaded
Disorder data for accession P22234 downloaded
Redox data for accession P22314 downloaded
Disorder data for accession P22314 downloaded
Redox data for accession P22626 downloaded
Disorder data for accession P22626 downloaded
Redox data for accession P22695 downloaded
Disorder data for accession P22695 downloaded
Redox data for accession P22830 downloaded
Disorder data for accession P22830 downloaded
Redox data for accession P23193 downloaded
Disorder data for accession P23193 downloaded
Redox data for accession P23229 downloaded
Disorder data for accession P23229 downloaded
Redox data for accession P23258 downloaded
Disorder data for accession P23258 downloaded
Redox data for accession P23284 downloaded
Disorder data for accession P23284 downloaded
Redox data for accession P23381 downloaded
Disorder data for accession P23381 downloaded
   accession                                              redox  \
0     P08559                                                 []
1     P08572                                     [[1690, 1712]]
2     P08670                                                 []
3     P08754                                                 []
4     P08758                                                 []
..       ...                                                ...
95    P23193                                       [[246, 301]]
96    P23229  [[75, 146], [536, 562], [643, 669], [762, 782]...
97    P23258                                                 []
98    P23284                                                 []
99    P23381                                                 []

                                             disorder
0   [0.4240681827068329, 0.4925544857978821, 0.686...
1   [0.9661752581596375, 0.9528498649597168, 0.957...
2   [0.9728150963783264, 0.9754696488380432, 0.974...
3   [0.758171558380127, 0.7104072570800781, 0.6688...
4   [0.43660348653793335, 0.4945676922798157, 0.63...
..                                                ...
95  [0.5692768692970276, 0.5917233228683472, 0.617...
96  [0.7962055802345276, 0.5880837440490723, 0.856...
97  [0.1621890515089035, 0.14842329919338226, 0.14...
98  [0.8980578780174255, 0.8866289854049683, 0.905...
99  [0.6772220134735107, 0.645186185836792, 0.6729...

[100 rows x 3 columns]
AIUPred pickle chunk 3 saved

Redox data for accession P23396 downloaded
Disorder data for accession P23396 downloaded
Redox data for accession P23434 downloaded
Disorder data for accession P23434 downloaded
Redox data for accession P23458 downloaded
Disorder data for accession P23458 downloaded
Redox data for accession P23467 downloaded
Disorder data for accession P23467 downloaded
Redox data for accession P23526 downloaded
Disorder data for accession P23526 downloaded
Redox data for accession P23528 downloaded
Disorder data for accession P23528 downloaded
Redox data for accession P23634 downloaded
Disorder data for accession P23634 downloaded
Redox data for accession P23743 downloaded
Disorder data for accession P23743 downloaded
Redox data for accession P23921 downloaded
Disorder data for accession P23921 downloaded
Redox data for accession P24666 downloaded
Disorder data for accession P24666 downloaded
Redox data for accession P24752 downloaded
Disorder data for accession P24752 downloaded
Redox data for accession P24844 downloaded
Disorder data for accession P24844 downloaded
Redox data for accession P25205 downloaded
Disorder data for accession P25205 downloaded
Redox data for accession P25398 downloaded
Disorder data for accession P25398 downloaded
Redox data for accession P25685 downloaded
Disorder data for accession P25685 downloaded
Redox data for accession P25786 downloaded
Disorder data for accession P25786 downloaded
Redox data for accession P25789 downloaded
Disorder data for accession P25789 downloaded
Redox data for accession P26006 downloaded
Disorder data for accession P26006 downloaded
Redox data for accession P26232 downloaded
Disorder data for accession P26232 downloaded
Redox data for accession P26440 downloaded

Disorder data for accession P26440 downloaded
Redox data for accession P26599 downloaded
Disorder data for accession P26599 downloaded
Redox data for accession P26639 downloaded
Disorder data for accession P26639 downloaded
Redox data for accession P26640 downloaded
Disorder data for accession P26640 downloaded
Redox data for accession P27348 downloaded
Disorder data for accession P27348 downloaded
Redox data for accession P27635 downloaded
Disorder data for accession P27635 downloaded
Redox data for accession P27707 downloaded
Disorder data for accession P27707 downloaded
Redox data for accession P27797 downloaded
Disorder data for accession P27797 downloaded
Redox data for accession P28070 downloaded
Disorder data for accession P28070 downloaded
Redox data for accession P28072 downloaded
Disorder data for accession P28072 downloaded
Redox data for accession P28161 downloaded
Disorder data for accession P28161 downloaded
Redox data for accession P28300 downloaded
Disorder data for accession P28300 downloaded
Redox data for accession P28340 downloaded
Disorder data for accession P28340 downloaded
Redox data for accession P28838 downloaded
Disorder data for accession P28838 downloaded
Redox data for accession P29144 downloaded
Disorder data for accession P29144 downloaded
Redox data for accession P29317 downloaded
Disorder data for accession P29317 downloaded
Redox data for accession P29353 downloaded
Disorder data for accession P29353 downloaded
Redox data for accession P29401 downloaded
Disorder data for accession P29401 downloaded
Redox data for accession P29692 downloaded
Disorder data for accession P29692 downloaded
Redox data for accession P29992 downloaded
Disorder data for accession P29992 downloaded
Redox data for accession P30041 downloaded
Disorder data for accession P30041 downloaded
Redox data for accession P30050 downloaded
Disorder data for accession P30050 downloaded
Redox data for accession P30084 downloaded
Disorder data for accession P30084 downloaded
Redox data for accession P30086 downloaded
Disorder data for accession P30086 downloaded
Redox data for accession P30101 downloaded
Disorder data for accession P30101 downloaded
Redox data for accession P30153 downloaded
Disorder data for accession P30153 downloaded
Redox data for accession P30260 downloaded
Disorder data for accession P30260 downloaded
Redox data for accession P30281 downloaded
Disorder data for accession P30281 downloaded
Redox data for accession P30519 downloaded
Disorder data for accession P30519 downloaded
Redox data for accession P30530 downloaded
Disorder data for accession P30530 downloaded
Redox data for accession P30626 downloaded
Disorder data for accession P30626 downloaded
Redox data for accession P31040 downloaded
Disorder data for accession P31040 downloaded
Redox data for accession P31153 downloaded
Disorder data for accession P31153 downloaded
Redox data for accession P31323 downloaded
Disorder data for accession P31323 downloaded
Redox data for accession P31327 downloaded
Disorder data for accession P31327 downloaded
Redox data for accession P31751 downloaded
Disorder data for accession P31751 downloaded
Redox data for accession P31930 downloaded
Disorder data for accession P31930 downloaded
Redox data for accession P31939 downloaded
Disorder data for accession P31939 downloaded
Redox data for accession P31943 downloaded
Disorder data for accession P31943 downloaded
Redox data for accession P31948 downloaded
Disorder data for accession P31948 downloaded
Redox data for accession P32969 downloaded
Disorder data for accession P32969 downloaded
Redox data for accession P33121 downloaded
Disorder data for accession P33121 downloaded
Redox data for accession P33316 downloaded
Disorder data for accession P33316 downloaded
Redox data for accession P33527 downloaded
Disorder data for accession P33527 downloaded
Redox data for accession P33993 downloaded
Disorder data for accession P33993 downloaded
Redox data for accession P34896 downloaded
Disorder data for accession P34896 downloaded
Redox data for accession P34897 downloaded
Disorder data for accession P34897 downloaded
Redox data for accession P34932 downloaded
Disorder data for accession P34932 downloaded
Redox data for accession P35237 downloaded
Disorder data for accession P35237 downloaded
Redox data for accession P35555 downloaded
Disorder data for accession P35555 downloaded
Redox data for accession P35579 downloaded
Disorder data for accession P35579 downloaded
Redox data for accession P35606 downloaded
Disorder data for accession P35606 downloaded
Redox data for accession P35613 downloaded
Disorder data for accession P35613 downloaded
Redox data for accession P35637 downloaded
Disorder data for accession P35637 downloaded
Redox data for accession P35659 downloaded
Disorder data for accession P35659 downloaded
Redox data for accession P35754 downloaded
Disorder data for accession P35754 downloaded
Redox data for accession P35914 downloaded
Disorder data for accession P35914 downloaded
Redox data for accession P36776 downloaded
Disorder data for accession P36776 downloaded
Redox data for accession P36915 downloaded
Disorder data for accession P36915 downloaded
Redox data for accession P36957 downloaded
Disorder data for accession P36957 downloaded
Redox data for accession P36959 downloaded
Disorder data for accession P36959 downloaded
Redox data for accession P37268 downloaded
Disorder data for accession P37268 downloaded
Redox data for accession P37837 downloaded
Disorder data for accession P37837 downloaded
Redox data for accession P38646 downloaded
Disorder data for accession P38646 downloaded
Redox data for accession P38936 downloaded
Disorder data for accession P38936 downloaded
Redox data for accession P39023 downloaded
Disorder data for accession P39023 downloaded
Redox data for accession P39656 downloaded
Disorder data for accession P39656 downloaded
Redox data for accession P40123 downloaded
Disorder data for accession P40123 downloaded
Redox data for accession P40227 downloaded
Disorder data for accession P40227 downloaded
Redox data for accession P40429 downloaded
Disorder data for accession P40429 downloaded
Redox data for accession P40692 downloaded
Disorder data for accession P40692 downloaded
Redox data for accession P40925 downloaded
Disorder data for accession P40925 downloaded
Redox data for accession P40926 downloaded
Disorder data for accession P40926 downloaded
Redox data for accession P40939 downloaded
Disorder data for accession P40939 downloaded
Redox data for accession P41223 downloaded
Disorder data for accession P41223 downloaded
Redox data for accession P41229 downloaded
Disorder data for accession P41229 downloaded
Redox data for accession P41250 downloaded
Disorder data for accession P41250 downloaded
Redox data for accession P41252 downloaded
Disorder data for accession P41252 downloaded
Redox data for accession P42166 downloaded
Disorder data for accession P42166 downloaded
Redox data for accession P42285 downloaded
Disorder data for accession P42285 downloaded
Redox data for accession P42336 downloaded
Disorder data for accession P42336 downloaded
   accession                                              redox  \
0     P23396                                                 []
1     P23434                                                 []
2     P23458                              [[0, 29], [885, 905]]
3     P23467  [[1352, 1377], [1533, 1574], [1674, 1692], [17...
4     P23526                                                 []
..       ...                                                ...
95    P41250                                                 []
96    P41252                                                 []
97    P42166                                       [[668, 694]]
98    P42285                                       [[118, 134]]
99    P42336                                                 []

                                             disorder
0   [0.4347473382949829, 0.4458702504634857, 0.405...
1   [0.9001032710075378, 0.9319942593574524, 0.937...
2   [0.18777690827846527, 0.18897756934165955, 0.2...
3   [0.9282439351081848, 0.9529286623001099, 0.962...
4   [0.4582195580005646, 0.4108659029006958, 0.388...
..                                                ...
95  [0.9744666218757629, 0.9769402742385864, 0.975...
96  [0.6352701783180237, 0.6120768189430237, 0.515...
97  [0.9488979578018188, 0.9449476003646851, 0.941...
98  [0.7217981219291687, 0.7032671570777893, 0.692...
99  [0.6595120429992676, 0.646857738494873, 0.5935...

[100 rows x 3 columns]
AIUPred pickle chunk 4 saved

Redox data for accession P42345 downloaded
Disorder data for accession P42345 downloaded
Redox data for accession P42677 downloaded
Disorder data for accession P42677 downloaded
Redox data for accession P42704 downloaded
Disorder data for accession P42704 downloaded
Redox data for accession P42858 downloaded
Disorder data for accession P42858 downloaded
Redox data for accession P43034 downloaded
Disorder data for accession P43034 downloaded
Redox data for accession P43243 downloaded
Disorder data for accession P43243 downloaded
Redox data for accession P43304 downloaded
Disorder data for accession P43304 downloaded
Redox data for accession P43490 downloaded
Disorder data for accession P43490 downloaded
Redox data for accession P43897 downloaded
Disorder data for accession P43897 downloaded
Redox data for accession P45880 downloaded
Disorder data for accession P45880 downloaded
Redox data for accession P45973 downloaded
Disorder data for accession P45973 downloaded
Redox data for accession P46013 downloaded
Disorder data for accession P46013 downloaded
Redox data for accession P46020 downloaded
Disorder data for accession P46020 downloaded
Redox data for accession P46060 downloaded
Disorder data for accession P46060 downloaded
Redox data for accession P46063 downloaded
Disorder data for accession P46063 downloaded
Redox data for accession P46776 downloaded
Disorder data for accession P46776 downloaded
Redox data for accession P46777 downloaded
Disorder data for accession P46777 downloaded
Redox data for accession P46779 downloaded
Disorder data for accession P46779 downloaded
Redox data for accession P46782 downloaded
Disorder data for accession P46782 downloaded
Redox data for accession P46821 downloaded
Disorder data for accession P46821 downloaded
Redox data for accession P46939 downloaded
Disorder data for accession P46939 downloaded
Redox data for accession P46940 downloaded
Disorder data for accession P46940 downloaded
Redox data for accession P47756 downloaded
Disorder data for accession P47756 downloaded
Redox data for accession P47897 downloaded
Disorder data for accession P47897 downloaded
Redox data for accession P48059 downloaded
Disorder data for accession P48059 downloaded
Redox data for accession P48444 downloaded
Disorder data for accession P48444 downloaded
Redox data for accession P48449 downloaded
Disorder data for accession P48449 downloaded
Redox data for accession P48509 downloaded
Disorder data for accession P48509 downloaded
Redox data for accession P48556 downloaded
Disorder data for accession P48556 downloaded
Redox data for accession P48643 downloaded
Disorder data for accession P48643 downloaded
Redox data for accession P48735 downloaded
Disorder data for accession P48735 downloaded
Redox data for accession P48739 downloaded
Disorder data for accession P48739 downloaded
Redox data for accession P49023 downloaded
Disorder data for accession P49023 downloaded
Redox data for accession P49189 downloaded
Disorder data for accession P49189 downloaded
Redox data for accession P49327 downloaded
Disorder data for accession P49327 downloaded
Redox data for accession P49368 downloaded
Disorder data for accession P49368 downloaded
Redox data for accession P49454 downloaded
Disorder data for accession P49454 downloaded
Redox data for accession P49458 downloaded
Disorder data for accession P49458 downloaded
Redox data for accession P49588 downloaded
Disorder data for accession P49588 downloaded
Redox data for accession P49643 downloaded
Disorder data for accession P49643 downloaded
Redox data for accession P49720 downloaded
Disorder data for accession P49720 downloaded
Redox data for accession P49721 downloaded
Disorder data for accession P49721 downloaded
Redox data for accession P49736 downloaded
Disorder data for accession P49736 downloaded
Redox data for accession P49748 downloaded
Disorder data for accession P49748 downloaded
Redox data for accession P49773 downloaded
Disorder data for accession P49773 downloaded
Redox data for accession P49792 downloaded
Disorder data for accession P49792 downloaded
Redox data for accession P49821 downloaded
Disorder data for accession P49821 downloaded
Redox data for accession P49841 downloaded
Disorder data for accession P49841 downloaded
Redox data for accession P49915 downloaded
Disorder data for accession P49915 downloaded
Redox data for accession P50053 downloaded
Disorder data for accession P50053 downloaded
Redox data for accession P50148 downloaded
Disorder data for accession P50148 downloaded
Redox data for accession P50213 downloaded
Disorder data for accession P50213 downloaded
Redox data for accession P50395 downloaded
Disorder data for accession P50395 downloaded
Redox data for accession P50416 downloaded
Disorder data for accession P50416 downloaded
Redox data for accession P50440 downloaded
Disorder data for accession P50440 downloaded
Redox data for accession P50552 downloaded
Disorder data for accession P50552 downloaded
Redox data for accession P50750 downloaded
Disorder data for accession P50750 downloaded
Redox data for accession P50851 downloaded
Disorder data for accession P50851 downloaded
Redox data for accession P50914 downloaded
Disorder data for accession P50914 downloaded
Redox data for accession P50990 downloaded
Disorder data for accession P50990 downloaded
Redox data for accession P50991 downloaded
Disorder data for accession P50991 downloaded
Redox data for accession P50995 downloaded
Disorder data for accession P50995 downloaded
Redox data for accession P51114 downloaded
Disorder data for accession P51114 downloaded
Redox data for accession P51398 downloaded
Disorder data for accession P51398 downloaded
Redox data for accession P51610 downloaded
Disorder data for accession P51610 downloaded
Redox data for accession P51858 downloaded
Disorder data for accession P51858 downloaded
Redox data for accession P51991 downloaded
Disorder data for accession P51991 downloaded
Redox data for accession P52209 downloaded
Disorder data for accession P52209 downloaded
Redox data for accession P52294 downloaded
Disorder data for accession P52294 downloaded
Redox data for accession P52306 downloaded
Disorder data for accession P52306 downloaded
Redox data for accession P52594 downloaded
Disorder data for accession P52594 downloaded
Redox data for accession P52597 downloaded
Disorder data for accession P52597 downloaded
Redox data for accession P52701 downloaded
Disorder data for accession P52701 downloaded
Redox data for accession P52758 downloaded
Disorder data for accession P52758 downloaded
Redox data for accession P52788 downloaded
Disorder data for accession P52788 downloaded
Redox data for accession P52789 downloaded
Disorder data for accession P52789 downloaded
Redox data for accession P52907 downloaded
Disorder data for accession P52907 downloaded
Redox data for accession P53041 downloaded
Disorder data for accession P53041 downloaded
Redox data for accession P53384 downloaded
Disorder data for accession P53384 downloaded
Redox data for accession P53396 downloaded
Disorder data for accession P53396 downloaded
Redox data for accession P53618 downloaded
Disorder data for accession P53618 downloaded
Redox data for accession P53621 downloaded
Disorder data for accession P53621 downloaded
Redox data for accession P53634 downloaded
Disorder data for accession P53634 downloaded
Redox data for accession P53990 downloaded
Disorder data for accession P53990 downloaded
Redox data for accession P53992 downloaded
Disorder data for accession P53992 downloaded
Redox data for accession P54136 downloaded
Disorder data for accession P54136 downloaded
Redox data for accession P54278 downloaded
Disorder data for accession P54278 downloaded
Redox data for accession P54577 downloaded
Disorder data for accession P54577 downloaded
Redox data for accession P54687 downloaded
Disorder data for accession P54687 downloaded
Redox data for accession P54709 downloaded
Disorder data for accession P54709 downloaded
Redox data for accession P54886 downloaded
Disorder data for accession P54886 downloaded
Redox data for accession P54920 downloaded
Disorder data for accession P54920 downloaded
Redox data for accession P55036 downloaded

Disorder data for accession P55036 downloaded
Redox data for accession P55060 downloaded
Disorder data for accession P55060 downloaded
Redox data for accession P55072 downloaded
Disorder data for accession P55072 downloaded
Redox data for accession P55145 downloaded
Disorder data for accession P55145 downloaded
Redox data for accession P55209 downloaded
Disorder data for accession P55209 downloaded
Redox data for accession P55735 downloaded
Disorder data for accession P55735 downloaded
Redox data for accession P55795 downloaded
Disorder data for accession P55795 downloaded
Redox data for accession P55884 downloaded
Disorder data for accession P55884 downloaded
   accession                      redox  \
0     P42345   [[291, 328], [343, 367]]
1     P42677                 [[33, 77]]
2     P42704                         []
3     P42858  [[92, 110], [2519, 2536]]
4     P43034                         []
..       ...                        ...
95    P55145                         []
96    P55209               [[263, 283]]
97    P55735                         []
98    P55795               [[278, 294]]
99    P55884                         []

                                             disorder
0   [0.9616777300834656, 0.9562957286834717, 0.950...
1   [0.9528055787086487, 0.9500324726104736, 0.948...
2   [0.9558553695678711, 0.9625232815742493, 0.974...
3   [0.6531109809875488, 0.6755985617637634, 0.689...
4   [0.5931788682937622, 0.6322243809700012, 0.579...
..                                                ...
95  [0.5712388157844543, 0.6143710017204285, 0.830...
96  [0.9378691911697388, 0.9382889270782471, 0.938...
97  [0.1828339546918869, 0.210280179977417, 0.2062...
98  [0.266500324010849, 0.22866159677505493, 0.191...
99  [0.9679333567619324, 0.9686153531074524, 0.969...

[100 rows x 3 columns]
AIUPred pickle chunk 5 saved

Redox data for accession P56589 downloaded
Disorder data for accession P56589 downloaded
Redox data for accession P57721 downloaded
Disorder data for accession P57721 downloaded
Redox data for accession P60174 downloaded
Disorder data for accession P60174 downloaded
Redox data for accession P60709 downloaded
Disorder data for accession P60709 downloaded
Redox data for accession P60866 downloaded
Disorder data for accession P60866 downloaded
Redox data for accession P60891 downloaded
Disorder data for accession P60891 downloaded
Redox data for accession P60900 downloaded
Disorder data for accession P60900 downloaded
Redox data for accession P60953 downloaded
Disorder data for accession P60953 downloaded
Redox data for accession P60981 downloaded
Disorder data for accession P60981 downloaded
Redox data for accession P61011 downloaded
Disorder data for accession P61011 downloaded
Redox data for accession P61081 downloaded
Disorder data for accession P61081 downloaded
Redox data for accession P61086 downloaded
Disorder data for accession P61086 downloaded
Redox data for accession P61088 downloaded
Disorder data for accession P61088 downloaded
Redox data for accession P61158 downloaded
Disorder data for accession P61158 downloaded
Redox data for accession P61160 downloaded
Disorder data for accession P61160 downloaded
Redox data for accession P61224 downloaded
Disorder data for accession P61224 downloaded
Redox data for accession P61247 downloaded
Disorder data for accession P61247 downloaded
Redox data for accession P61964 downloaded
Disorder data for accession P61964 downloaded
Redox data for accession P61970 downloaded
Disorder data for accession P61970 downloaded
Redox data for accession P61978 downloaded
Disorder data for accession P61978 downloaded
Redox data for accession P62072 downloaded
Disorder data for accession P62072 downloaded
Redox data for accession P62136 downloaded
Disorder data for accession P62136 downloaded
Redox data for accession P62195 downloaded
Disorder data for accession P62195 downloaded
Redox data for accession P62241 downloaded
Disorder data for accession P62241 downloaded
Redox data for accession P62249 downloaded
Disorder data for accession P62249 downloaded
Redox data for accession P62263 downloaded
Disorder data for accession P62263 downloaded
Redox data for accession P62316 downloaded
Disorder data for accession P62316 downloaded
Redox data for accession P62318 downloaded
Disorder data for accession P62318 downloaded
Redox data for accession P62333 downloaded
Disorder data for accession P62333 downloaded
Redox data for accession P62495 downloaded
Disorder data for accession P62495 downloaded
Redox data for accession P62633 downloaded
Disorder data for accession P62633 downloaded
Redox data for accession P62701 downloaded
Disorder data for accession P62701 downloaded
Redox data for accession P62714 downloaded
Disorder data for accession P62714 downloaded
Redox data for accession P62826 downloaded
Disorder data for accession P62826 downloaded
Redox data for accession P62829 downloaded
Disorder data for accession P62829 downloaded
Redox data for accession P62834 downloaded
Disorder data for accession P62834 downloaded
Redox data for accession P62857 downloaded
Disorder data for accession P62857 downloaded
Redox data for accession P62873 downloaded
Disorder data for accession P62873 downloaded
Redox data for accession P62879 downloaded
Disorder data for accession P62879 downloaded
Redox data for accession P62888 downloaded
Disorder data for accession P62888 downloaded
Redox data for accession P62910 downloaded
Disorder data for accession P62910 downloaded
Redox data for accession P62937 downloaded
Disorder data for accession P62937 downloaded
Redox data for accession P63010 downloaded
Disorder data for accession P63010 downloaded
Redox data for accession P63096 downloaded
Disorder data for accession P63096 downloaded
Redox data for accession P63104 downloaded
Disorder data for accession P63104 downloaded
Redox data for accession P63167 downloaded
Disorder data for accession P63167 downloaded
Redox data for accession P63208 downloaded
Disorder data for accession P63208 downloaded
Redox data for accession P63220 downloaded
Disorder data for accession P63220 downloaded
Redox data for accession P63244 downloaded
Disorder data for accession P63244 downloaded
Redox data for accession P67870 downloaded
Disorder data for accession P67870 downloaded
Redox data for accession P67936 downloaded
Disorder data for accession P67936 downloaded
Redox data for accession P68104 downloaded
Disorder data for accession P68104 downloaded
Redox data for accession P78371 downloaded
Disorder data for accession P78371 downloaded
Redox data for accession P78417 downloaded
Disorder data for accession P78417 downloaded
Redox data for accession P78527 downloaded
Disorder data for accession P78527 downloaded
Redox data for accession P78559 downloaded
Disorder data for accession P78559 downloaded
Redox data for accession P83731 downloaded
Disorder data for accession P83731 downloaded
Redox data for accession P84090 downloaded
Disorder data for accession P84090 downloaded
Redox data for accession P84103 downloaded
Disorder data for accession P84103 downloaded
Redox data for accession Q00534 downloaded
Disorder data for accession Q00534 downloaded
Redox data for accession Q00537 downloaded
Disorder data for accession Q00537 downloaded
Redox data for accession Q00610 downloaded
Disorder data for accession Q00610 downloaded
Redox data for accession Q00653 downloaded
Disorder data for accession Q00653 downloaded
Redox data for accession Q00839 downloaded
Disorder data for accession Q00839 downloaded
Redox data for accession Q01082 downloaded
Disorder data for accession Q01082 downloaded
Redox data for accession Q01469 downloaded
Disorder data for accession Q01469 downloaded
Redox data for accession Q01484 downloaded
Disorder data for accession Q01484 downloaded
Redox data for accession Q01518 downloaded
Disorder data for accession Q01518 downloaded
Redox data for accession Q01658 downloaded
Disorder data for accession Q01658 downloaded
Redox data for accession Q01780 downloaded
Disorder data for accession Q01780 downloaded
Redox data for accession Q01813 downloaded
Disorder data for accession Q01813 downloaded

Redox data for accession Q01844 downloaded
Disorder data for accession Q01844 downloaded
Redox data for accession Q01970 downloaded
Disorder data for accession Q01970 downloaded
Redox data for accession Q01995 downloaded
Disorder data for accession Q01995 downloaded
Redox data for accession Q02218 downloaded
Disorder data for accession Q02218 downloaded
Redox data for accession Q02241 downloaded
Disorder data for accession Q02241 downloaded
Redox data for accession Q02252 downloaded
Disorder data for accession Q02252 downloaded
Redox data for accession Q02543 downloaded
Disorder data for accession Q02543 downloaded
Redox data for accession Q02790 downloaded
Disorder data for accession Q02790 downloaded
Redox data for accession Q02809 downloaded
Disorder data for accession Q02809 downloaded
Redox data for accession Q03001 downloaded
Disorder data for accession Q03001 downloaded
Redox data for accession Q03426 downloaded
Disorder data for accession Q03426 downloaded
Redox data for accession Q03519 downloaded
Disorder data for accession Q03519 downloaded
Redox data for accession Q04446 downloaded
Disorder data for accession Q04446 downloaded
Redox data for accession Q04637 downloaded
Disorder data for accession Q04637 downloaded
Redox data for accession Q04760 downloaded
Disorder data for accession Q04760 downloaded
Redox data for accession Q04771 downloaded
Disorder data for accession Q04771 downloaded
Redox data for accession Q04917 downloaded
Disorder data for accession Q04917 downloaded
Redox data for accession Q06124 downloaded
Disorder data for accession Q06124 downloaded
Redox data for accession Q06136 downloaded
Disorder data for accession Q06136 downloaded
Redox data for accession Q06210 downloaded
Disorder data for accession Q06210 downloaded
Redox data for accession Q06278 downloaded
Disorder data for accession Q06278 downloaded
Redox data for accession Q06546 downloaded
Disorder data for accession Q06546 downloaded
Redox data for accession Q06609 downloaded
Disorder data for accession Q06609 downloaded
Redox data for accession Q07065 downloaded
Disorder data for accession Q07065 downloaded
Redox data for accession Q07866 downloaded
Disorder data for accession Q07866 downloaded
Redox data for accession Q07954 downloaded
Disorder data for accession Q07954 downloaded
Redox data for accession Q07955 downloaded
Disorder data for accession Q07955 downloaded
Redox data for accession Q08170 downloaded
Disorder data for accession Q08170 downloaded
Redox data for accession Q08211 downloaded
Disorder data for accession Q08211 downloaded
   accession                                              redox  \
0     P56589                                                 []
1     P57721                                       [[299, 353]]
2     P60174                                                 []
3     P60709                                                 []
4     P60866                                                 []
..       ...                                                ...
95    Q07866                                       [[421, 474]]
96    Q07954  [[23, 201], [462, 524], [792, 1255], [1530, 15...
97    Q07955                                                 []
98    Q08170                                                 []
99    Q08211                              [[0, 17], [601, 626]]

                                             disorder
0   [0.6805089712142944, 0.73421311378479, 0.68959...
1   [0.8731334805488586, 0.818577766418457, 0.8663...
2   [0.3986901342868805, 0.378527969121933, 0.3555...
3   [0.34306368231773376, 0.38042646646499634, 0.6...
4   [0.955964982509613, 0.9545536637306213, 0.9605...
..                                                ...
95  [0.5170800685882568, 0.5482677221298218, 0.569...
96  [0.9660865664482117, 0.9723835587501526, 0.977...
97  [0.9322102069854736, 0.932581901550293, 0.9360...
98  [0.28462377190589905, 0.19342820346355438, 0.2...
99  [0.24960270524024963, 0.2515239715576172, 0.21...

[100 rows x 3 columns]
AIUPred pickle chunk 6 saved

Redox data for accession Q08257 downloaded
Disorder data for accession Q08257 downloaded
Redox data for accession Q08AF3 downloaded
Disorder data for accession Q08AF3 downloaded
Redox data for accession Q08AM6 downloaded
Disorder data for accession Q08AM6 downloaded
Redox data for accession Q09666 downloaded
Disorder data for accession Q09666 downloaded
Redox data for accession Q0ZGT2 downloaded
Disorder data for accession Q0ZGT2 downloaded
Redox data for accession Q10567 downloaded
Disorder data for accession Q10567 downloaded
Redox data for accession Q12765 downloaded
Disorder data for accession Q12765 downloaded
Redox data for accession Q12769 downloaded
Disorder data for accession Q12769 downloaded
Redox data for accession Q12792 downloaded
Disorder data for accession Q12792 downloaded
Redox data for accession Q12800 downloaded
Disorder data for accession Q12800 downloaded
Redox data for accession Q12846 downloaded
Disorder data for accession Q12846 downloaded
Redox data for accession Q12874 downloaded
Disorder data for accession Q12874 downloaded
Redox data for accession Q12888 downloaded
Disorder data for accession Q12888 downloaded
Redox data for accession Q12904 downloaded
Disorder data for accession Q12904 downloaded
Redox data for accession Q12931 downloaded
Disorder data for accession Q12931 downloaded
Redox data for accession Q12974 downloaded
Disorder data for accession Q12974 downloaded
Redox data for accession Q12979 downloaded
Disorder data for accession Q12979 downloaded
Redox data for accession Q13011 downloaded
Disorder data for accession Q13011 downloaded
Redox data for accession Q13042 downloaded
Disorder data for accession Q13042 downloaded
Redox data for accession Q13045 downloaded
Disorder data for accession Q13045 downloaded
Redox data for accession Q13085 downloaded
Disorder data for accession Q13085 downloaded
Redox data for accession Q13098 downloaded
Disorder data for accession Q13098 downloaded
Redox data for accession Q13126 downloaded
Disorder data for accession Q13126 downloaded
Redox data for accession Q13148 downloaded
Disorder data for accession Q13148 downloaded
Redox data for accession Q13153 downloaded
Disorder data for accession Q13153 downloaded
Redox data for accession Q13155 downloaded
Disorder data for accession Q13155 downloaded
Redox data for accession Q13158 downloaded
Disorder data for accession Q13158 downloaded
Redox data for accession Q13162 downloaded
Disorder data for accession Q13162 downloaded
Redox data for accession Q13190 downloaded
Disorder data for accession Q13190 downloaded
Redox data for accession Q13200 downloaded
Disorder data for accession Q13200 downloaded
Redox data for accession Q13242 downloaded
Disorder data for accession Q13242 downloaded
Redox data for accession Q13310 downloaded
Disorder data for accession Q13310 downloaded
Redox data for accession Q13325 downloaded
Disorder data for accession Q13325 downloaded
Redox data for accession Q13418 downloaded
Disorder data for accession Q13418 downloaded
Redox data for accession Q13423 downloaded
Disorder data for accession Q13423 downloaded
Redox data for accession Q13426 downloaded
Disorder data for accession Q13426 downloaded
Redox data for accession Q13439 downloaded
Disorder data for accession Q13439 downloaded
Redox data for accession Q13443 downloaded
Disorder data for accession Q13443 downloaded
Redox data for accession Q13501 downloaded
Disorder data for accession Q13501 downloaded
Redox data for accession Q13505 downloaded
Disorder data for accession Q13505 downloaded
Redox data for accession Q13526 downloaded
Disorder data for accession Q13526 downloaded
Redox data for accession Q13555 downloaded
Disorder data for accession Q13555 downloaded
Redox data for accession Q13557 downloaded
Disorder data for accession Q13557 downloaded
Redox data for accession Q13596 downloaded
Disorder data for accession Q13596 downloaded
Redox data for accession Q13610 downloaded
Disorder data for accession Q13610 downloaded
Redox data for accession Q13616 downloaded
Disorder data for accession Q13616 downloaded

Redox data for accession Q13617 downloaded
Disorder data for accession Q13617 downloaded
Redox data for accession Q13620 downloaded
Disorder data for accession Q13620 downloaded
Redox data for accession Q13630 downloaded
Disorder data for accession Q13630 downloaded
Redox data for accession Q13637 downloaded
Disorder data for accession Q13637 downloaded
Redox data for accession Q13740 downloaded
Disorder data for accession Q13740 downloaded
Redox data for accession Q13795 downloaded
Disorder data for accession Q13795 downloaded
Redox data for accession Q13813 downloaded
Disorder data for accession Q13813 downloaded
Redox data for accession Q13838 downloaded
Disorder data for accession Q13838 downloaded
Redox data for accession Q13867 downloaded
Disorder data for accession Q13867 downloaded
Redox data for accession Q13868 downloaded
Disorder data for accession Q13868 downloaded
Redox data for accession Q13907 downloaded
Disorder data for accession Q13907 downloaded
Redox data for accession Q14008 downloaded
Disorder data for accession Q14008 downloaded
Redox data for accession Q14019 downloaded
Disorder data for accession Q14019 downloaded
Redox data for accession Q14108 downloaded
Disorder data for accession Q14108 downloaded
Redox data for accession Q14126 downloaded
Disorder data for accession Q14126 downloaded
Redox data for accession Q14152 downloaded
Disorder data for accession Q14152 downloaded
Redox data for accession Q14155 downloaded
Disorder data for accession Q14155 downloaded
Redox data for accession Q14192 downloaded
Disorder data for accession Q14192 downloaded
Redox data for accession Q14197 downloaded
Disorder data for accession Q14197 downloaded
Redox data for accession Q14203 downloaded
Disorder data for accession Q14203 downloaded
Redox data for accession Q14204 downloaded
Disorder data for accession Q14204 downloaded
Redox data for accession Q14315 downloaded
Disorder data for accession Q14315 downloaded
Redox data for accession Q14318 downloaded
Disorder data for accession Q14318 downloaded
Redox data for accession Q14376 downloaded
Disorder data for accession Q14376 downloaded
Redox data for accession Q14558 downloaded
Disorder data for accession Q14558 downloaded
Redox data for accession Q14566 downloaded
Disorder data for accession Q14566 downloaded
Redox data for accession Q14644 downloaded
Disorder data for accession Q14644 downloaded
Redox data for accession Q14683 downloaded
Disorder data for accession Q14683 downloaded
Redox data for accession Q14690 downloaded
Disorder data for accession Q14690 downloaded
Redox data for accession Q14692 downloaded
Disorder data for accession Q14692 downloaded
Redox data for accession Q14697 downloaded
Disorder data for accession Q14697 downloaded
Redox data for accession Q14764 downloaded
Disorder data for accession Q14764 downloaded
Redox data for accession Q14847 downloaded
Disorder data for accession Q14847 downloaded
Redox data for accession Q14974 downloaded
Disorder data for accession Q14974 downloaded
Redox data for accession Q14980 downloaded
Disorder data for accession Q14980 downloaded
Redox data for accession Q14C86 downloaded
Disorder data for accession Q14C86 downloaded
Redox data for accession Q15008 downloaded
Disorder data for accession Q15008 downloaded
Redox data for accession Q15018 downloaded
Disorder data for accession Q15018 downloaded
Redox data for accession Q15019 downloaded
Disorder data for accession Q15019 downloaded
Redox data for accession Q15020 downloaded
Disorder data for accession Q15020 downloaded
Redox data for accession Q15024 downloaded
Disorder data for accession Q15024 downloaded
Redox data for accession Q15029 downloaded
Disorder data for accession Q15029 downloaded
Redox data for accession Q15041 downloaded
Disorder data for accession Q15041 downloaded
Redox data for accession Q15042 downloaded
Disorder data for accession Q15042 downloaded
Redox data for accession Q15047 downloaded
Disorder data for accession Q15047 downloaded
Redox data for accession Q15056 downloaded
Disorder data for accession Q15056 downloaded
Redox data for accession Q15075 downloaded
Disorder data for accession Q15075 downloaded
Redox data for accession Q15102 downloaded
Disorder data for accession Q15102 downloaded
Redox data for accession Q15147 downloaded
Disorder data for accession Q15147 downloaded
Redox data for accession Q15149 downloaded
Disorder data for accession Q15149 downloaded
Redox data for accession Q15154 downloaded
Disorder data for accession Q15154 downloaded
Redox data for accession Q15181 downloaded
Disorder data for accession Q15181 downloaded
Redox data for accession Q15185 downloaded
Disorder data for accession Q15185 downloaded
Redox data for accession Q15311 downloaded
Disorder data for accession Q15311 downloaded
   accession                                     redox  \
0     Q08257                                        []
1     Q08AF3                     [[0, 28], [357, 373]]
2     Q08AM6                                        []
3     Q09666  [[538, 584], [2805, 2824], [5514, 5539]]
4     Q0ZGT2                              [[651, 675]]
..       ...                                       ...
95    Q15149  [[940, 989], [1109, 1162], [3271, 3305]]
96    Q15154              [[1004, 1029], [1697, 1726]]
97    Q15181                  [[102, 125], [233, 289]]
98    Q15185                                [[49, 92]]
99    Q15311                                        []

                                             disorder
0   [0.4634188711643219, 0.4538528621196747, 0.424...
1   [0.4711979031562805, 0.5554893016815186, 0.524...
2   [0.8056607246398926, 0.7754446268081665, 0.732...
3   [0.6714980006217957, 0.6408772468566895, 0.754...
4   [0.8859938383102417, 0.849071741104126, 0.8488...
..                                                ...
95  [0.5858825445175171, 0.5498777031898499, 0.551...
96  [0.973086416721344, 0.9746835231781006, 0.9754...
97  [0.8831166625022888, 0.9182336330413818, 0.862...
98  [0.32144781947135925, 0.4053439199924469, 0.34...
99  [0.9672262072563171, 0.9682759046554565, 0.971...

[100 rows x 3 columns]
AIUPred pickle chunk 7 saved

Redox data for accession Q15345 downloaded
Disorder data for accession Q15345 downloaded
Redox data for accession Q15361 downloaded
Disorder data for accession Q15361 downloaded
Redox data for accession Q15365 downloaded
Disorder data for accession Q15365 downloaded
Redox data for accession Q15366 downloaded
Disorder data for accession Q15366 downloaded
Redox data for accession Q15386 downloaded
Disorder data for accession Q15386 downloaded
Redox data for accession Q15392 downloaded
Disorder data for accession Q15392 downloaded
Redox data for accession Q15428 downloaded
Disorder data for accession Q15428 downloaded
Redox data for accession Q15435 downloaded
Disorder data for accession Q15435 downloaded
Redox data for accession Q15437 downloaded
Disorder data for accession Q15437 downloaded
Redox data for accession Q15459 downloaded
Disorder data for accession Q15459 downloaded
Redox data for accession Q15643 downloaded
Disorder data for accession Q15643 downloaded
Redox data for accession Q15678 downloaded
Disorder data for accession Q15678 downloaded
Redox data for accession Q15738 downloaded
Disorder data for accession Q15738 downloaded
Redox data for accession Q15746 downloaded
Disorder data for accession Q15746 downloaded
Redox data for accession Q15811 downloaded
Disorder data for accession Q15811 downloaded
Redox data for accession Q15814 downloaded
Disorder data for accession Q15814 downloaded
Redox data for accession Q15942 downloaded
Disorder data for accession Q15942 downloaded
Redox data for accession Q16181 downloaded
Disorder data for accession Q16181 downloaded
Redox data for accession Q16270 downloaded
Disorder data for accession Q16270 downloaded
Redox data for accession Q16531 downloaded
Disorder data for accession Q16531 downloaded
Redox data for accession Q16543 downloaded
Disorder data for accession Q16543 downloaded
Redox data for accession Q16555 downloaded
Disorder data for accession Q16555 downloaded
Redox data for accession Q16576 downloaded

Disorder data for accession Q16576 downloaded
Redox data for accession Q16630 downloaded
Disorder data for accession Q16630 downloaded
Redox data for accession Q16643 downloaded
Disorder data for accession Q16643 downloaded
Redox data for accession Q16658 downloaded
Disorder data for accession Q16658 downloaded
Redox data for accession Q16762 downloaded
Disorder data for accession Q16762 downloaded
Redox data for accession Q16775 downloaded
Disorder data for accession Q16775 downloaded
Redox data for accession Q16891 downloaded
Disorder data for accession Q16891 downloaded
Redox data for accession Q1KMD3 downloaded
Disorder data for accession Q1KMD3 downloaded
Redox data for accession Q27J81 downloaded
Disorder data for accession Q27J81 downloaded
Redox data for accession Q2M389 downloaded
Disorder data for accession Q2M389 downloaded
Redox data for accession Q2TB10 downloaded
Disorder data for accession Q2TB10 downloaded
Redox data for accession Q32P28 downloaded
Disorder data for accession Q32P28 downloaded
Redox data for accession Q3MHD2 downloaded
Disorder data for accession Q3MHD2 downloaded
Redox data for accession Q4G148 downloaded
Disorder data for accession Q4G148 downloaded
Redox data for accession Q4VC31 downloaded
Disorder data for accession Q4VC31 downloaded
Redox data for accession Q52LJ0 downloaded
Disorder data for accession Q52LJ0 downloaded
Redox data for accession Q52LW3 downloaded
Disorder data for accession Q52LW3 downloaded
Redox data for accession Q53EP0 downloaded
Disorder data for accession Q53EP0 downloaded
Redox data for accession Q53FA7 downloaded
Disorder data for accession Q53FA7 downloaded
Redox data for accession Q53H12 downloaded
Disorder data for accession Q53H12 downloaded
Redox data for accession Q58WW2 downloaded
Disorder data for accession Q58WW2 downloaded
Redox data for accession Q5BJF6 downloaded
Disorder data for accession Q5BJF6 downloaded
Redox data for accession Q5JRA6 downloaded
Disorder data for accession Q5JRA6 downloaded
Redox data for accession Q5JSH3 downloaded
Disorder data for accession Q5JSH3 downloaded
Redox data for accession Q5JTH9 downloaded
Disorder data for accession Q5JTH9 downloaded
Redox data for accession Q5JWF2 downloaded
Disorder data for accession Q5JWF2 downloaded
Redox data for accession Q5K651 downloaded
Disorder data for accession Q5K651 downloaded
Redox data for accession Q5M775 downloaded
Disorder data for accession Q5M775 downloaded
Redox data for accession Q5MIZ7 downloaded
Disorder data for accession Q5MIZ7 downloaded
Redox data for accession Q5R3I4 downloaded
Disorder data for accession Q5R3I4 downloaded
Redox data for accession Q5RKV6 downloaded
Disorder data for accession Q5RKV6 downloaded
Redox data for accession Q5SRE5 downloaded
Disorder data for accession Q5SRE5 downloaded
Redox data for accession Q5T0D9 downloaded
Disorder data for accession Q5T0D9 downloaded
Redox data for accession Q5T4S7 downloaded
Disorder data for accession Q5T4S7 downloaded
Redox data for accession Q5T653 downloaded
Disorder data for accession Q5T653 downloaded
Redox data for accession Q5T8P6 downloaded
Disorder data for accession Q5T8P6 downloaded
Redox data for accession Q5TFE4 downloaded
Disorder data for accession Q5TFE4 downloaded
Redox data for accession Q5VU43 downloaded
Disorder data for accession Q5VU43 downloaded
Redox data for accession Q5VYK3 downloaded
Disorder data for accession Q5VYK3 downloaded
Redox data for accession Q5W0V3 downloaded
Disorder data for accession Q5W0V3 downloaded
Redox data for accession Q63ZY3 downloaded
Disorder data for accession Q63ZY3 downloaded
Redox data for accession Q658Y4 downloaded
Disorder data for accession Q658Y4 downloaded
Redox data for accession Q66K74 downloaded
Disorder data for accession Q66K74 downloaded
Redox data for accession Q676U5 downloaded
Disorder data for accession Q676U5 downloaded
Redox data for accession Q68D91 downloaded
Disorder data for accession Q68D91 downloaded
Redox data for accession Q68EM7 downloaded
Disorder data for accession Q68EM7 downloaded
Redox data for accession Q69YN2 downloaded
Disorder data for accession Q69YN2 downloaded
Redox data for accession Q6AI12 downloaded
Disorder data for accession Q6AI12 downloaded
Redox data for accession Q6DD88 downloaded
Disorder data for accession Q6DD88 downloaded
Redox data for accession Q6I9Y2 downloaded
Disorder data for accession Q6I9Y2 downloaded
Redox data for accession Q6NUK1 downloaded
Disorder data for accession Q6NUK1 downloaded
Redox data for accession Q6NUQ4 downloaded
Disorder data for accession Q6NUQ4 downloaded
Redox data for accession Q6P158 downloaded
Disorder data for accession Q6P158 downloaded
Redox data for accession Q6P1N0 downloaded
Disorder data for accession Q6P1N0 downloaded
Redox data for accession Q6P2E9 downloaded
Disorder data for accession Q6P2E9 downloaded
Redox data for accession Q6P2H3 downloaded
Disorder data for accession Q6P2H3 downloaded
Redox data for accession Q6P587 downloaded
Disorder data for accession Q6P587 downloaded
Redox data for accession Q6PCE3 downloaded
Disorder data for accession Q6PCE3 downloaded
Redox data for accession Q6PD62 downloaded
Disorder data for accession Q6PD62 downloaded
Redox data for accession Q6PFW1 downloaded
Disorder data for accession Q6PFW1 downloaded
Redox data for accession Q6PI48 downloaded
Disorder data for accession Q6PI48 downloaded
Redox data for accession Q6QNY1 downloaded
Disorder data for accession Q6QNY1 downloaded
Redox data for accession Q6R327 downloaded
Disorder data for accession Q6R327 downloaded
Redox data for accession Q6SZW1 downloaded
Disorder data for accession Q6SZW1 downloaded
Redox data for accession Q6UXH8 downloaded
Disorder data for accession Q6UXH8 downloaded
Redox data for accession Q6UXV4 downloaded
Disorder data for accession Q6UXV4 downloaded
Redox data for accession Q6YN16 downloaded
Disorder data for accession Q6YN16 downloaded
Redox data for accession Q6ZRS2 downloaded
Disorder data for accession Q6ZRS2 downloaded
Impossible to download AIUPred data for accession Q6ZUT6
Redox data for accession Q6ZUT6 downloaded
Disorder data for accession Q6ZUT6 downloaded
Redox data for accession Q6ZW76 downloaded
Disorder data for accession Q6ZW76 downloaded
Redox data for accession Q7KZF4 downloaded
Disorder data for accession Q7KZF4 downloaded
Redox data for accession Q7L014 downloaded
Disorder data for accession Q7L014 downloaded
Redox data for accession Q7L1Q6 downloaded
Disorder data for accession Q7L1Q6 downloaded
Redox data for accession Q7L273 downloaded
Disorder data for accession Q7L273 downloaded
Redox data for accession Q7L2H7 downloaded
Disorder data for accession Q7L2H7 downloaded
Redox data for accession Q7L5N7 downloaded
Disorder data for accession Q7L5N7 downloaded
Redox data for accession Q7RTS9 downloaded
Disorder data for accession Q7RTS9 downloaded
Redox data for accession Q7Z2W4 downloaded
Disorder data for accession Q7Z2W4 downloaded
   accession                                            redox  \
0     Q15345                [[0, 24], [414, 433], [577, 613]]
1     Q15361                                     [[863, 905]]
2     Q15365             [[176, 201], [210, 246], [262, 290]]
3     Q15366                         [[217, 239], [278, 309]]
4     Q15386                                       [[61, 83]]
..       ...                                              ...
95    Q7L273                                     [[345, 389]]
96    Q7L2H7                                               []
97    Q7L5N7                                               []
98    Q7RTS9                                               []
99    Q7Z2W4  [[64, 114], [142, 225], [503, 529], [706, 729]]

                                             disorder
0   [0.5612087249755859, 0.5046565532684326, 0.457...
1   [0.9614123106002808, 0.9631190299987793, 0.965...
2   [0.8746519088745117, 0.7992340326309204, 0.632...
3   [0.7924962639808655, 0.713824987411499, 0.5647...
4   [0.9674648642539978, 0.9652840495109558, 0.967...
..                                                ...
95  [0.12041522562503815, 0.11713752150535583, 0.1...
96  [0.6318807005882263, 0.6754509806632996, 0.707...
97  [0.9091097116470337, 0.9178804755210876, 0.918...
98  [0.9113113284111023, 0.9012885689735413, 0.893...
99  [0.3371352255344391, 0.31252774596214294, 0.39...

[100 rows x 3 columns]
AIUPred pickle chunk 8 saved

Redox data for accession Q7Z2Z2 downloaded
Disorder data for accession Q7Z2Z2 downloaded
Redox data for accession Q7Z4Q2 downloaded
Disorder data for accession Q7Z4Q2 downloaded
Redox data for accession Q7Z4V5 downloaded
Disorder data for accession Q7Z4V5 downloaded
Redox data for accession Q7Z6Z7 downloaded
Disorder data for accession Q7Z6Z7 downloaded
Redox data for accession Q86U42 downloaded
Disorder data for accession Q86U42 downloaded
Redox data for accession Q86UP2 downloaded
Disorder data for accession Q86UP2 downloaded
Redox data for accession Q86VI3 downloaded
Disorder data for accession Q86VI3 downloaded
Redox data for accession Q86VP6 downloaded
Disorder data for accession Q86VP6 downloaded
Redox data for accession Q86VU5 downloaded
Disorder data for accession Q86VU5 downloaded
Redox data for accession Q86X55 downloaded
Disorder data for accession Q86X55 downloaded
Redox data for accession Q86XZ4 downloaded
Disorder data for accession Q86XZ4 downloaded
Redox data for accession Q86Y37 downloaded
Disorder data for accession Q86Y37 downloaded
Redox data for accession Q86Y82 downloaded
Disorder data for accession Q86Y82 downloaded
Redox data for accession Q86YH6 downloaded
Disorder data for accession Q86YH6 downloaded
Redox data for accession Q8IU81 downloaded
Disorder data for accession Q8IU81 downloaded
Redox data for accession Q8IUR7 downloaded
Disorder data for accession Q8IUR7 downloaded
Redox data for accession Q8IWA0 downloaded
Disorder data for accession Q8IWA0 downloaded
Redox data for accession Q8IWB7 downloaded
Disorder data for accession Q8IWB7 downloaded
Redox data for accession Q8IWE2 downloaded
Disorder data for accession Q8IWE2 downloaded
Redox data for accession Q8IWR0 downloaded
Disorder data for accession Q8IWR0 downloaded
Redox data for accession Q8IX04 downloaded
Disorder data for accession Q8IX04 downloaded
Redox data for accession Q8IXK0 downloaded
Disorder data for accession Q8IXK0 downloaded
Redox data for accession Q8IXY8 downloaded
Disorder data for accession Q8IXY8 downloaded
Redox data for accession Q8IY81 downloaded
Disorder data for accession Q8IY81 downloaded
Redox data for accession Q8IYD1 downloaded
Disorder data for accession Q8IYD1 downloaded
Redox data for accession Q8IYS1 downloaded
Disorder data for accession Q8IYS1 downloaded
Redox data for accession Q8IYS2 downloaded
Disorder data for accession Q8IYS2 downloaded
Redox data for accession Q8IZ83 downloaded
Disorder data for accession Q8IZ83 downloaded
Redox data for accession Q8IZH2 downloaded
Disorder data for accession Q8IZH2 downloaded
Redox data for accession Q8IZP0 downloaded
Disorder data for accession Q8IZP0 downloaded
Redox data for accession Q8N0V3 downloaded
Disorder data for accession Q8N0V3 downloaded
Redox data for accession Q8N163 downloaded
Disorder data for accession Q8N163 downloaded
Redox data for accession Q8N1F7 downloaded
Disorder data for accession Q8N1F7 downloaded
Redox data for accession Q8N392 downloaded
Disorder data for accession Q8N392 downloaded
Redox data for accession Q8N3C0 downloaded
Disorder data for accession Q8N3C0 downloaded
Redox data for accession Q8N3Y1 downloaded
Disorder data for accession Q8N3Y1 downloaded
Redox data for accession Q8N556 downloaded
Disorder data for accession Q8N556 downloaded
Redox data for accession Q8N5A5 downloaded
Disorder data for accession Q8N5A5 downloaded
Redox data for accession Q8N5L8 downloaded
Disorder data for accession Q8N5L8 downloaded
Redox data for accession Q8N806 downloaded
Disorder data for accession Q8N806 downloaded
Redox data for accession Q8NAP3 downloaded
Disorder data for accession Q8NAP3 downloaded
Redox data for accession Q8NAV1 downloaded
Disorder data for accession Q8NAV1 downloaded
Redox data for accession Q8NB16 downloaded
Disorder data for accession Q8NB16 downloaded
Redox data for accession Q8NB49 downloaded
Disorder data for accession Q8NB49 downloaded
Redox data for accession Q8NE71 downloaded
Disorder data for accession Q8NE71 downloaded
Redox data for accession Q8NEN9 downloaded
Disorder data for accession Q8NEN9 downloaded
Redox data for accession Q8NEW0 downloaded
Disorder data for accession Q8NEW0 downloaded
Redox data for accession Q8NF37 downloaded
Disorder data for accession Q8NF37 downloaded
Redox data for accession Q8NF91 downloaded
Disorder data for accession Q8NF91 downloaded
Redox data for accession Q8NFH4 downloaded
Disorder data for accession Q8NFH4 downloaded
Redox data for accession Q8NG68 downloaded
Disorder data for accession Q8NG68 downloaded
Redox data for accession Q8TAE8 downloaded
Disorder data for accession Q8TAE8 downloaded
Redox data for accession Q8TB52 downloaded
Disorder data for accession Q8TB52 downloaded
Redox data for accession Q8TBC4 downloaded
Disorder data for accession Q8TBC4 downloaded
Redox data for accession Q8TCG1 downloaded
Disorder data for accession Q8TCG1 downloaded
Redox data for accession Q8TCS8 downloaded
Disorder data for accession Q8TCS8 downloaded
Redox data for accession Q8TDD1 downloaded
Disorder data for accession Q8TDD1 downloaded
Redox data for accession Q8TDX7 downloaded
Disorder data for accession Q8TDX7 downloaded
Redox data for accession Q8TEQ6 downloaded
Disorder data for accession Q8TEQ6 downloaded
Redox data for accession Q8TEX9 downloaded
Disorder data for accession Q8TEX9 downloaded
Redox data for accession Q8TF42 downloaded
Disorder data for accession Q8TF42 downloaded
Redox data for accession Q8TF68 downloaded
Disorder data for accession Q8TF68 downloaded
Redox data for accession Q8WTW4 downloaded
Disorder data for accession Q8WTW4 downloaded
Redox data for accession Q8WUM4 downloaded
Disorder data for accession Q8WUM4 downloaded
Redox data for accession Q8WUP2 downloaded
Disorder data for accession Q8WUP2 downloaded
Redox data for accession Q8WV93 downloaded
Disorder data for accession Q8WV93 downloaded
Redox data for accession Q8WVM7 downloaded
Disorder data for accession Q8WVM7 downloaded
Redox data for accession Q8WVT3 downloaded
Disorder data for accession Q8WVT3 downloaded
Redox data for accession Q8WWI1 downloaded
Disorder data for accession Q8WWI1 downloaded
Redox data for accession Q8WX92 downloaded
Disorder data for accession Q8WX92 downloaded
Redox data for accession Q8WX93 downloaded
Disorder data for accession Q8WX93 downloaded
Redox data for accession Q92499 downloaded
Disorder data for accession Q92499 downloaded
Redox data for accession Q92538 downloaded
Disorder data for accession Q92538 downloaded
Redox data for accession Q92547 downloaded
Disorder data for accession Q92547 downloaded
Redox data for accession Q92598 downloaded
Disorder data for accession Q92598 downloaded
Redox data for accession Q92614 downloaded
Disorder data for accession Q92614 downloaded
Redox data for accession Q92616 downloaded
Disorder data for accession Q92616 downloaded
Redox data for accession Q92685 downloaded
Disorder data for accession Q92685 downloaded
Redox data for accession Q92688 downloaded
Disorder data for accession Q92688 downloaded
Redox data for accession Q92747 downloaded
Disorder data for accession Q92747 downloaded
Redox data for accession Q92791 downloaded
Disorder data for accession Q92791 downloaded
Redox data for accession Q92841 downloaded
Disorder data for accession Q92841 downloaded
Redox data for accession Q92870 downloaded
Disorder data for accession Q92870 downloaded
Redox data for accession Q92878 downloaded
Disorder data for accession Q92878 downloaded
Redox data for accession Q92888 downloaded
Disorder data for accession Q92888 downloaded
Redox data for accession Q92896 downloaded
Disorder data for accession Q92896 downloaded
Redox data for accession Q92900 downloaded
Disorder data for accession Q92900 downloaded
Redox data for accession Q92905 downloaded
Disorder data for accession Q92905 downloaded
Redox data for accession Q92945 downloaded
Disorder data for accession Q92945 downloaded
Redox data for accession Q92973 downloaded
Disorder data for accession Q92973 downloaded
Redox data for accession Q92974 downloaded
Disorder data for accession Q92974 downloaded
Redox data for accession Q93008 downloaded
Disorder data for accession Q93008 downloaded
Redox data for accession Q93009 downloaded

Disorder data for accession Q93009 downloaded
Redox data for accession Q93034 downloaded
Disorder data for accession Q93034 downloaded
Redox data for accession Q93073 downloaded
Disorder data for accession Q93073 downloaded
Redox data for accession Q969F9 downloaded
Disorder data for accession Q969F9 downloaded
Redox data for accession Q969Q5 downloaded
Disorder data for accession Q969Q5 downloaded
Redox data for accession Q969R2 downloaded
Disorder data for accession Q969R2 downloaded
Redox data for accession Q969V5 downloaded
Disorder data for accession Q969V5 downloaded
Redox data for accession Q96A33 downloaded
Disorder data for accession Q96A33 downloaded
   accession                                       redox  \
0     Q7Z2Z2                                [[945, 971]]
1     Q7Z4Q2                     [[44, 117], [367, 410]]
2     Q7Z4V5                                          []
3     Q7Z6Z7  [[2623, 2682], [3295, 3312], [3325, 3402]]
4     Q86U42                                          []
..       ...                                         ...
95    Q969F9                                [[240, 276]]
96    Q969Q5                                [[185, 203]]
97    Q969R2                                [[750, 771]]
98    Q969V5                                [[290, 352]]
99    Q96A33                                          []

                                             disorder
0   [0.3999044597148895, 0.33398520946502686, 0.37...
1   [0.9635007977485657, 0.9626993536949158, 0.966...
2   [0.1842426061630249, 0.20131957530975342, 0.22...
3   [0.8417747020721436, 0.8499825596809387, 0.829...
4   [0.973024308681488, 0.9755134582519531, 0.9420...
..                                                ...
95  [0.21213398873806, 0.2583315670490265, 0.24982...
96  [0.2517959773540497, 0.27004048228263855, 0.34...
97  [0.9770599603652954, 0.9793764352798462, 0.980...
98  [0.7135459184646606, 0.7266877293586731, 0.723...
99  [0.9264702200889587, 0.9278115034103394, 0.936...

[100 rows x 3 columns]
AIUPred pickle chunk 9 saved

Redox data for accession Q96A65 downloaded
Disorder data for accession Q96A65 downloaded
Redox data for accession Q96AC1 downloaded
Disorder data for accession Q96AC1 downloaded
Redox data for accession Q96AE4 downloaded
Disorder data for accession Q96AE4 downloaded
Redox data for accession Q96AG4 downloaded
Disorder data for accession Q96AG4 downloaded
Redox data for accession Q96AT9 downloaded
Disorder data for accession Q96AT9 downloaded
Redox data for accession Q96BY6 downloaded
Disorder data for accession Q96BY6 downloaded
Redox data for accession Q96C90 downloaded
Disorder data for accession Q96C90 downloaded
Redox data for accession Q96CS3 downloaded
Disorder data for accession Q96CS3 downloaded
Redox data for accession Q96CV9 downloaded
Disorder data for accession Q96CV9 downloaded
Redox data for accession Q96CW6 downloaded
Disorder data for accession Q96CW6 downloaded
Redox data for accession Q96DG6 downloaded
Disorder data for accession Q96DG6 downloaded
Redox data for accession Q96ED9 downloaded
Disorder data for accession Q96ED9 downloaded
Redox data for accession Q96EL3 downloaded
Disorder data for accession Q96EL3 downloaded
Redox data for accession Q96FJ2 downloaded
Disorder data for accession Q96FJ2 downloaded
Redox data for accession Q96FW1 downloaded
Disorder data for accession Q96FW1 downloaded
Redox data for accession Q96FX7 downloaded
Disorder data for accession Q96FX7 downloaded
Redox data for accession Q96FZ7 downloaded
Disorder data for accession Q96FZ7 downloaded
Redox data for accession Q96GG9 downloaded
Disorder data for accession Q96GG9 downloaded
Redox data for accession Q96GX9 downloaded
Disorder data for accession Q96GX9 downloaded
Redox data for accession Q96HC4 downloaded
Disorder data for accession Q96HC4 downloaded
Redox data for accession Q96HE7 downloaded
Disorder data for accession Q96HE7 downloaded
Redox data for accession Q96I24 downloaded
Disorder data for accession Q96I24 downloaded
Redox data for accession Q96I25 downloaded
Disorder data for accession Q96I25 downloaded
Redox data for accession Q96II8 downloaded
Disorder data for accession Q96II8 downloaded
Redox data for accession Q96JB2 downloaded
Disorder data for accession Q96JB2 downloaded
Redox data for accession Q96JB5 downloaded
Disorder data for accession Q96JB5 downloaded
Redox data for accession Q96K76 downloaded
Disorder data for accession Q96K76 downloaded
Redox data for accession Q96KR1 downloaded
Disorder data for accession Q96KR1 downloaded
Redox data for accession Q96ME1 downloaded
Disorder data for accession Q96ME1 downloaded
Redox data for accession Q96MX6 downloaded
Disorder data for accession Q96MX6 downloaded
Redox data for accession Q96N67 downloaded
Disorder data for accession Q96N67 downloaded
Redox data for accession Q96P48 downloaded
Disorder data for accession Q96P48 downloaded
Redox data for accession Q96P50 downloaded
Disorder data for accession Q96P50 downloaded
Redox data for accession Q96PK6 downloaded
Disorder data for accession Q96PK6 downloaded
Redox data for accession Q96Q15 downloaded
Disorder data for accession Q96Q15 downloaded
Redox data for accession Q96QB1 downloaded
Disorder data for accession Q96QB1 downloaded
Redox data for accession Q96QK1 downloaded
Disorder data for accession Q96QK1 downloaded
Redox data for accession Q96RS6 downloaded
Disorder data for accession Q96RS6 downloaded
Redox data for accession Q96RU3 downloaded
Disorder data for accession Q96RU3 downloaded
Redox data for accession Q96T21 downloaded
Disorder data for accession Q96T21 downloaded
Redox data for accession Q96T76 downloaded
Disorder data for accession Q96T76 downloaded
Redox data for accession Q96T88 downloaded
Disorder data for accession Q96T88 downloaded
Redox data for accession Q96TA1 downloaded
Disorder data for accession Q96TA1 downloaded
Redox data for accession Q99426 downloaded
Disorder data for accession Q99426 downloaded
Redox data for accession Q99439 downloaded
Disorder data for accession Q99439 downloaded
Redox data for accession Q99442 downloaded
Disorder data for accession Q99442 downloaded
Redox data for accession Q99459 downloaded
Disorder data for accession Q99459 downloaded
Redox data for accession Q99471 downloaded
Disorder data for accession Q99471 downloaded
Redox data for accession Q99536 downloaded
Disorder data for accession Q99536 downloaded
Redox data for accession Q99567 downloaded
Disorder data for accession Q99567 downloaded
Redox data for accession Q99575 downloaded
Disorder data for accession Q99575 downloaded
Redox data for accession Q99598 downloaded
Disorder data for accession Q99598 downloaded
Redox data for accession Q99741 downloaded
Disorder data for accession Q99741 downloaded
Redox data for accession Q99797 downloaded
Disorder data for accession Q99797 downloaded
Redox data for accession Q99805 downloaded
Disorder data for accession Q99805 downloaded
Redox data for accession Q99832 downloaded
Disorder data for accession Q99832 downloaded
Redox data for accession Q99873 downloaded
Disorder data for accession Q99873 downloaded
Redox data for accession Q99942 downloaded
Disorder data for accession Q99942 downloaded
Redox data for accession Q99961 downloaded
Disorder data for accession Q99961 downloaded
Redox data for accession Q9BPW8 downloaded
Disorder data for accession Q9BPW8 downloaded
Redox data for accession Q9BPX3 downloaded
Impossible to download AIUPred data for accession Q9BPX3
Disorder data for accession Q9BPX3 downloaded
Redox data for accession Q9BQ52 downloaded
Disorder data for accession Q9BQ52 downloaded
Redox data for accession Q9BQ70 downloaded
Disorder data for accession Q9BQ70 downloaded
Redox data for accession Q9BQB6 downloaded
Disorder data for accession Q9BQB6 downloaded
Redox data for accession Q9BRP1 downloaded
Disorder data for accession Q9BRP1 downloaded
Redox data for accession Q9BRX2 downloaded
Disorder data for accession Q9BRX2 downloaded
Redox data for accession Q9BSH4 downloaded
Disorder data for accession Q9BSH4 downloaded
Redox data for accession Q9BSJ8 downloaded
Disorder data for accession Q9BSJ8 downloaded

Redox data for accession Q9BSL1 downloaded
Disorder data for accession Q9BSL1 downloaded
Redox data for accession Q9BTT0 downloaded
Disorder data for accession Q9BTT0 downloaded
Redox data for accession Q9BTV5 downloaded
Disorder data for accession Q9BTV5 downloaded
Redox data for accession Q9BTW9 downloaded
Disorder data for accession Q9BTW9 downloaded
Redox data for accession Q9BU76 downloaded
Disorder data for accession Q9BU76 downloaded
Redox data for accession Q9BUF5 downloaded
Disorder data for accession Q9BUF5 downloaded
Redox data for accession Q9BUJ2 downloaded
Disorder data for accession Q9BUJ2 downloaded
Redox data for accession Q9BV81 downloaded
Disorder data for accession Q9BV81 downloaded
Redox data for accession Q9BVP2 downloaded
Disorder data for accession Q9BVP2 downloaded
Redox data for accession Q9BW19 downloaded
Disorder data for accession Q9BW19 downloaded
Redox data for accession Q9BWU0 downloaded
Disorder data for accession Q9BWU0 downloaded
Redox data for accession Q9BXF6 downloaded
Disorder data for accession Q9BXF6 downloaded
Redox data for accession Q9BXJ9 downloaded
Disorder data for accession Q9BXJ9 downloaded
Redox data for accession Q9BXK5 downloaded
Disorder data for accession Q9BXK5 downloaded
Redox data for accession Q9BXP5 downloaded
Disorder data for accession Q9BXP5 downloaded
Redox data for accession Q9BXR0 downloaded
Disorder data for accession Q9BXR0 downloaded
Redox data for accession Q9BXY0 downloaded
Disorder data for accession Q9BXY0 downloaded
Redox data for accession Q9BY32 downloaded
Disorder data for accession Q9BY32 downloaded
Redox data for accession Q9BY44 downloaded
Disorder data for accession Q9BY44 downloaded
Redox data for accession Q9BYT8 downloaded
Disorder data for accession Q9BYT8 downloaded
Redox data for accession Q9BYX2 downloaded
Disorder data for accession Q9BYX2 downloaded
Redox data for accession Q9BZ29 downloaded
Disorder data for accession Q9BZ29 downloaded
Redox data for accession Q9BZE1 downloaded
Disorder data for accession Q9BZE1 downloaded
Redox data for accession Q9BZF1 downloaded
Disorder data for accession Q9BZF1 downloaded
Redox data for accession Q9BZF9 downloaded
Disorder data for accession Q9BZF9 downloaded
Redox data for accession Q9BZH6 downloaded
Disorder data for accession Q9BZH6 downloaded
Redox data for accession Q9BZL4 downloaded
Disorder data for accession Q9BZL4 downloaded
Redox data for accession Q9C0B1 downloaded
Disorder data for accession Q9C0B1 downloaded
Redox data for accession Q9C0D5 downloaded
Disorder data for accession Q9C0D5 downloaded
Redox data for accession Q9GZN8 downloaded
Disorder data for accession Q9GZN8 downloaded
Redox data for accession Q9GZR7 downloaded
Disorder data for accession Q9GZR7 downloaded
Redox data for accession Q9GZS1 downloaded
Disorder data for accession Q9GZS1 downloaded
   accession                                 redox  \
0     Q96A65                                    []
1     Q96AC1                          [[401, 429]]
2     Q96AE4                          [[142, 164]]
3     Q96AG4                          [[123, 155]]
4     Q96AT9                             [[0, 19]]
..       ...                                   ...
95    Q9C0B1  [[162, 188], [339, 358], [454, 494]]
96    Q9C0D5                          [[131, 177]]
97    Q9GZN8                          [[153, 174]]
98    Q9GZR7                                    []
99    Q9GZS1                           [[99, 174]]

                                             disorder
0   [0.9411023259162903, 0.9417685270309448, 0.957...
1   [0.20108364522457123, 0.24241162836551666, 0.3...
2   [0.967380940914154, 0.9731827974319458, 0.9757...
3   [0.9519845247268677, 0.9459549188613892, 0.945...
4   [0.1912926286458969, 0.563433051109314, 0.5926...
..                                                ...
95  [0.7922578454017639, 0.7466980218887329, 0.715...
96  [0.9365859627723694, 0.9359602332115173, 0.939...
97  [0.957676351070404, 0.9579092860221863, 0.9553...
98  [0.9423770308494568, 0.9359455704689026, 0.916...
99  [0.4379409849643707, 0.4237017035484314, 0.500...

[100 rows x 3 columns]
AIUPred pickle chunk 10 saved

Redox data for accession Q9H0C8 downloaded
Disorder data for accession Q9H0C8 downloaded
Redox data for accession Q9H1B7 downloaded
Disorder data for accession Q9H1B7 downloaded
Redox data for accession Q9H204 downloaded
Disorder data for accession Q9H204 downloaded
Redox data for accession Q9H2G2 downloaded
Disorder data for accession Q9H2G2 downloaded
Redox data for accession Q9H2M9 downloaded
Disorder data for accession Q9H2M9 downloaded
Redox data for accession Q9H2U2 downloaded
Disorder data for accession Q9H2U2 downloaded
Redox data for accession Q9H3U1 downloaded
Disorder data for accession Q9H3U1 downloaded
Redox data for accession Q9H488 downloaded
Disorder data for accession Q9H488 downloaded
Redox data for accession Q9H4A3 downloaded
Disorder data for accession Q9H4A3 downloaded
Redox data for accession Q9H4H8 downloaded
Disorder data for accession Q9H4H8 downloaded
Redox data for accession Q9H4L4 downloaded
Disorder data for accession Q9H4L4 downloaded
Redox data for accession Q9H583 downloaded
Disorder data for accession Q9H583 downloaded
Redox data for accession Q9H6R4 downloaded
Disorder data for accession Q9H6R4 downloaded
Redox data for accession Q9H7C4 downloaded
Disorder data for accession Q9H7C4 downloaded
Redox data for accession Q9H8Y8 downloaded
Disorder data for accession Q9H8Y8 downloaded
Redox data for accession Q9H936 downloaded
Disorder data for accession Q9H936 downloaded
Redox data for accession Q9H9A5 downloaded
Disorder data for accession Q9H9A5 downloaded
Redox data for accession Q9HAU4 downloaded
Disorder data for accession Q9HAU4 downloaded
Redox data for accession Q9HAV0 downloaded
Disorder data for accession Q9HAV0 downloaded
Redox data for accession Q9HAV4 downloaded
Disorder data for accession Q9HAV4 downloaded
Redox data for accession Q9HB71 downloaded
Disorder data for accession Q9HB71 downloaded
Redox data for accession Q9HBH5 downloaded
Disorder data for accession Q9HBH5 downloaded
Redox data for accession Q9HC35 downloaded
Disorder data for accession Q9HC35 downloaded
Redox data for accession Q9HC36 downloaded
Disorder data for accession Q9HC36 downloaded
Redox data for accession Q9HCC0 downloaded
Disorder data for accession Q9HCC0 downloaded
Redox data for accession Q9HCG7 downloaded
Disorder data for accession Q9HCG7 downloaded
Redox data for accession Q9HD20 downloaded
Disorder data for accession Q9HD20 downloaded
Redox data for accession Q9HD33 downloaded
Disorder data for accession Q9HD33 downloaded
Redox data for accession Q9HD67 downloaded
Disorder data for accession Q9HD67 downloaded
Redox data for accession Q9NP61 downloaded
Disorder data for accession Q9NP61 downloaded
Redox data for accession Q9NP79 downloaded
Disorder data for accession Q9NP79 downloaded
Redox data for accession Q9NP92 downloaded
Disorder data for accession Q9NP92 downloaded
Redox data for accession Q9NPG3 downloaded
Disorder data for accession Q9NPG3 downloaded
Redox data for accession Q9NPJ8 downloaded
Disorder data for accession Q9NPJ8 downloaded
Redox data for accession Q9NQC3 downloaded
Disorder data for accession Q9NQC3 downloaded
Redox data for accession Q9NQG5 downloaded
Disorder data for accession Q9NQG5 downloaded
Redox data for accession Q9NQR4 downloaded
Disorder data for accession Q9NQR4 downloaded
Redox data for accession Q9NQW6 downloaded
Disorder data for accession Q9NQW6 downloaded
Redox data for accession Q9NQW7 downloaded
Disorder data for accession Q9NQW7 downloaded
Redox data for accession Q9NR56 downloaded
Disorder data for accession Q9NR56 downloaded
Redox data for accession Q9NRR4 downloaded
Disorder data for accession Q9NRR4 downloaded
Redox data for accession Q9NS00 downloaded
Disorder data for accession Q9NS00 downloaded
Redox data for accession Q9NSK0 downloaded
Disorder data for accession Q9NSK0 downloaded
Redox data for accession Q9NT62 downloaded
Disorder data for accession Q9NT62 downloaded
Redox data for accession Q9NTJ3 downloaded
Disorder data for accession Q9NTJ3 downloaded

Redox data for accession Q9NUJ1 downloaded
Disorder data for accession Q9NUJ1 downloaded
Redox data for accession Q9NUP9 downloaded
Disorder data for accession Q9NUP9 downloaded
Redox data for accession Q9NUQ6 downloaded
Disorder data for accession Q9NUQ6 downloaded
Redox data for accession Q9NUQ9 downloaded
Disorder data for accession Q9NUQ9 downloaded
Redox data for accession Q9NVM9 downloaded
Disorder data for accession Q9NVM9 downloaded
Redox data for accession Q9NVN8 downloaded
Disorder data for accession Q9NVN8 downloaded
Redox data for accession Q9NVU7 downloaded
Disorder data for accession Q9NVU7 downloaded
Redox data for accession Q9NVW2 downloaded
Disorder data for accession Q9NVW2 downloaded
Redox data for accession Q9NVZ3 downloaded
Disorder data for accession Q9NVZ3 downloaded
Redox data for accession Q9NW13 downloaded
Disorder data for accession Q9NW13 downloaded
Redox data for accession Q9NW15 downloaded
Disorder data for accession Q9NW15 downloaded
Redox data for accession Q9NX08 downloaded
Disorder data for accession Q9NX08 downloaded
Redox data for accession Q9NXG2 downloaded
Disorder data for accession Q9NXG2 downloaded
Redox data for accession Q9NXH8 downloaded
Disorder data for accession Q9NXH8 downloaded
Redox data for accession Q9NY33 downloaded
Disorder data for accession Q9NY33 downloaded
Redox data for accession Q9NYB9 downloaded
Disorder data for accession Q9NYB9 downloaded
Redox data for accession Q9NYK5 downloaded
Disorder data for accession Q9NYK5 downloaded
Redox data for accession Q9NYL2 downloaded
Disorder data for accession Q9NYL2 downloaded
Redox data for accession Q9NZD2 downloaded
Disorder data for accession Q9NZD2 downloaded
Redox data for accession Q9NZI7 downloaded
Disorder data for accession Q9NZI7 downloaded
Redox data for accession Q9NZI8 downloaded
Disorder data for accession Q9NZI8 downloaded
Redox data for accession Q9NZJ4 downloaded
Disorder data for accession Q9NZJ4 downloaded
Redox data for accession Q9NZJ7 downloaded
Disorder data for accession Q9NZJ7 downloaded
Redox data for accession Q9NZL9 downloaded
Disorder data for accession Q9NZL9 downloaded
Redox data for accession Q9NZM1 downloaded
Disorder data for accession Q9NZM1 downloaded
Redox data for accession Q9NZZ3 downloaded
Disorder data for accession Q9NZZ3 downloaded
Redox data for accession Q9P0K7 downloaded
Disorder data for accession Q9P0K7 downloaded
Redox data for accession Q9P0L0 downloaded
Disorder data for accession Q9P0L0 downloaded
Redox data for accession Q9P287 downloaded
Disorder data for accession Q9P287 downloaded
Redox data for accession Q9P291 downloaded
Disorder data for accession Q9P291 downloaded
Redox data for accession Q9P2E9 downloaded
Disorder data for accession Q9P2E9 downloaded
Redox data for accession Q9P2J5 downloaded
Disorder data for accession Q9P2J5 downloaded
Redox data for accession Q9P2T1 downloaded
Disorder data for accession Q9P2T1 downloaded
Redox data for accession Q9P2W9 downloaded
Disorder data for accession Q9P2W9 downloaded
Redox data for accession Q9UBB4 downloaded
Disorder data for accession Q9UBB4 downloaded
Redox data for accession Q9UBB9 downloaded
Disorder data for accession Q9UBB9 downloaded
Redox data for accession Q9UBE0 downloaded
Disorder data for accession Q9UBE0 downloaded
Redox data for accession Q9UBF2 downloaded
Disorder data for accession Q9UBF2 downloaded
Redox data for accession Q9UBG0 downloaded
Disorder data for accession Q9UBG0 downloaded
Redox data for accession Q9UBI1 downloaded
Disorder data for accession Q9UBI1 downloaded
Redox data for accession Q9UBI6 downloaded
Disorder data for accession Q9UBI6 downloaded
Redox data for accession Q9UBM7 downloaded
Disorder data for accession Q9UBM7 downloaded
Redox data for accession Q9UBT2 downloaded
Disorder data for accession Q9UBT2 downloaded
Redox data for accession Q9UDY4 downloaded
Disorder data for accession Q9UDY4 downloaded
Redox data for accession Q9UEW8 downloaded
Disorder data for accession Q9UEW8 downloaded
Redox data for accession Q9UFN0 downloaded
Disorder data for accession Q9UFN0 downloaded
Redox data for accession Q9UGP4 downloaded
Disorder data for accession Q9UGP4 downloaded
Redox data for accession Q9UGP8 downloaded
Disorder data for accession Q9UGP8 downloaded
Redox data for accession Q9UHB9 downloaded
Disorder data for accession Q9UHB9 downloaded
Redox data for accession Q9UI14 downloaded
Disorder data for accession Q9UI14 downloaded
Redox data for accession Q9UID3 downloaded
Disorder data for accession Q9UID3 downloaded
Redox data for accession Q9UJA5 downloaded
Disorder data for accession Q9UJA5 downloaded
Redox data for accession Q9UJU6 downloaded
Disorder data for accession Q9UJU6 downloaded
Redox data for accession Q9UK41 downloaded
Disorder data for accession Q9UK41 downloaded
Redox data for accession Q9UK61 downloaded
Disorder data for accession Q9UK61 downloaded
   accession                  redox  \
0     Q9H0C8                     []
1     Q9H1B7  [[2, 53], [704, 795]]
2     Q9H204             [[39, 93]]
3     Q9H2G2                     []
4     Q9H2M9                     []
..       ...                    ...
95    Q9UID3           [[766, 782]]
96    Q9UJA5                     []
97    Q9UJU6                     []
98    Q9UK41                     []
99    Q9UK61                     []

                                             disorder
0   [0.9727692008018494, 0.9752423167228699, 0.978...
1   [0.9080359935760498, 0.8606981039047241, 0.781...
2   [0.9747959971427917, 0.9741731882095337, 0.979...
3   [0.4686247408390045, 0.49270835518836975, 0.59...
4   [0.33812886476516724, 0.38839057087898254, 0.4...
..                                                ...
95  [0.9699824452400208, 0.9686371684074402, 0.974...
96  [0.9769726991653442, 0.9759214520454407, 0.974...
97  [0.18567097187042236, 0.21659928560256958, 0.2...
98  [0.9586377739906311, 0.9623861312866211, 0.961...
99  [0.9657752513885498, 0.9678490161895752, 0.971...

[100 rows x 3 columns]
AIUPred pickle chunk 11 saved

Redox data for accession Q9UKG1 downloaded
Disorder data for accession Q9UKG1 downloaded
Redox data for accession Q9UKP4 downloaded
Disorder data for accession Q9UKP4 downloaded
Redox data for accession Q9UKX5 downloaded
Disorder data for accession Q9UKX5 downloaded
Redox data for accession Q9UL54 downloaded
Disorder data for accession Q9UL54 downloaded
Redox data for accession Q9ULC4 downloaded
Disorder data for accession Q9ULC4 downloaded
Redox data for accession Q9ULS5 downloaded
Disorder data for accession Q9ULS5 downloaded
Redox data for accession Q9ULT8 downloaded
Disorder data for accession Q9ULT8 downloaded
Redox data for accession Q9ULV4 downloaded
Disorder data for accession Q9ULV4 downloaded
Redox data for accession Q9ULX3 downloaded
Disorder data for accession Q9ULX3 downloaded
Redox data for accession Q9UM54 downloaded
Disorder data for accession Q9UM54 downloaded
Redox data for accession Q9UN81 downloaded
Disorder data for accession Q9UN81 downloaded
Redox data for accession Q9UNE7 downloaded
Disorder data for accession Q9UNE7 downloaded
Redox data for accession Q9UNF0 downloaded
Disorder data for accession Q9UNF0 downloaded
Redox data for accession Q9UNH7 downloaded
Disorder data for accession Q9UNH7 downloaded
Redox data for accession Q9UNM6 downloaded
Disorder data for accession Q9UNM6 downloaded
Redox data for accession Q9UNN8 downloaded
Disorder data for accession Q9UNN8 downloaded
Redox data for accession Q9UNS2 downloaded
Disorder data for accession Q9UNS2 downloaded
Redox data for accession Q9UPM8 downloaded
Disorder data for accession Q9UPM8 downloaded
Redox data for accession Q9UPN3 downloaded
Disorder data for accession Q9UPN3 downloaded
Redox data for accession Q9UQ80 downloaded
Disorder data for accession Q9UQ80 downloaded
Redox data for accession Q9UQB8 downloaded
Disorder data for accession Q9UQB8 downloaded
Redox data for accession Q9UQE7 downloaded
Disorder data for accession Q9UQE7 downloaded
Redox data for accession Q9Y232 downloaded
Disorder data for accession Q9Y232 downloaded
Redox data for accession Q9Y263 downloaded
Disorder data for accession Q9Y263 downloaded

Redox data for accession Q9Y265 downloaded
Disorder data for accession Q9Y265 downloaded
Redox data for accession Q9Y295 downloaded
Disorder data for accession Q9Y295 downloaded
Redox data for accession Q9Y2L1 downloaded
Disorder data for accession Q9Y2L1 downloaded
Redox data for accession Q9Y2Q5 downloaded
Disorder data for accession Q9Y2Q5 downloaded
Redox data for accession Q9Y2X7 downloaded
Disorder data for accession Q9Y2X7 downloaded
Redox data for accession Q9Y2Z0 downloaded
Disorder data for accession Q9Y2Z0 downloaded
Redox data for accession Q9Y2Z4 downloaded
Disorder data for accession Q9Y2Z4 downloaded
Redox data for accession Q9Y376 downloaded
Disorder data for accession Q9Y376 downloaded
Redox data for accession Q9Y383 downloaded
Disorder data for accession Q9Y383 downloaded
Redox data for accession Q9Y3A5 downloaded
Disorder data for accession Q9Y3A5 downloaded
Redox data for accession Q9Y3B3 downloaded
Disorder data for accession Q9Y3B3 downloaded
Redox data for accession Q9Y3B8 downloaded
Disorder data for accession Q9Y3B8 downloaded
Redox data for accession Q9Y3C6 downloaded
Disorder data for accession Q9Y3C6 downloaded
Redox data for accession Q9Y3C7 downloaded
Disorder data for accession Q9Y3C7 downloaded
Redox data for accession Q9Y3D0 downloaded
Disorder data for accession Q9Y3D0 downloaded
Redox data for accession Q9Y3E5 downloaded
Disorder data for accession Q9Y3E5 downloaded
Redox data for accession Q9Y3L3 downloaded
Disorder data for accession Q9Y3L3 downloaded
Redox data for accession Q9Y3U8 downloaded
Disorder data for accession Q9Y3U8 downloaded
Redox data for accession Q9Y450 downloaded
Disorder data for accession Q9Y450 downloaded
Redox data for accession Q9Y490 downloaded
Disorder data for accession Q9Y490 downloaded
Redox data for accession Q9Y4L1 downloaded
Disorder data for accession Q9Y4L1 downloaded
Redox data for accession Q9Y4P3 downloaded
Disorder data for accession Q9Y4P3 downloaded
Redox data for accession Q9Y4R8 downloaded
Disorder data for accession Q9Y4R8 downloaded
Redox data for accession Q9Y4W2 downloaded
Disorder data for accession Q9Y4W2 downloaded
Redox data for accession Q9Y4X5 downloaded
Disorder data for accession Q9Y4X5 downloaded
Redox data for accession Q9Y508 downloaded
Disorder data for accession Q9Y508 downloaded
Redox data for accession Q9Y5B8 downloaded
Disorder data for accession Q9Y5B8 downloaded
Redox data for accession Q9Y5B9 downloaded
Disorder data for accession Q9Y5B9 downloaded
Redox data for accession Q9Y5L0 downloaded
Disorder data for accession Q9Y5L0 downloaded
Redox data for accession Q9Y5M8 downloaded
Disorder data for accession Q9Y5M8 downloaded
Redox data for accession Q9Y5N6 downloaded
Disorder data for accession Q9Y5N6 downloaded
Redox data for accession Q9Y5P4 downloaded
Disorder data for accession Q9Y5P4 downloaded
Redox data for accession Q9Y5Q9 downloaded
Disorder data for accession Q9Y5Q9 downloaded
Redox data for accession Q9Y618 downloaded
Disorder data for accession Q9Y618 downloaded
Redox data for accession Q9Y678 downloaded
Disorder data for accession Q9Y678 downloaded
Redox data for accession Q9Y696 downloaded
Disorder data for accession Q9Y696 downloaded
Redox data for accession Q9Y6B7 downloaded
Disorder data for accession Q9Y6B7 downloaded
Redox data for accession Q9Y6E0 downloaded
Disorder data for accession Q9Y6E0 downloaded
Redox data for accession Q9Y6G3 downloaded
Disorder data for accession Q9Y6G3 downloaded
Redox data for accession Q9Y6M1 downloaded
Disorder data for accession Q9Y6M1 downloaded
Redox data for accession Q9Y6M5 downloaded
Disorder data for accession Q9Y6M5 downloaded
Redox data for accession Q9Y6Y8 downloaded
Disorder data for accession Q9Y6Y8 downloaded
   accession                                              redox  \
0     Q9UKG1                                       [[303, 390]]
1     Q9UKP4  [[107, 178], [347, 379], [391, 416], [492, 596...
2     Q9UKX5                                                 []
3     Q9UL54                                                 []
4     Q9ULC4                                                 []
..       ...                                                ...
61    Q9Y6E0                                                 []
62    Q9Y6G3                                         [[11, 72]]
63    Q9Y6M1                                                 []
64    Q9Y6M5                                       [[414, 462]]
65    Q9Y6Y8                                                 []

                                             disorder
0   [0.8445485234260559, 0.8410840630531311, 0.871...
1   [0.9778885841369629, 0.9777780175209045, 0.978...
2   [0.9202557802200317, 0.9368434548377991, 0.940...
3   [0.9494222402572632, 0.9483581185340881, 0.947...
4   [0.6901811361312866, 0.65202397108078, 0.56066...
..                                                ...
61  [0.5842058658599854, 0.6147359609603882, 0.698...
62  [0.757029116153717, 0.841290295124054, 0.82651...
63  [0.2482396364212036, 0.22154109179973602, 0.20...
64  [0.620266318321228, 0.5917750597000122, 0.5621...
65  [0.9723373651504517, 0.9753174781799316, 0.976...

[66 rows x 3 columns]
AIUPred pickle chunk 12 saved

Combine pickle chunks into a single file.

In [10]:
# Retrieve output chunks, merge them, and save as a unique file
AIUPred_proteins = pd.DataFrame()

for i in range(len(accessions)):
    with open(f"res/AIUPred_proteins_chunk_{i+1}.pkl", "rb") as f:
        AIUPred_proteins_chunk = pickle.load(f)
    AIUPred_proteins = pd.concat([AIUPred_proteins, AIUPred_proteins_chunk], ignore_index=True)

with open("res/AIUPred_proteins.pkl", "wb") as f:
    pickle.dump(AIUPred_proteins, f)

AIUPred_proteins

,accession,redox,disorder
0,A0AVT1,"[[582, 624]]","[0.9659407138824463, 0.9646615386009216, 0.968..."
1,A6NDU8,"[[223, 250]]","[0.3372959494590759, 0.32355791330337524, 0.34..."
2,A6NHR9,"[[1868, 1900]]","[0.9728986024856567, 0.9776636362075806, 0.978..."
3,A6NKF1,[],"[0.9777251482009888, 0.9779385328292847, 0.978..."
4,B2RTY4,"[[723, 741], [755, 787], [1170, 1224], [2030, ...","[0.672510027885437, 0.7656236290931702, 0.5662..."
...,...,...,...
1161,Q9Y6E0,[],"[0.5842058658599854, 0.6147359609603882, 0.698..."
1162,Q9Y6G3,"[[11, 72]]","[0.757029116153717, 0.841290295124054, 0.82651..."
1163,Q9Y6M1,[],"[0.2482396364212036, 0.22154109179973602, 0.20..."
1164,Q9Y6M5,"[[414, 462]]","[0.620266318321228, 0.5917750597000122, 0.5621..."
1165,Q9Y6Y8,[],"[0.9723373651504517, 0.9753174781799316, 0.976..."

###  2.6 - Download UniProt data from EBI, save pickle chunk files
Takes about 10 minutes for 1000 new proteins.<br>

In [11]:
def EBI_download(accession):
    ### Access EBI's API and download data from there
    url = "https://www.ebi.ac.uk/proteins/api/proteins/"
    requestURL = url+accession 
    try:    # try to download page
        EBI_res = session.get(requestURL, headers={"Accept": "application/json"})
        EBI_res.raise_for_status()
    except:
        print(f"Impossible to download EBI data for accession {accession}")
    if EBI_res.status_code == requests.codes.ok:    # if download worked
        return json.loads(EBI_res.text)

In [12]:
with requests.Session() as session:
    for i in range(len(accessions)):  # Loop over chunks
        EBI_data = []

        # Either copy data from old pickle or download data from EBI's API
        for accession in accessions[i]:  # Loop over accessions in the chunk
            if accession in EBI_proteins_old["accession"].values:   # if accession is already in the old pickle
                EBI_old = EBI_proteins_old.loc[EBI_proteins_old["accession"] == accession, "EBI_data"].iloc[0]
                EBI_data.append(EBI_old)
                print(f"EBI data for accession {accession} copied from old pickle")
            else:   # if new data need to be downloaded
                EBI_new = EBI_download(accession)
                EBI_data.append(EBI_new)
                print(f"EBI data for accession {accession} downloaded")

        # Assemble all data for a chunk of accessions in a DataFrame
        EBI_chunk = pd.DataFrame({"accession": accessions[i], "EBI_data": EBI_data})
        print(EBI_chunk)

        # Save chunk as pickle
        with open(f"res/EBI_proteins_chunk_{i+1}.pkl", "wb") as f:
            pickle.dump(EBI_chunk, f)
        print(f"EBI pickle chunk {i+1} saved\n")

EBI data for accession A0AVT1 downloaded
EBI data for accession A6NDU8 downloaded
EBI data for accession A6NHR9 downloaded
EBI data for accession A6NKF1 downloaded
EBI data for accession B2RTY4 downloaded
EBI data for accession O00116 downloaded
EBI data for accession O00151 downloaded
EBI data for accession O00159 downloaded
EBI data for accession O00170 downloaded
EBI data for accession O00186 downloaded
EBI data for accession O00231 downloaded
EBI data for accession O00233 downloaded
EBI data for accession O00267 downloaded
EBI data for accession O00299 downloaded
EBI data for accession O00303 downloaded
EBI data for accession O00400 downloaded
EBI data for accession O00410 downloaded
EBI data for accession O00425 downloaded
EBI data for accession O00429 downloaded
EBI data for accession O00462 downloaded
EBI data for accession O00469 downloaded
EBI data for accession O00471 downloaded
EBI data for accession O00541 downloaded
EBI data for accession O00567 downloaded
EBI data for accession O00571 downloaded
EBI data for accession O00629 downloaded
EBI data for accession O00743 downloaded
EBI data for accession O14524 downloaded
EBI data for accession O14530 downloaded
EBI data for accession O14617 downloaded
EBI data for accession O14682 downloaded
EBI data for accession O14744 downloaded
EBI data for accession O14787 downloaded
EBI data for accession O14818 downloaded
EBI data for accession O14867 downloaded
EBI data for accession O14879 downloaded
EBI data for accession O14929 downloaded
EBI data for accession O14950 downloaded
EBI data for accession O14964 downloaded
EBI data for accession O14967 downloaded
EBI data for accession O14974 downloaded
EBI data for accession O14979 downloaded
EBI data for accession O14981 downloaded
EBI data for accession O15056 downloaded
EBI data for accession O15067 downloaded
EBI data for accession O15078 downloaded
EBI data for accession O15131 downloaded
EBI data for accession O15144 downloaded
EBI data for accession O15228 downloaded
EBI data for accession O15269 downloaded
EBI data for accession O15357 downloaded
EBI data for accession O15371 downloaded
EBI data for accession O15400 downloaded
EBI data for accession O15498 downloaded
EBI data for accession O43143 downloaded
EBI data for accession O43242 downloaded
EBI data for accession O43299 downloaded
EBI data for accession O43447 downloaded
EBI data for accession O43592 downloaded
EBI data for accession O43660 downloaded
EBI data for accession O43663 downloaded
EBI data for accession O43707 downloaded
EBI data for accession O43747 downloaded
EBI data for accession O43765 downloaded
EBI data for accession O43795 downloaded
EBI data for accession O43837 downloaded
EBI data for accession O60216 downloaded
EBI data for accession O60231 downloaded
EBI data for accession O60244 downloaded
EBI data for accession O60292 downloaded
EBI data for accession O60306 downloaded
EBI data for accession O60343 downloaded
EBI data for accession O60508 downloaded
EBI data for accession O60610 downloaded
EBI data for accession O60664 downloaded
EBI data for accession O60701 downloaded
EBI data for accession O60716 downloaded
EBI data for accession O60826 downloaded
EBI data for accession O60832 downloaded
EBI data for accession O60884 downloaded
EBI data for accession O60890 downloaded
EBI data for accession O60936 downloaded
EBI data for accession O75083 downloaded
EBI data for accession O75116 downloaded
EBI data for accession O75122 downloaded
EBI data for accession O75131 downloaded
EBI data for accession O75147 downloaded
EBI data for accession O75165 downloaded
EBI data for accession O75179 downloaded
EBI data for accession O75326 downloaded
EBI data for accession O75347 downloaded
EBI data for accession O75351 downloaded
EBI data for accession O75367 downloaded
EBI data for accession O75369 downloaded
EBI data for accession O75390 downloaded
EBI data for accession O75439 downloaded
EBI data for accession O75503 downloaded
EBI data for accession O75521 downloaded
EBI data for accession O75530 downloaded
EBI data for accession O75531 downloaded
   accession                                           EBI_data
0     A0AVT1  {'accession': 'A0AVT1', 'id': 'UBA6_HUMAN', 'p...
1     A6NDU8  {'accession': 'A6NDU8', 'id': 'RIMC1_HUMAN', '...
2     A6NHR9  {'accession': 'A6NHR9', 'id': 'SMHD1_HUMAN', '...
3     A6NKF1  {'accession': 'A6NKF1', 'id': 'SAC31_HUMAN', '...
4     B2RTY4  {'accession': 'B2RTY4', 'id': 'MYO9A_HUMAN', '...
..       ...                                                ...
95    O75439  {'accession': 'O75439', 'id': 'MPPB_HUMAN', 'p...
96    O75503  {'accession': 'O75503', 'id': 'CLN5_HUMAN', 'p...
97    O75521  {'accession': 'O75521', 'id': 'ECI2_HUMAN', 'p...
98    O75530  {'accession': 'O75530', 'id': 'EED_HUMAN', 'pr...
99    O75531  {'accession': 'O75531', 'id': 'BAF_HUMAN', 'pr...

[100 rows x 2 columns]
EBI pickle chunk 1 saved

EBI data for accession O75533 downloaded
EBI data for accession O75534 downloaded
EBI data for accession O75607 downloaded
EBI data for accession O75643 downloaded
EBI data for accession O75663 downloaded
EBI data for accession O75694 downloaded
EBI data for accession O75821 downloaded
EBI data for accession O75822 downloaded
EBI data for accession O75828 downloaded
EBI data for accession O75832 downloaded
EBI data for accession O75874 downloaded
EBI data for accession O75923 downloaded
EBI data for accession O75947 downloaded
EBI data for accession O75953 downloaded
EBI data for accession O76021 downloaded
EBI data for accession O76094 downloaded
EBI data for accession O94760 downloaded
EBI data for accession O94763 downloaded
EBI data for accession O94776 downloaded
EBI data for accession O94804 downloaded
EBI data for accession O94808 downloaded
EBI data for accession O94826 downloaded
EBI data for accession O94855 downloaded
EBI data for accession O94874 downloaded
EBI data for accession O94876 downloaded
EBI data for accession O94901 downloaded
EBI data for accession O94905 downloaded
EBI data for accession O94906 downloaded
EBI data for accession O94919 downloaded
EBI data for accession O94979 downloaded
EBI data for accession O95059 downloaded
EBI data for accession O95155 downloaded
EBI data for accession O95163 downloaded
EBI data for accession O95202 downloaded
EBI data for accession O95210 downloaded
EBI data for accession O95260 downloaded
EBI data for accession O95292 downloaded
EBI data for accession O95336 downloaded
EBI data for accession O95373 downloaded
EBI data for accession O95394 downloaded
EBI data for accession O95478 downloaded
EBI data for accession O95571 downloaded
EBI data for accession O95573 downloaded
EBI data for accession O95757 downloaded
EBI data for accession O95758 downloaded
EBI data for accession O95782 downloaded
EBI data for accession O95831 downloaded
EBI data for accession O95861 downloaded
EBI data for accession O95881 downloaded
EBI data for accession O95905 downloaded
EBI data for accession O96019 downloaded
EBI data for accession P00338 downloaded
EBI data for accession P00367 downloaded
EBI data for accession P00387 downloaded
EBI data for accession P00491 downloaded
EBI data for accession P00492 downloaded
EBI data for accession P00505 downloaded
EBI data for accession P00558 downloaded
EBI data for accession P00749 downloaded
EBI data for accession P01889 downloaded
EBI data for accession P02545 downloaded
EBI data for accession P02751 downloaded
EBI data for accession P02795 downloaded
EBI data for accession P04040 downloaded
EBI data for accession P04049 downloaded
EBI data for accession P04075 downloaded
EBI data for accession P04083 downloaded
EBI data for accession P04181 downloaded
EBI data for accession P04216 downloaded
EBI data for accession P04406 downloaded
EBI data for accession P04632 downloaded
EBI data for accession P04843 downloaded
EBI data for accession P04844 downloaded
EBI data for accession P04899 downloaded
EBI data for accession P05062 downloaded
EBI data for accession P05120 downloaded
EBI data for accession P05141 downloaded
EBI data for accession P05198 downloaded
EBI data for accession P05388 downloaded
EBI data for accession P05455 downloaded

EBI data for accession P05556 downloaded
EBI data for accession P06132 downloaded
EBI data for accession P06400 downloaded
EBI data for accession P06733 downloaded
EBI data for accession P06746 downloaded
EBI data for accession P07237 downloaded
EBI data for accession P07355 downloaded
EBI data for accession P07384 downloaded
EBI data for accession P07437 downloaded
EBI data for accession P07602 downloaded
EBI data for accession P07737 downloaded
EBI data for accession P07814 downloaded
EBI data for accession P07858 downloaded
EBI data for accession P07900 downloaded
EBI data for accession P07954 downloaded
EBI data for accession P07992 downloaded
EBI data for accession P08133 downloaded
EBI data for accession P08174 downloaded
EBI data for accession P08237 downloaded
EBI data for accession P08240 downloaded
   accession                                           EBI_data
0     O75533  {'accession': 'O75533', 'id': 'SF3B1_HUMAN', '...
1     O75534  {'accession': 'O75534', 'id': 'CSDE1_HUMAN', '...
2     O75607  {'accession': 'O75607', 'id': 'NPM3_HUMAN', 'p...
3     O75643  {'accession': 'O75643', 'id': 'U520_HUMAN', 'p...
4     O75663  {'accession': 'O75663', 'id': 'TIPRL_HUMAN', '...
..       ...                                                ...
95    P07992  {'accession': 'P07992', 'id': 'ERCC1_HUMAN', '...
96    P08133  {'accession': 'P08133', 'id': 'ANXA6_HUMAN', '...
97    P08174  {'accession': 'P08174', 'id': 'DAF_HUMAN', 'pr...
98    P08237  {'accession': 'P08237', 'id': 'PFKAM_HUMAN', '...
99    P08240  {'accession': 'P08240', 'id': 'SRPRA_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 2 saved

EBI data for accession P08559 downloaded
EBI data for accession P08572 downloaded
EBI data for accession P08670 downloaded
EBI data for accession P08754 downloaded
EBI data for accession P08758 downloaded
EBI data for accession P09038 downloaded
EBI data for accession P09104 downloaded
EBI data for accession P09132 downloaded
EBI data for accession P09211 downloaded
EBI data for accession P09234 downloaded
EBI data for accession P09382 downloaded
EBI data for accession P09496 downloaded
EBI data for accession P09497 downloaded
EBI data for accession P09543 downloaded
EBI data for accession P09651 downloaded
EBI data for accession P09936 downloaded
EBI data for accession P09972 downloaded
EBI data for accession P0CG39 downloaded
EBI data for accession P10155 downloaded
EBI data for accession P10301 downloaded
EBI data for accession P10589 downloaded
EBI data for accession P10619 downloaded
EBI data for accession P10644 downloaded
EBI data for accession P10768 downloaded
EBI data for accession P10809 downloaded
EBI data for accession P11142 downloaded
EBI data for accession P11216 downloaded
EBI data for accession P11274 downloaded
EBI data for accession P11413 downloaded
EBI data for accession P11586 downloaded
EBI data for accession P11766 downloaded
EBI data for accession P11802 downloaded
EBI data for accession P11908 downloaded
EBI data for accession P12004 downloaded
EBI data for accession P12081 downloaded
EBI data for accession P12270 downloaded
EBI data for accession P12814 downloaded
EBI data for accession P12955 downloaded
EBI data for accession P13489 downloaded
EBI data for accession P13611 downloaded
EBI data for accession P13639 downloaded
EBI data for accession P13693 downloaded
EBI data for accession P13716 downloaded
EBI data for accession P13726 downloaded
EBI data for accession P13797 downloaded
EBI data for accession P13798 downloaded
EBI data for accession P13987 downloaded
EBI data for accession P14174 downloaded
EBI data for accession P14314 downloaded
EBI data for accession P14618 downloaded
EBI data for accession P14649 downloaded
EBI data for accession P15121 downloaded
EBI data for accession P15170 downloaded
EBI data for accession P15531 downloaded
EBI data for accession P15924 downloaded
EBI data for accession P16070 downloaded
EBI data for accession P16615 downloaded
EBI data for accession P16930 downloaded
EBI data for accession P17050 downloaded
EBI data for accession P17066 downloaded
EBI data for accession P17301 downloaded
EBI data for accession P17655 downloaded
EBI data for accession P17812 downloaded
EBI data for accession P17844 downloaded
EBI data for accession P18031 downloaded
EBI data for accession P18077 downloaded
EBI data for accession P18085 downloaded
EBI data for accession P18206 downloaded
EBI data for accession P18583 downloaded
EBI data for accession P18669 downloaded
EBI data for accession P19338 downloaded
EBI data for accession P19367 downloaded
EBI data for accession P20020 downloaded
EBI data for accession P20042 downloaded
EBI data for accession P20073 downloaded
EBI data for accession P20337 downloaded
EBI data for accession P20585 downloaded
EBI data for accession P20645 downloaded
EBI data for accession P20936 downloaded
EBI data for accession P21281 downloaded
EBI data for accession P21291 downloaded
EBI data for accession P21333 downloaded
EBI data for accession P21399 downloaded
EBI data for accession P21589 downloaded
EBI data for accession P21796 downloaded
EBI data for accession P21964 downloaded
EBI data for accession P21980 downloaded
EBI data for accession P22033 downloaded
EBI data for accession P22061 downloaded
EBI data for accession P22102 downloaded
EBI data for accession P22234 downloaded
EBI data for accession P22314 downloaded
EBI data for accession P22626 downloaded
EBI data for accession P22695 downloaded
EBI data for accession P22830 downloaded
EBI data for accession P23193 downloaded
EBI data for accession P23229 downloaded
EBI data for accession P23258 downloaded
EBI data for accession P23284 downloaded
EBI data for accession P23381 downloaded
   accession                                           EBI_data
0     P08559  {'accession': 'P08559', 'id': 'ODPA_HUMAN', 'p...
1     P08572  {'accession': 'P08572', 'id': 'CO4A2_HUMAN', '...
2     P08670  {'accession': 'P08670', 'id': 'VIME_HUMAN', 'p...
3     P08754  {'accession': 'P08754', 'id': 'GNAI3_HUMAN', '...
4     P08758  {'accession': 'P08758', 'id': 'ANXA5_HUMAN', '...
..       ...                                                ...
95    P23193  {'accession': 'P23193', 'id': 'TCEA1_HUMAN', '...
96    P23229  {'accession': 'P23229', 'id': 'ITA6_HUMAN', 'p...
97    P23258  {'accession': 'P23258', 'id': 'TBG1_HUMAN', 'p...
98    P23284  {'accession': 'P23284', 'id': 'PPIB_HUMAN', 'p...
99    P23381  {'accession': 'P23381', 'id': 'SYWC_HUMAN', 'p...

[100 rows x 2 columns]
EBI pickle chunk 3 saved

EBI data for accession P23396 downloaded
EBI data for accession P23434 downloaded
EBI data for accession P23458 downloaded
EBI data for accession P23467 downloaded
EBI data for accession P23526 downloaded
EBI data for accession P23528 downloaded
EBI data for accession P23634 downloaded
EBI data for accession P23743 downloaded
EBI data for accession P23921 downloaded
EBI data for accession P24666 downloaded
EBI data for accession P24752 downloaded
EBI data for accession P24844 downloaded
EBI data for accession P25205 downloaded
EBI data for accession P25398 downloaded
EBI data for accession P25685 downloaded
EBI data for accession P25786 downloaded
EBI data for accession P25789 downloaded
EBI data for accession P26006 downloaded
EBI data for accession P26232 downloaded
EBI data for accession P26440 downloaded
EBI data for accession P26599 downloaded
EBI data for accession P26639 downloaded
EBI data for accession P26640 downloaded
EBI data for accession P27348 downloaded
EBI data for accession P27635 downloaded
EBI data for accession P27707 downloaded
EBI data for accession P27797 downloaded
EBI data for accession P28070 downloaded
EBI data for accession P28072 downloaded
EBI data for accession P28161 downloaded
EBI data for accession P28300 downloaded
EBI data for accession P28340 downloaded
EBI data for accession P28838 downloaded
EBI data for accession P29144 downloaded
EBI data for accession P29317 downloaded
EBI data for accession P29353 downloaded
EBI data for accession P29401 downloaded
EBI data for accession P29692 downloaded
EBI data for accession P29992 downloaded
EBI data for accession P30041 downloaded

EBI data for accession P30050 downloaded
EBI data for accession P30084 downloaded
EBI data for accession P30086 downloaded
EBI data for accession P30101 downloaded
EBI data for accession P30153 downloaded
EBI data for accession P30260 downloaded
EBI data for accession P30281 downloaded
EBI data for accession P30519 downloaded
EBI data for accession P30530 downloaded
EBI data for accession P30626 downloaded
EBI data for accession P31040 downloaded
EBI data for accession P31153 downloaded
EBI data for accession P31323 downloaded
EBI data for accession P31327 downloaded
EBI data for accession P31751 downloaded
EBI data for accession P31930 downloaded
EBI data for accession P31939 downloaded
EBI data for accession P31943 downloaded
EBI data for accession P31948 downloaded
EBI data for accession P32969 downloaded
EBI data for accession P33121 downloaded
EBI data for accession P33316 downloaded
EBI data for accession P33527 downloaded
EBI data for accession P33993 downloaded
EBI data for accession P34896 downloaded
EBI data for accession P34897 downloaded
EBI data for accession P34932 downloaded
EBI data for accession P35237 downloaded
EBI data for accession P35555 downloaded
EBI data for accession P35579 downloaded
EBI data for accession P35606 downloaded
EBI data for accession P35613 downloaded
EBI data for accession P35637 downloaded
EBI data for accession P35659 downloaded
EBI data for accession P35754 downloaded
EBI data for accession P35914 downloaded
EBI data for accession P36776 downloaded
EBI data for accession P36915 downloaded
EBI data for accession P36957 downloaded
EBI data for accession P36959 downloaded
EBI data for accession P37268 downloaded
EBI data for accession P37837 downloaded
EBI data for accession P38646 downloaded
EBI data for accession P38936 downloaded
EBI data for accession P39023 downloaded
EBI data for accession P39656 downloaded
EBI data for accession P40123 downloaded
EBI data for accession P40227 downloaded
EBI data for accession P40429 downloaded
EBI data for accession P40692 downloaded
EBI data for accession P40925 downloaded
EBI data for accession P40926 downloaded
EBI data for accession P40939 downloaded
EBI data for accession P41223 downloaded
EBI data for accession P41229 downloaded
EBI data for accession P41250 downloaded
EBI data for accession P41252 downloaded
EBI data for accession P42166 downloaded
EBI data for accession P42285 downloaded
EBI data for accession P42336 downloaded
   accession                                           EBI_data
0     P23396  {'accession': 'P23396', 'id': 'RS3_HUMAN', 'pr...
1     P23434  {'accession': 'P23434', 'id': 'GCSH_HUMAN', 'p...
2     P23458  {'accession': 'P23458', 'id': 'JAK1_HUMAN', 'p...
3     P23467  {'accession': 'P23467', 'id': 'PTPRB_HUMAN', '...
4     P23526  {'accession': 'P23526', 'id': 'SAHH_HUMAN', 'p...
..       ...                                                ...
95    P41250  {'accession': 'P41250', 'id': 'GARS_HUMAN', 'p...
96    P41252  {'accession': 'P41252', 'id': 'SYIC_HUMAN', 'p...
97    P42166  {'accession': 'P42166', 'id': 'LAP2A_HUMAN', '...
98    P42285  {'accession': 'P42285', 'id': 'MTREX_HUMAN', '...
99    P42336  {'accession': 'P42336', 'id': 'PK3CA_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 4 saved

EBI data for accession P42345 downloaded
EBI data for accession P42677 downloaded
EBI data for accession P42704 downloaded
EBI data for accession P42858 downloaded
EBI data for accession P43034 downloaded
EBI data for accession P43243 downloaded
EBI data for accession P43304 downloaded
EBI data for accession P43490 downloaded
EBI data for accession P43897 downloaded
EBI data for accession P45880 downloaded
EBI data for accession P45973 downloaded
EBI data for accession P46013 downloaded
EBI data for accession P46020 downloaded
EBI data for accession P46060 downloaded
EBI data for accession P46063 downloaded
EBI data for accession P46776 downloaded
EBI data for accession P46777 downloaded
EBI data for accession P46779 downloaded
EBI data for accession P46782 downloaded
EBI data for accession P46821 downloaded
EBI data for accession P46939 downloaded
EBI data for accession P46940 downloaded
EBI data for accession P47756 downloaded
EBI data for accession P47897 downloaded
EBI data for accession P48059 downloaded
EBI data for accession P48444 downloaded
EBI data for accession P48449 downloaded
EBI data for accession P48509 downloaded
EBI data for accession P48556 downloaded
EBI data for accession P48643 downloaded
EBI data for accession P48735 downloaded
EBI data for accession P48739 downloaded
EBI data for accession P49023 downloaded
EBI data for accession P49189 downloaded
EBI data for accession P49327 downloaded
EBI data for accession P49368 downloaded
EBI data for accession P49454 downloaded
EBI data for accession P49458 downloaded
EBI data for accession P49588 downloaded
EBI data for accession P49643 downloaded
EBI data for accession P49720 downloaded
EBI data for accession P49721 downloaded
EBI data for accession P49736 downloaded
EBI data for accession P49748 downloaded
EBI data for accession P49773 downloaded
EBI data for accession P49792 downloaded
EBI data for accession P49821 downloaded
EBI data for accession P49841 downloaded
EBI data for accession P49915 downloaded
EBI data for accession P50053 downloaded
EBI data for accession P50148 downloaded
EBI data for accession P50213 downloaded
EBI data for accession P50395 downloaded
EBI data for accession P50416 downloaded
EBI data for accession P50440 downloaded
EBI data for accession P50552 downloaded
EBI data for accession P50750 downloaded
EBI data for accession P50851 downloaded
EBI data for accession P50914 downloaded
EBI data for accession P50990 downloaded
EBI data for accession P50991 downloaded
EBI data for accession P50995 downloaded
EBI data for accession P51114 downloaded
EBI data for accession P51398 downloaded
EBI data for accession P51610 downloaded
EBI data for accession P51858 downloaded
EBI data for accession P51991 downloaded
EBI data for accession P52209 downloaded
EBI data for accession P52294 downloaded
EBI data for accession P52306 downloaded
EBI data for accession P52594 downloaded
EBI data for accession P52597 downloaded
EBI data for accession P52701 downloaded
EBI data for accession P52758 downloaded
EBI data for accession P52788 downloaded
EBI data for accession P52789 downloaded
EBI data for accession P52907 downloaded
EBI data for accession P53041 downloaded
EBI data for accession P53384 downloaded
EBI data for accession P53396 downloaded
EBI data for accession P53618 downloaded
EBI data for accession P53621 downloaded
EBI data for accession P53634 downloaded
EBI data for accession P53990 downloaded
EBI data for accession P53992 downloaded
EBI data for accession P54136 downloaded
EBI data for accession P54278 downloaded
EBI data for accession P54577 downloaded
EBI data for accession P54687 downloaded
EBI data for accession P54709 downloaded
EBI data for accession P54886 downloaded
EBI data for accession P54920 downloaded
EBI data for accession P55036 downloaded
EBI data for accession P55060 downloaded
EBI data for accession P55072 downloaded
EBI data for accession P55145 downloaded
EBI data for accession P55209 downloaded
EBI data for accession P55735 downloaded
EBI data for accession P55795 downloaded
EBI data for accession P55884 downloaded
   accession                                           EBI_data
0     P42345  {'accession': 'P42345', 'id': 'MTOR_HUMAN', 'p...
1     P42677  {'accession': 'P42677', 'id': 'RS27_HUMAN', 'p...
2     P42704  {'accession': 'P42704', 'id': 'LPPRC_HUMAN', '...
3     P42858  {'accession': 'P42858', 'id': 'HD_HUMAN', 'pro...
4     P43034  {'accession': 'P43034', 'id': 'LIS1_HUMAN', 'p...
..       ...                                                ...
95    P55145  {'accession': 'P55145', 'id': 'MANF_HUMAN', 'p...
96    P55209  {'accession': 'P55209', 'id': 'NP1L1_HUMAN', '...
97    P55735  {'accession': 'P55735', 'id': 'SEC13_HUMAN', '...
98    P55795  {'accession': 'P55795', 'id': 'HNRH2_HUMAN', '...
99    P55884  {'accession': 'P55884', 'id': 'EIF3B_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 5 saved

EBI data for accession P56589 downloaded
EBI data for accession P57721 downloaded
EBI data for accession P60174 downloaded
EBI data for accession P60709 downloaded
EBI data for accession P60866 downloaded
EBI data for accession P60891 downloaded
EBI data for accession P60900 downloaded
EBI data for accession P60953 downloaded
EBI data for accession P60981 downloaded
EBI data for accession P61011 downloaded
EBI data for accession P61081 downloaded
EBI data for accession P61086 downloaded
EBI data for accession P61088 downloaded
EBI data for accession P61158 downloaded
EBI data for accession P61160 downloaded
EBI data for accession P61224 downloaded
EBI data for accession P61247 downloaded
EBI data for accession P61964 downloaded
EBI data for accession P61970 downloaded
EBI data for accession P61978 downloaded
EBI data for accession P62072 downloaded
EBI data for accession P62136 downloaded
EBI data for accession P62195 downloaded
EBI data for accession P62241 downloaded
EBI data for accession P62249 downloaded
EBI data for accession P62263 downloaded
EBI data for accession P62316 downloaded
EBI data for accession P62318 downloaded
EBI data for accession P62333 downloaded
EBI data for accession P62495 downloaded
EBI data for accession P62633 downloaded
EBI data for accession P62701 downloaded
EBI data for accession P62714 downloaded
EBI data for accession P62826 downloaded
EBI data for accession P62829 downloaded
EBI data for accession P62834 downloaded
EBI data for accession P62857 downloaded
EBI data for accession P62873 downloaded
EBI data for accession P62879 downloaded
EBI data for accession P62888 downloaded
EBI data for accession P62910 downloaded
EBI data for accession P62937 downloaded
EBI data for accession P63010 downloaded
EBI data for accession P63096 downloaded
EBI data for accession P63104 downloaded
EBI data for accession P63167 downloaded
EBI data for accession P63208 downloaded
EBI data for accession P63220 downloaded
EBI data for accession P63244 downloaded
EBI data for accession P67870 downloaded
EBI data for accession P67936 downloaded
EBI data for accession P68104 downloaded
EBI data for accession P78371 downloaded
EBI data for accession P78417 downloaded
EBI data for accession P78527 downloaded
EBI data for accession P78559 downloaded
EBI data for accession P83731 downloaded
EBI data for accession P84090 downloaded
EBI data for accession P84103 downloaded
EBI data for accession Q00534 downloaded
EBI data for accession Q00537 downloaded
EBI data for accession Q00610 downloaded
EBI data for accession Q00653 downloaded
EBI data for accession Q00839 downloaded
EBI data for accession Q01082 downloaded
EBI data for accession Q01469 downloaded
EBI data for accession Q01484 downloaded
EBI data for accession Q01518 downloaded
EBI data for accession Q01658 downloaded
EBI data for accession Q01780 downloaded
EBI data for accession Q01813 downloaded
EBI data for accession Q01844 downloaded
EBI data for accession Q01970 downloaded
EBI data for accession Q01995 downloaded
EBI data for accession Q02218 downloaded
EBI data for accession Q02241 downloaded
EBI data for accession Q02252 downloaded
EBI data for accession Q02543 downloaded
EBI data for accession Q02790 downloaded
EBI data for accession Q02809 downloaded
EBI data for accession Q03001 downloaded
EBI data for accession Q03426 downloaded
EBI data for accession Q03519 downloaded
EBI data for accession Q04446 downloaded
EBI data for accession Q04637 downloaded
EBI data for accession Q04760 downloaded
EBI data for accession Q04771 downloaded
EBI data for accession Q04917 downloaded
EBI data for accession Q06124 downloaded
EBI data for accession Q06136 downloaded
EBI data for accession Q06210 downloaded
EBI data for accession Q06278 downloaded
EBI data for accession Q06546 downloaded
EBI data for accession Q06609 downloaded
EBI data for accession Q07065 downloaded
EBI data for accession Q07866 downloaded
EBI data for accession Q07954 downloaded
EBI data for accession Q07955 downloaded
EBI data for accession Q08170 downloaded
EBI data for accession Q08211 downloaded
   accession                                           EBI_data
0     P56589  {'accession': 'P56589', 'id': 'PEX3_HUMAN', 'p...
1     P57721  {'accession': 'P57721', 'id': 'PCBP3_HUMAN', '...
2     P60174  {'accession': 'P60174', 'id': 'TPIS_HUMAN', 'p...
3     P60709  {'accession': 'P60709', 'id': 'ACTB_HUMAN', 'p...
4     P60866  {'accession': 'P60866', 'id': 'RS20_HUMAN', 'p...
..       ...                                                ...
95    Q07866  {'accession': 'Q07866', 'id': 'KLC1_HUMAN', 'p...
96    Q07954  {'accession': 'Q07954', 'id': 'LRP1_HUMAN', 'p...
97    Q07955  {'accession': 'Q07955', 'id': 'SRSF1_HUMAN', '...
98    Q08170  {'accession': 'Q08170', 'id': 'SRSF4_HUMAN', '...
99    Q08211  {'accession': 'Q08211', 'id': 'DHX9_HUMAN', 'p...

[100 rows x 2 columns]
EBI pickle chunk 6 saved

EBI data for accession Q08257 downloaded
EBI data for accession Q08AF3 downloaded
EBI data for accession Q08AM6 downloaded
EBI data for accession Q09666 downloaded
EBI data for accession Q0ZGT2 downloaded
EBI data for accession Q10567 downloaded
EBI data for accession Q12765 downloaded
EBI data for accession Q12769 downloaded
EBI data for accession Q12792 downloaded
EBI data for accession Q12800 downloaded
EBI data for accession Q12846 downloaded
EBI data for accession Q12874 downloaded
EBI data for accession Q12888 downloaded
EBI data for accession Q12904 downloaded
EBI data for accession Q12931 downloaded
EBI data for accession Q12974 downloaded
EBI data for accession Q12979 downloaded
EBI data for accession Q13011 downloaded
EBI data for accession Q13042 downloaded
EBI data for accession Q13045 downloaded
EBI data for accession Q13085 downloaded
EBI data for accession Q13098 downloaded
EBI data for accession Q13126 downloaded
EBI data for accession Q13148 downloaded
EBI data for accession Q13153 downloaded
EBI data for accession Q13155 downloaded
EBI data for accession Q13158 downloaded
EBI data for accession Q13162 downloaded
EBI data for accession Q13190 downloaded
EBI data for accession Q13200 downloaded
EBI data for accession Q13242 downloaded
EBI data for accession Q13310 downloaded
EBI data for accession Q13325 downloaded
EBI data for accession Q13418 downloaded
EBI data for accession Q13423 downloaded
EBI data for accession Q13426 downloaded
EBI data for accession Q13439 downloaded
EBI data for accession Q13443 downloaded
EBI data for accession Q13501 downloaded
EBI data for accession Q13505 downloaded
EBI data for accession Q13526 downloaded
EBI data for accession Q13555 downloaded
EBI data for accession Q13557 downloaded
EBI data for accession Q13596 downloaded
EBI data for accession Q13610 downloaded
EBI data for accession Q13616 downloaded
EBI data for accession Q13617 downloaded
EBI data for accession Q13620 downloaded
EBI data for accession Q13630 downloaded
EBI data for accession Q13637 downloaded
EBI data for accession Q13740 downloaded
EBI data for accession Q13795 downloaded
EBI data for accession Q13813 downloaded
EBI data for accession Q13838 downloaded
EBI data for accession Q13867 downloaded
EBI data for accession Q13868 downloaded
EBI data for accession Q13907 downloaded
EBI data for accession Q14008 downloaded
EBI data for accession Q14019 downloaded
EBI data for accession Q14108 downloaded
EBI data for accession Q14126 downloaded
EBI data for accession Q14152 downloaded
EBI data for accession Q14155 downloaded
EBI data for accession Q14192 downloaded
EBI data for accession Q14197 downloaded
EBI data for accession Q14203 downloaded
EBI data for accession Q14204 downloaded
EBI data for accession Q14315 downloaded
EBI data for accession Q14318 downloaded
EBI data for accession Q14376 downloaded
EBI data for accession Q14558 downloaded
EBI data for accession Q14566 downloaded
EBI data for accession Q14644 downloaded
EBI data for accession Q14683 downloaded
EBI data for accession Q14690 downloaded
EBI data for accession Q14692 downloaded
EBI data for accession Q14697 downloaded
EBI data for accession Q14764 downloaded
EBI data for accession Q14847 downloaded
EBI data for accession Q14974 downloaded

EBI data for accession Q14980 downloaded
EBI data for accession Q14C86 downloaded
EBI data for accession Q15008 downloaded
EBI data for accession Q15018 downloaded
EBI data for accession Q15019 downloaded
EBI data for accession Q15020 downloaded
EBI data for accession Q15024 downloaded
EBI data for accession Q15029 downloaded
EBI data for accession Q15041 downloaded
EBI data for accession Q15042 downloaded
EBI data for accession Q15047 downloaded
EBI data for accession Q15056 downloaded
EBI data for accession Q15075 downloaded
EBI data for accession Q15102 downloaded
EBI data for accession Q15147 downloaded
EBI data for accession Q15149 downloaded
EBI data for accession Q15154 downloaded
EBI data for accession Q15181 downloaded
EBI data for accession Q15185 downloaded
EBI data for accession Q15311 downloaded
   accession                                           EBI_data
0     Q08257  {'accession': 'Q08257', 'id': 'QOR_HUMAN', 'pr...
1     Q08AF3  {'accession': 'Q08AF3', 'id': 'SLFN5_HUMAN', '...
2     Q08AM6  {'accession': 'Q08AM6', 'id': 'VAC14_HUMAN', '...
3     Q09666  {'accession': 'Q09666', 'id': 'AHNK_HUMAN', 'p...
4     Q0ZGT2  {'accession': 'Q0ZGT2', 'id': 'NEXN_HUMAN', 'p...
..       ...                                                ...
95    Q15149  {'accession': 'Q15149', 'id': 'PLEC_HUMAN', 'p...
96    Q15154  {'accession': 'Q15154', 'id': 'PCM1_HUMAN', 'p...
97    Q15181  {'accession': 'Q15181', 'id': 'IPYR_HUMAN', 'p...
98    Q15185  {'accession': 'Q15185', 'id': 'TEBP_HUMAN', 'p...
99    Q15311  {'accession': 'Q15311', 'id': 'RBP1_HUMAN', 'p...

[100 rows x 2 columns]
EBI pickle chunk 7 saved

EBI data for accession Q15345 downloaded
EBI data for accession Q15361 downloaded
EBI data for accession Q15365 downloaded
EBI data for accession Q15366 downloaded
EBI data for accession Q15386 downloaded
EBI data for accession Q15392 downloaded
EBI data for accession Q15428 downloaded
EBI data for accession Q15435 downloaded
EBI data for accession Q15437 downloaded
EBI data for accession Q15459 downloaded
EBI data for accession Q15643 downloaded
EBI data for accession Q15678 downloaded
EBI data for accession Q15738 downloaded
EBI data for accession Q15746 downloaded
EBI data for accession Q15811 downloaded
EBI data for accession Q15814 downloaded
EBI data for accession Q15942 downloaded
EBI data for accession Q16181 downloaded
EBI data for accession Q16270 downloaded
EBI data for accession Q16531 downloaded
EBI data for accession Q16543 downloaded
EBI data for accession Q16555 downloaded
EBI data for accession Q16576 downloaded
EBI data for accession Q16630 downloaded
EBI data for accession Q16643 downloaded
EBI data for accession Q16658 downloaded
EBI data for accession Q16762 downloaded
EBI data for accession Q16775 downloaded
EBI data for accession Q16891 downloaded
EBI data for accession Q1KMD3 downloaded
EBI data for accession Q27J81 downloaded
EBI data for accession Q2M389 downloaded
EBI data for accession Q2TB10 downloaded
EBI data for accession Q32P28 downloaded
EBI data for accession Q3MHD2 downloaded
EBI data for accession Q4G148 downloaded
EBI data for accession Q4VC31 downloaded
EBI data for accession Q52LJ0 downloaded
EBI data for accession Q52LW3 downloaded
EBI data for accession Q53EP0 downloaded
EBI data for accession Q53FA7 downloaded
EBI data for accession Q53H12 downloaded
EBI data for accession Q58WW2 downloaded
EBI data for accession Q5BJF6 downloaded
EBI data for accession Q5JRA6 downloaded
EBI data for accession Q5JSH3 downloaded
EBI data for accession Q5JTH9 downloaded
EBI data for accession Q5JWF2 downloaded
EBI data for accession Q5K651 downloaded
EBI data for accession Q5M775 downloaded
EBI data for accession Q5MIZ7 downloaded
EBI data for accession Q5R3I4 downloaded
EBI data for accession Q5RKV6 downloaded
EBI data for accession Q5SRE5 downloaded
EBI data for accession Q5T0D9 downloaded
EBI data for accession Q5T4S7 downloaded
EBI data for accession Q5T653 downloaded
EBI data for accession Q5T8P6 downloaded
EBI data for accession Q5TFE4 downloaded
EBI data for accession Q5VU43 downloaded
EBI data for accession Q5VYK3 downloaded
EBI data for accession Q5W0V3 downloaded
EBI data for accession Q63ZY3 downloaded
EBI data for accession Q658Y4 downloaded
EBI data for accession Q66K74 downloaded
EBI data for accession Q676U5 downloaded
EBI data for accession Q68D91 downloaded
EBI data for accession Q68EM7 downloaded
EBI data for accession Q69YN2 downloaded
EBI data for accession Q6AI12 downloaded
EBI data for accession Q6DD88 downloaded
EBI data for accession Q6I9Y2 downloaded
EBI data for accession Q6NUK1 downloaded
EBI data for accession Q6NUQ4 downloaded
EBI data for accession Q6P158 downloaded
EBI data for accession Q6P1N0 downloaded
EBI data for accession Q6P2E9 downloaded
EBI data for accession Q6P2H3 downloaded
EBI data for accession Q6P587 downloaded
EBI data for accession Q6PCE3 downloaded
EBI data for accession Q6PD62 downloaded
EBI data for accession Q6PFW1 downloaded
EBI data for accession Q6PI48 downloaded
EBI data for accession Q6QNY1 downloaded
EBI data for accession Q6R327 downloaded
EBI data for accession Q6SZW1 downloaded
EBI data for accession Q6UXH8 downloaded
EBI data for accession Q6UXV4 downloaded
EBI data for accession Q6YN16 downloaded
EBI data for accession Q6ZRS2 downloaded
EBI data for accession Q6ZUT6 downloaded
EBI data for accession Q6ZW76 downloaded
EBI data for accession Q7KZF4 downloaded
EBI data for accession Q7L014 downloaded
EBI data for accession Q7L1Q6 downloaded
EBI data for accession Q7L273 downloaded
EBI data for accession Q7L2H7 downloaded
EBI data for accession Q7L5N7 downloaded
EBI data for accession Q7RTS9 downloaded
EBI data for accession Q7Z2W4 downloaded
   accession                                           EBI_data
0     Q15345  {'accession': 'Q15345', 'id': 'LRC41_HUMAN', '...
1     Q15361  {'accession': 'Q15361', 'id': 'TTF1_HUMAN', 'p...
2     Q15365  {'accession': 'Q15365', 'id': 'PCBP1_HUMAN', '...
3     Q15366  {'accession': 'Q15366', 'id': 'PCBP2_HUMAN', '...
4     Q15386  {'accession': 'Q15386', 'id': 'UBE3C_HUMAN', '...
..       ...                                                ...
95    Q7L273  {'accession': 'Q7L273', 'id': 'KCTD9_HUMAN', '...
96    Q7L2H7  {'accession': 'Q7L2H7', 'id': 'EIF3M_HUMAN', '...
97    Q7L5N7  {'accession': 'Q7L5N7', 'id': 'PCAT2_HUMAN', '...
98    Q7RTS9  {'accession': 'Q7RTS9', 'id': 'DYM_HUMAN', 'pr...
99    Q7Z2W4  {'accession': 'Q7Z2W4', 'id': 'ZCCHV_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 8 saved

EBI data for accession Q7Z2Z2 downloaded
EBI data for accession Q7Z4Q2 downloaded
EBI data for accession Q7Z4V5 downloaded
EBI data for accession Q7Z6Z7 downloaded
EBI data for accession Q86U42 downloaded
EBI data for accession Q86UP2 downloaded
EBI data for accession Q86VI3 downloaded
EBI data for accession Q86VP6 downloaded
EBI data for accession Q86VU5 downloaded
EBI data for accession Q86X55 downloaded
EBI data for accession Q86XZ4 downloaded
EBI data for accession Q86Y37 downloaded
EBI data for accession Q86Y82 downloaded
EBI data for accession Q86YH6 downloaded
EBI data for accession Q8IU81 downloaded
EBI data for accession Q8IUR7 downloaded
EBI data for accession Q8IWA0 downloaded
EBI data for accession Q8IWB7 downloaded
EBI data for accession Q8IWE2 downloaded
EBI data for accession Q8IWR0 downloaded
EBI data for accession Q8IX04 downloaded
EBI data for accession Q8IXK0 downloaded
EBI data for accession Q8IXY8 downloaded
EBI data for accession Q8IY81 downloaded
EBI data for accession Q8IYD1 downloaded
EBI data for accession Q8IYS1 downloaded
EBI data for accession Q8IYS2 downloaded
EBI data for accession Q8IZ83 downloaded
EBI data for accession Q8IZH2 downloaded
EBI data for accession Q8IZP0 downloaded
EBI data for accession Q8N0V3 downloaded
EBI data for accession Q8N163 downloaded
EBI data for accession Q8N1F7 downloaded
EBI data for accession Q8N392 downloaded
EBI data for accession Q8N3C0 downloaded
EBI data for accession Q8N3Y1 downloaded
EBI data for accession Q8N556 downloaded
EBI data for accession Q8N5A5 downloaded
EBI data for accession Q8N5L8 downloaded
EBI data for accession Q8N806 downloaded

EBI data for accession Q8NAP3 downloaded
EBI data for accession Q8NAV1 downloaded
EBI data for accession Q8NB16 downloaded
EBI data for accession Q8NB49 downloaded
EBI data for accession Q8NE71 downloaded
EBI data for accession Q8NEN9 downloaded
EBI data for accession Q8NEW0 downloaded
EBI data for accession Q8NF37 downloaded
EBI data for accession Q8NF91 downloaded
EBI data for accession Q8NFH4 downloaded
EBI data for accession Q8NG68 downloaded
EBI data for accession Q8TAE8 downloaded
EBI data for accession Q8TB52 downloaded
EBI data for accession Q8TBC4 downloaded
EBI data for accession Q8TCG1 downloaded
EBI data for accession Q8TCS8 downloaded
EBI data for accession Q8TDD1 downloaded
EBI data for accession Q8TDX7 downloaded
EBI data for accession Q8TEQ6 downloaded
EBI data for accession Q8TEX9 downloaded
EBI data for accession Q8TF42 downloaded
EBI data for accession Q8TF68 downloaded
EBI data for accession Q8WTW4 downloaded
EBI data for accession Q8WUM4 downloaded
EBI data for accession Q8WUP2 downloaded
EBI data for accession Q8WV93 downloaded
EBI data for accession Q8WVM7 downloaded
EBI data for accession Q8WVT3 downloaded
EBI data for accession Q8WWI1 downloaded
EBI data for accession Q8WX92 downloaded
EBI data for accession Q8WX93 downloaded
EBI data for accession Q92499 downloaded
EBI data for accession Q92538 downloaded
EBI data for accession Q92547 downloaded
EBI data for accession Q92598 downloaded
EBI data for accession Q92614 downloaded
EBI data for accession Q92616 downloaded
EBI data for accession Q92685 downloaded
EBI data for accession Q92688 downloaded
EBI data for accession Q92747 downloaded
EBI data for accession Q92791 downloaded
EBI data for accession Q92841 downloaded
EBI data for accession Q92870 downloaded
EBI data for accession Q92878 downloaded
EBI data for accession Q92888 downloaded
EBI data for accession Q92896 downloaded
EBI data for accession Q92900 downloaded
EBI data for accession Q92905 downloaded
EBI data for accession Q92945 downloaded
EBI data for accession Q92973 downloaded
EBI data for accession Q92974 downloaded
EBI data for accession Q93008 downloaded
EBI data for accession Q93009 downloaded
EBI data for accession Q93034 downloaded
EBI data for accession Q93073 downloaded
EBI data for accession Q969F9 downloaded
EBI data for accession Q969Q5 downloaded
EBI data for accession Q969R2 downloaded
EBI data for accession Q969V5 downloaded
EBI data for accession Q96A33 downloaded
   accession                                           EBI_data
0     Q7Z2Z2  {'accession': 'Q7Z2Z2', 'id': 'EFL1_HUMAN', 'p...
1     Q7Z4Q2  {'accession': 'Q7Z4Q2', 'id': 'HEAT3_HUMAN', '...
2     Q7Z4V5  {'accession': 'Q7Z4V5', 'id': 'HDGR2_HUMAN', '...
3     Q7Z6Z7  {'accession': 'Q7Z6Z7', 'id': 'HUWE1_HUMAN', '...
4     Q86U42  {'accession': 'Q86U42', 'id': 'PABP2_HUMAN', '...
..       ...                                                ...
95    Q969F9  {'accession': 'Q969F9', 'id': 'HPS3_HUMAN', 'p...
96    Q969Q5  {'accession': 'Q969Q5', 'id': 'RAB24_HUMAN', '...
97    Q969R2  {'accession': 'Q969R2', 'id': 'OSBP2_HUMAN', '...
98    Q969V5  {'accession': 'Q969V5', 'id': 'MUL1_HUMAN', 'p...
99    Q96A33  {'accession': 'Q96A33', 'id': 'CCD47_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 9 saved

EBI data for accession Q96A65 downloaded
EBI data for accession Q96AC1 downloaded
EBI data for accession Q96AE4 downloaded
EBI data for accession Q96AG4 downloaded
EBI data for accession Q96AT9 downloaded
EBI data for accession Q96BY6 downloaded
EBI data for accession Q96C90 downloaded
EBI data for accession Q96CS3 downloaded
EBI data for accession Q96CV9 downloaded
EBI data for accession Q96CW6 downloaded
EBI data for accession Q96DG6 downloaded
EBI data for accession Q96ED9 downloaded
EBI data for accession Q96EL3 downloaded
EBI data for accession Q96FJ2 downloaded
EBI data for accession Q96FW1 downloaded
EBI data for accession Q96FX7 downloaded
EBI data for accession Q96FZ7 downloaded
EBI data for accession Q96GG9 downloaded
EBI data for accession Q96GX9 downloaded
EBI data for accession Q96HC4 downloaded
EBI data for accession Q96HE7 downloaded
EBI data for accession Q96I24 downloaded
EBI data for accession Q96I25 downloaded
EBI data for accession Q96II8 downloaded
EBI data for accession Q96JB2 downloaded
EBI data for accession Q96JB5 downloaded
EBI data for accession Q96K76 downloaded
EBI data for accession Q96KR1 downloaded
EBI data for accession Q96ME1 downloaded
EBI data for accession Q96MX6 downloaded
EBI data for accession Q96N67 downloaded
EBI data for accession Q96P48 downloaded
EBI data for accession Q96P50 downloaded
EBI data for accession Q96PK6 downloaded
EBI data for accession Q96Q15 downloaded
EBI data for accession Q96QB1 downloaded
EBI data for accession Q96QK1 downloaded
EBI data for accession Q96RS6 downloaded
EBI data for accession Q96RU3 downloaded
EBI data for accession Q96T21 downloaded
EBI data for accession Q96T76 downloaded
EBI data for accession Q96T88 downloaded
EBI data for accession Q96TA1 downloaded
EBI data for accession Q99426 downloaded
EBI data for accession Q99439 downloaded
EBI data for accession Q99442 downloaded
EBI data for accession Q99459 downloaded
EBI data for accession Q99471 downloaded
EBI data for accession Q99536 downloaded
EBI data for accession Q99567 downloaded
EBI data for accession Q99575 downloaded
EBI data for accession Q99598 downloaded
EBI data for accession Q99741 downloaded
EBI data for accession Q99797 downloaded
EBI data for accession Q99805 downloaded
EBI data for accession Q99832 downloaded
EBI data for accession Q99873 downloaded
EBI data for accession Q99942 downloaded
EBI data for accession Q99961 downloaded
EBI data for accession Q9BPW8 downloaded
EBI data for accession Q9BPX3 downloaded
EBI data for accession Q9BQ52 downloaded
EBI data for accession Q9BQ70 downloaded
EBI data for accession Q9BQB6 downloaded
EBI data for accession Q9BRP1 downloaded
EBI data for accession Q9BRX2 downloaded
EBI data for accession Q9BSH4 downloaded
EBI data for accession Q9BSJ8 downloaded
EBI data for accession Q9BSL1 downloaded
EBI data for accession Q9BTT0 downloaded
EBI data for accession Q9BTV5 downloaded
EBI data for accession Q9BTW9 downloaded
EBI data for accession Q9BU76 downloaded
EBI data for accession Q9BUF5 downloaded
EBI data for accession Q9BUJ2 downloaded
EBI data for accession Q9BV81 downloaded
EBI data for accession Q9BVP2 downloaded
EBI data for accession Q9BW19 downloaded
EBI data for accession Q9BWU0 downloaded
EBI data for accession Q9BXF6 downloaded
EBI data for accession Q9BXJ9 downloaded
EBI data for accession Q9BXK5 downloaded
EBI data for accession Q9BXP5 downloaded
EBI data for accession Q9BXR0 downloaded
EBI data for accession Q9BXY0 downloaded
EBI data for accession Q9BY32 downloaded
EBI data for accession Q9BY44 downloaded
EBI data for accession Q9BYT8 downloaded
EBI data for accession Q9BYX2 downloaded
EBI data for accession Q9BZ29 downloaded
EBI data for accession Q9BZE1 downloaded
EBI data for accession Q9BZF1 downloaded
EBI data for accession Q9BZF9 downloaded
EBI data for accession Q9BZH6 downloaded
EBI data for accession Q9BZL4 downloaded
EBI data for accession Q9C0B1 downloaded
EBI data for accession Q9C0D5 downloaded
EBI data for accession Q9GZN8 downloaded
EBI data for accession Q9GZR7 downloaded
EBI data for accession Q9GZS1 downloaded
   accession                                           EBI_data
0     Q96A65  {'accession': 'Q96A65', 'id': 'EXOC4_HUMAN', '...
1     Q96AC1  {'accession': 'Q96AC1', 'id': 'FERM2_HUMAN', '...
2     Q96AE4  {'accession': 'Q96AE4', 'id': 'FUBP1_HUMAN', '...
3     Q96AG4  {'accession': 'Q96AG4', 'id': 'LRC59_HUMAN', '...
4     Q96AT9  {'accession': 'Q96AT9', 'id': 'RPE_HUMAN', 'pr...
..       ...                                                ...
95    Q9C0B1  {'accession': 'Q9C0B1', 'id': 'FTO_HUMAN', 'pr...
96    Q9C0D5  {'accession': 'Q9C0D5', 'id': 'TANC1_HUMAN', '...
97    Q9GZN8  {'accession': 'Q9GZN8', 'id': 'ADSSP_HUMAN', '...
98    Q9GZR7  {'accession': 'Q9GZR7', 'id': 'DDX24_HUMAN', '...
99    Q9GZS1  {'accession': 'Q9GZS1', 'id': 'RPA49_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 10 saved

EBI data for accession Q9H0C8 downloaded
EBI data for accession Q9H1B7 downloaded
EBI data for accession Q9H204 downloaded
EBI data for accession Q9H2G2 downloaded
EBI data for accession Q9H2M9 downloaded
EBI data for accession Q9H2U2 downloaded
EBI data for accession Q9H3U1 downloaded
EBI data for accession Q9H488 downloaded
EBI data for accession Q9H4A3 downloaded
EBI data for accession Q9H4H8 downloaded
EBI data for accession Q9H4L4 downloaded
EBI data for accession Q9H583 downloaded
EBI data for accession Q9H6R4 downloaded
EBI data for accession Q9H7C4 downloaded
EBI data for accession Q9H8Y8 downloaded
EBI data for accession Q9H936 downloaded
EBI data for accession Q9H9A5 downloaded
EBI data for accession Q9HAU4 downloaded
EBI data for accession Q9HAV0 downloaded
EBI data for accession Q9HAV4 downloaded
EBI data for accession Q9HB71 downloaded
EBI data for accession Q9HBH5 downloaded
EBI data for accession Q9HC35 downloaded
EBI data for accession Q9HC36 downloaded
EBI data for accession Q9HCC0 downloaded
EBI data for accession Q9HCG7 downloaded
EBI data for accession Q9HD20 downloaded
EBI data for accession Q9HD33 downloaded
EBI data for accession Q9HD67 downloaded
EBI data for accession Q9NP61 downloaded
EBI data for accession Q9NP79 downloaded
EBI data for accession Q9NP92 downloaded
EBI data for accession Q9NPG3 downloaded
EBI data for accession Q9NPJ8 downloaded
EBI data for accession Q9NQC3 downloaded
EBI data for accession Q9NQG5 downloaded
EBI data for accession Q9NQR4 downloaded
EBI data for accession Q9NQW6 downloaded
EBI data for accession Q9NQW7 downloaded
EBI data for accession Q9NR56 downloaded
EBI data for accession Q9NRR4 downloaded
EBI data for accession Q9NS00 downloaded
EBI data for accession Q9NSK0 downloaded
EBI data for accession Q9NT62 downloaded
EBI data for accession Q9NTJ3 downloaded
EBI data for accession Q9NUJ1 downloaded
EBI data for accession Q9NUP9 downloaded
EBI data for accession Q9NUQ6 downloaded
EBI data for accession Q9NUQ9 downloaded
EBI data for accession Q9NVM9 downloaded
EBI data for accession Q9NVN8 downloaded
EBI data for accession Q9NVU7 downloaded
EBI data for accession Q9NVW2 downloaded
EBI data for accession Q9NVZ3 downloaded
EBI data for accession Q9NW13 downloaded
EBI data for accession Q9NW15 downloaded
EBI data for accession Q9NX08 downloaded
EBI data for accession Q9NXG2 downloaded
EBI data for accession Q9NXH8 downloaded
EBI data for accession Q9NY33 downloaded
EBI data for accession Q9NYB9 downloaded
EBI data for accession Q9NYK5 downloaded
EBI data for accession Q9NYL2 downloaded
EBI data for accession Q9NZD2 downloaded
EBI data for accession Q9NZI7 downloaded
EBI data for accession Q9NZI8 downloaded
EBI data for accession Q9NZJ4 downloaded
EBI data for accession Q9NZJ7 downloaded
EBI data for accession Q9NZL9 downloaded
EBI data for accession Q9NZM1 downloaded
EBI data for accession Q9NZZ3 downloaded
EBI data for accession Q9P0K7 downloaded
EBI data for accession Q9P0L0 downloaded
EBI data for accession Q9P287 downloaded
EBI data for accession Q9P291 downloaded
EBI data for accession Q9P2E9 downloaded
EBI data for accession Q9P2J5 downloaded
EBI data for accession Q9P2T1 downloaded
EBI data for accession Q9P2W9 downloaded
EBI data for accession Q9UBB4 downloaded
EBI data for accession Q9UBB9 downloaded
EBI data for accession Q9UBE0 downloaded
EBI data for accession Q9UBF2 downloaded
EBI data for accession Q9UBG0 downloaded
EBI data for accession Q9UBI1 downloaded
EBI data for accession Q9UBI6 downloaded
EBI data for accession Q9UBM7 downloaded
EBI data for accession Q9UBT2 downloaded
EBI data for accession Q9UDY4 downloaded
EBI data for accession Q9UEW8 downloaded
EBI data for accession Q9UFN0 downloaded
EBI data for accession Q9UGP4 downloaded
EBI data for accession Q9UGP8 downloaded
EBI data for accession Q9UHB9 downloaded
EBI data for accession Q9UI14 downloaded
EBI data for accession Q9UID3 downloaded
EBI data for accession Q9UJA5 downloaded
EBI data for accession Q9UJU6 downloaded
EBI data for accession Q9UK41 downloaded
EBI data for accession Q9UK61 downloaded
   accession                                           EBI_data
0     Q9H0C8  {'accession': 'Q9H0C8', 'id': 'ILKAP_HUMAN', '...
1     Q9H1B7  {'accession': 'Q9H1B7', 'id': 'I2BPL_HUMAN', '...
2     Q9H204  {'accession': 'Q9H204', 'id': 'MED28_HUMAN', '...
3     Q9H2G2  {'accession': 'Q9H2G2', 'id': 'SLK_HUMAN', 'pr...
4     Q9H2M9  {'accession': 'Q9H2M9', 'id': 'RBGPR_HUMAN', '...
..       ...                                                ...
95    Q9UID3  {'accession': 'Q9UID3', 'id': 'VPS51_HUMAN', '...
96    Q9UJA5  {'accession': 'Q9UJA5', 'id': 'TRM6_HUMAN', 'p...
97    Q9UJU6  {'accession': 'Q9UJU6', 'id': 'DBNL_HUMAN', 'p...
98    Q9UK41  {'accession': 'Q9UK41', 'id': 'VPS28_HUMAN', '...
99    Q9UK61  {'accession': 'Q9UK61', 'id': 'TASOR_HUMAN', '...

[100 rows x 2 columns]
EBI pickle chunk 11 saved

EBI data for accession Q9UKG1 downloaded
EBI data for accession Q9UKP4 downloaded
EBI data for accession Q9UKX5 downloaded
EBI data for accession Q9UL54 downloaded
EBI data for accession Q9ULC4 downloaded
EBI data for accession Q9ULS5 downloaded
EBI data for accession Q9ULT8 downloaded
EBI data for accession Q9ULV4 downloaded
EBI data for accession Q9ULX3 downloaded
EBI data for accession Q9UM54 downloaded
EBI data for accession Q9UN81 downloaded
EBI data for accession Q9UNE7 downloaded
EBI data for accession Q9UNF0 downloaded
EBI data for accession Q9UNH7 downloaded
EBI data for accession Q9UNM6 downloaded
EBI data for accession Q9UNN8 downloaded
EBI data for accession Q9UNS2 downloaded
EBI data for accession Q9UPM8 downloaded
EBI data for accession Q9UPN3 downloaded
EBI data for accession Q9UQ80 downloaded
EBI data for accession Q9UQB8 downloaded
EBI data for accession Q9UQE7 downloaded
EBI data for accession Q9Y232 downloaded
EBI data for accession Q9Y263 downloaded
EBI data for accession Q9Y265 downloaded
EBI data for accession Q9Y295 downloaded
EBI data for accession Q9Y2L1 downloaded
EBI data for accession Q9Y2Q5 downloaded
EBI data for accession Q9Y2X7 downloaded
EBI data for accession Q9Y2Z0 downloaded
EBI data for accession Q9Y2Z4 downloaded
EBI data for accession Q9Y376 downloaded
EBI data for accession Q9Y383 downloaded
EBI data for accession Q9Y3A5 downloaded
EBI data for accession Q9Y3B3 downloaded
EBI data for accession Q9Y3B8 downloaded
EBI data for accession Q9Y3C6 downloaded
EBI data for accession Q9Y3C7 downloaded
EBI data for accession Q9Y3D0 downloaded
EBI data for accession Q9Y3E5 downloaded
EBI data for accession Q9Y3L3 downloaded
EBI data for accession Q9Y3U8 downloaded
EBI data for accession Q9Y450 downloaded
EBI data for accession Q9Y490 downloaded
EBI data for accession Q9Y4L1 downloaded
EBI data for accession Q9Y4P3 downloaded
EBI data for accession Q9Y4R8 downloaded
EBI data for accession Q9Y4W2 downloaded
EBI data for accession Q9Y4X5 downloaded
EBI data for accession Q9Y508 downloaded
EBI data for accession Q9Y5B8 downloaded
EBI data for accession Q9Y5B9 downloaded
EBI data for accession Q9Y5L0 downloaded
EBI data for accession Q9Y5M8 downloaded
EBI data for accession Q9Y5N6 downloaded
EBI data for accession Q9Y5P4 downloaded
EBI data for accession Q9Y5Q9 downloaded
EBI data for accession Q9Y618 downloaded
EBI data for accession Q9Y678 downloaded
EBI data for accession Q9Y696 downloaded
EBI data for accession Q9Y6B7 downloaded
EBI data for accession Q9Y6E0 downloaded
EBI data for accession Q9Y6G3 downloaded
EBI data for accession Q9Y6M1 downloaded
EBI data for accession Q9Y6M5 downloaded
EBI data for accession Q9Y6Y8 downloaded
   accession                                           EBI_data
0     Q9UKG1  {'accession': 'Q9UKG1', 'id': 'DP13A_HUMAN', '...
1     Q9UKP4  {'accession': 'Q9UKP4', 'id': 'ATS7_HUMAN', 'p...
2     Q9UKX5  {'accession': 'Q9UKX5', 'id': 'ITA11_HUMAN', '...
3     Q9UL54  {'accession': 'Q9UL54', 'id': 'TAOK2_HUMAN', '...
4     Q9ULC4  {'accession': 'Q9ULC4', 'id': 'MCTS1_HUMAN', '...
..       ...                                                ...
61    Q9Y6E0  {'accession': 'Q9Y6E0', 'id': 'STK24_HUMAN', '...
62    Q9Y6G3  {'accession': 'Q9Y6G3', 'id': 'RM42_HUMAN', 'p...
63    Q9Y6M1  {'accession': 'Q9Y6M1', 'id': 'IF2B2_HUMAN', '...
64    Q9Y6M5  {'accession': 'Q9Y6M5', 'id': 'ZNT1_HUMAN', 'p...
65    Q9Y6Y8  {'accession': 'Q9Y6Y8', 'id': 'S23IP_HUMAN', '...

[66 rows x 2 columns]
EBI pickle chunk 12 saved

Combine pickle chunks into a single file.

In [13]:
# Retrieve output chunks, merge them, and save as a unique file
EBI_proteins = pd.DataFrame()

for i in range(len(accessions)):
    with open(f"res/EBI_proteins_chunk_{i+1}.pkl", "rb") as f:
        EBI_proteins_chunk = pickle.load(f)
    EBI_proteins = pd.concat([EBI_proteins, EBI_proteins_chunk], ignore_index=True)

with open("res/EBI_proteins.pkl", "wb") as f:
    pickle.dump(EBI_proteins, f)

EBI_proteins

     accession                                           EBI_data
0       A0AVT1  {'accession': 'A0AVT1', 'id': 'UBA6_HUMAN', 'p...
1       A6NDU8  {'accession': 'A6NDU8', 'id': 'RIMC1_HUMAN', '...
2       A6NHR9  {'accession': 'A6NHR9', 'id': 'SMHD1_HUMAN', '...
3       A6NKF1  {'accession': 'A6NKF1', 'id': 'SAC31_HUMAN', '...
4       B2RTY4  {'accession': 'B2RTY4', 'id': 'MYO9A_HUMAN', '...
...        ...                                                ...
1161    Q9Y6E0  {'accession': 'Q9Y6E0', 'id': 'STK24_HUMAN', '...
1162    Q9Y6G3  {'accession': 'Q9Y6G3', 'id': 'RM42_HUMAN', 'p...
1163    Q9Y6M1  {'accession': 'Q9Y6M1', 'id': 'IF2B2_HUMAN', '...
1164    Q9Y6M5  {'accession': 'Q9Y6M5', 'id': 'ZNT1_HUMAN', 'p...
1165    Q9Y6Y8  {'accession': 'Q9Y6Y8', 'id': 'S23IP_HUMAN', '...

[1166 rows x 2 columns]

## 3 - Analyze data and extract information about each cysteine, including AlphaFold proximity data
### 3.1 - Retrieve AIUPred and EBI outputs from pickle and redistribute protein data over all cysteines

In [14]:
with open("res/AIUPred_proteins.pkl", "rb") as f:
    AIUPred_proteins = pickle.load(f)
with open("res/EBI_proteins.pkl", "rb") as f:
    EBI_proteins = pickle.load(f)

# Distribute protein data over all cysteines
redox = []
disorder = []
EBI_data = []

for i in range(len(input_data)):
    redox.append(AIUPred_proteins.loc[AIUPred_proteins["accession"] == input_data[accession_column][i].split(";")[0], "redox"].iloc[0])
    disorder.append(AIUPred_proteins.loc[AIUPred_proteins["accession"] == input_data[accession_column][i].split(";")[0], "disorder"].iloc[0])
    EBI_data.append(EBI_proteins.loc[EBI_proteins["accession"] == input_data[accession_column][i].split(";")[0], "EBI_data"].iloc[0])

AIUPred_output = pd.concat([input_data, pd.DataFrame({"redox": redox, "disorder": disorder})], axis=1)
AIUPred_output

,protein accession number,gene name,cysteine site,redox,disorder
0,P49588,AARS1,C773,[],"[0.6165097951889038, 0.630347728729248, 0.5685..."
1,P49588,AARS1,C903,[],"[0.6165097951889038, 0.630347728729248, 0.5685..."
2,P33527,ABCC1,C744,[],"[0.8710123300552368, 0.9304897785186768, 0.922..."
3,Q8NE71,ABCF1,C655,[],"[0.974740743637085, 0.9731984734535217, 0.9748..."
4,Q9NUJ1,ABHD10,C100,[],"[0.8191232085227966, 0.8696340918540955, 0.899..."
...,...,...,...,...,...
1719,Q96KR1,ZFR,C922,"[[327, 357], [379, 412], [568, 612]]","[0.7348648309707642, 0.720794141292572, 0.8413..."
1720,Q8N5A5,ZGPAT,C377,"[[317, 385]]","[0.5898325443267822, 0.5299968123435974, 0.569..."
1721,Q8TF68,ZNF384,C435,"[[223, 466]]","[0.9632839560508728, 0.9637404680252075, 0.969..."
1722,Q2TB10,ZNF800,C359,"[[0, 28], [225, 261], [283, 318], [347, 379], ...","[0.5370450615882874, 0.5559547543525696, 0.560..."
1723,Q15942,ZYX,C384,"[[368, 572]]","[0.9759196639060974, 0.975585401058197, 0.9766..."

In [15]:
EBI_output = pd.concat([input_data, pd.DataFrame({"EBI_data": EBI_data})], axis=1)
EBI_output

,protein accession number,gene name,cysteine site,EBI_data
0,P49588,AARS1,C773,"{'accession': 'P49588', 'id': 'SYAC_HUMAN', 'p..."
1,P49588,AARS1,C903,"{'accession': 'P49588', 'id': 'SYAC_HUMAN', 'p..."
2,P33527,ABCC1,C744,"{'accession': 'P33527', 'id': 'MRP1_HUMAN', 'p..."
3,Q8NE71,ABCF1,C655,"{'accession': 'Q8NE71', 'id': 'ABCF1_HUMAN', '..."
4,Q9NUJ1,ABHD10,C100,"{'accession': 'Q9NUJ1', 'id': 'ABHDA_HUMAN', '..."
...,...,...,...,...
1719,Q96KR1,ZFR,C922,"{'accession': 'Q96KR1', 'id': 'ZFR_HUMAN', 'pr..."
1720,Q8N5A5,ZGPAT,C377,"{'accession': 'Q8N5A5', 'id': 'ZGPAT_HUMAN', '..."
1721,Q8TF68,ZNF384,C435,"{'accession': 'Q8TF68', 'id': 'ZN384_HUMAN', '..."
1722,Q2TB10,ZNF800,C359,"{'accession': 'Q2TB10', 'id': 'ZN800_HUMAN', '..."
1723,Q15942,ZYX,C384,"{'accession': 'Q15942', 'id': 'ZYX_HUMAN', 'pr..."

### 3.2 - Transform AIUPred output into specific features

In [16]:
sensitive = []
within = []
disorder = []

for i in range(len(AIUPred_output)):
    cysteine = list(AIUPred_output[cysteine_column][i].split(","))[0]  # if several cysteines, consider just the first
    cysteine_pos = int(cysteine[1:] if cysteine[0].lower() == "c" else cysteine)  # if cysteine starts with a "C", remove it
    withinyn = "No"
    # Is there a region that is sensitive to oxidation?
    if AIUPred_output["redox"][i] == "NaN":
        sensitive.append("NaN")
        within.append("NaN")
    else:
        if len(AIUPred_output["redox"][i]) == 0:
            sensitive.append("No")
        else:
            sensitive.append("Yes")
            # Is the cysteine within that region?
            for j in range(len(AIUPred_output["redox"][i])):
                if (AIUPred_output["redox"][i][j][0] <= cysteine_pos) & (cysteine_pos <= AIUPred_output["redox"][i][j][1]):
                    withinyn = "Yes"    # if cysteine is within one of the regions
        within.append(withinyn)
    # What is the disorder value of the cysteine?
    if AIUPred_output["disorder"][i] == "NaN" or cysteine_pos > len(AIUPred_output["disorder"][i]):
        disorder.append("NaN")
    else:
        disorder.append(round(AIUPred_output["disorder"][i][cysteine_pos-1], 2))

AIUPred_features = pd.DataFrame({"sensitive": sensitive, "cysteine_within": within, "disorder_value": disorder})

### 3.3 - Transform EBI output into the desired features

In [17]:
proteinLength = []
fullName = []
subcellularLoc = []

for i in range(len(EBI_output)):
    
    # Protein length and sequence
    proteinLength.append(EBI_output["EBI_data"][i]["sequence"]["length"])
#     protein_sequence = EBI_output["EBI_data"][i]["sequence"]["sequence"]
    
    # Full protein name
    fullName.append(EBI_output["EBI_data"][i]["protein"]["recommendedName"]["fullName"]["value"])
    
    # Subcellular location
    locations = []
    try:
        for j in EBI_output["EBI_data"][i]["comments"]:
            if j["type"] == "SUBCELLULAR_LOCATION":
                try:
                    for k in j["locations"]:
                        locations.append(k["location"]["value"])
                except Exception:
                    pass
    except:
        pass
    subcellularLoc.append(locations)

EBI_features = pd.DataFrame({"protein_length": proteinLength, "full_name": fullName, "subcellular_loc": subcellularLoc})

### 3.4 - Download AlphaFold data and extract proximity residues for each cysteine

In [18]:
class AlphaFoldClient:
    def __init__(self):
        self.session = requests.Session()
        self.parser = PDB.PDBParser()

    def get_pdb(self, accession):
        ### Access AlphaFold's API and get model ID and pdb_url for the "correct" model
        protein_length = EBI_proteins.loc[EBI_proteins["accession"] == accession, "EBI_data"].iloc[0]["sequence"]["length"]
        url = "https://alphafold.ebi.ac.uk/api/prediction/"
        requestURL = url+accession
        global no_output, no_length
        model_ID, pdb_url = "NaN", "NaN"
        try:    # try to download metadata page
            AlphaFold_res = self.session.get(requestURL, params={"include_complexes": "false"})
            AlphaFold_res.raise_for_status()
        except:
            print(f"Impossible to retrieve AlphaFold metadata for accession {accession}")
            no_output+=1
            return model_ID, pdb_url   # if there is no AlphaFold output
        AlphaFold_output = json.loads(AlphaFold_res.text)
        print(f"AlphaFold metadata for accession {accession} downloaded")        
        # Loop through models to select the one where sequence is same length as in UniProt
        for i in AlphaFold_output:
            if i["sequenceEnd"] == protein_length:
                model_ID = i["modelEntityId"]
                pdb_url = i["pdbUrl"]
                return model_ID, pdb_url   # if a correct model is found
        print(f"No AlphaFold model with same sequence length as UniProt for accession {accession}")
        no_length+=1
        return model_ID, pdb_url   # if there is no model that fits the UniProt sequence length

    def get_chain(self, accession):
        ### Access pdb model on AlphaFold's API and extract chain
        model_ID, pdb_url = self.get_pdb(accession)
        try:    # try to download pdb file
            pdb_res = self.session.get(pdb_url)
            pdb_res.raise_for_status()
        except:
            print(f"Impossible to retrieve pdb data for accession {accession}")
            return model_ID, "NaN"
        # Parse the pdb file-like object to extract the chain with info on all residues
        structure = self.parser.get_structure(accession, io.StringIO(pdb_res.text))
        model = structure[0]
        chain = model["A"]
        print(f"AlphaFold chain for accession {accession} downloaded")
        return model_ID, chain

In [19]:
def distance(chain, residue1, residue2):
    ### Calculate distance between C-alpha atoms of two residues
    # Extract the C-alpha (CA) atoms for both residues
    atom1 = chain[residue1]["CA"]
    atom2 = chain[residue2]["CA"]
    
    # Calculate the vector distance
    diff = atom1.get_coord() - atom2.get_coord()
    return np.sqrt(np.sum(diff ** 2))

Loop over all the cysteines, download AlphaFold chain for their protein, then scan the chain and extract residues in proximity to the cysteine.<br>
Combine cysteine information, AlphaFold model ID, and proximity residues data in a DataFrame.<br>
Takes about 2,5 minutes for 1000 cysteines.

In [20]:
proximity = 20   # distance of interest, in Å
no_output = 0
no_length = 0
AlphaFold_model_IDs = []
AlphaFold_proximity_residues = []
old_accession = None
client = AlphaFoldClient()

# Download data from AlphaFold's API
for i in range(len(input_data)):  # Loop over rows
    accession = input_data[accession_column][i].split(";")[0]
    cysteine = list(str(input_data[cysteine_column][i]).split(","))[0]  # if several cysteines, consider just the first
    cysteine_pos = int(cysteine[1:] if cysteine[0].lower() == "c" else cysteine)  # if cysteine starts with a "C", remove it
    proximity_residues = {}

    if accession != old_accession:  # download only if it's a new protein
        model_ID, chain = client.get_chain(accession)

    try:   # Loop over residues and select those close to the cysteine
        for k in range (sum(1 for res in chain)):
            dist = distance(chain, cysteine_pos, k+1)
            if dist <= proximity:
                proximity_residues[k+1] = round(dist, 2)
    except:   # If no chain could be downloaded
        pass

    AlphaFold_model_IDs.append(model_ID)
    AlphaFold_proximity_residues.append(proximity_residues)        
    old_accession = accession

# Assemble all data in a DataFrame
AlphaFold_output = pd.concat([input_data, pd.DataFrame({"AlphaFold_model_ID": AlphaFold_model_IDs,
                                                         "proximity_residues": AlphaFold_proximity_residues})], axis=1)

print(AlphaFold_output)
print(f"\nTotal accessions with no output: {no_output}\nTotal accessions with no model of the correct length: {no_length}\n")

AlphaFold metadata for accession P49588 downloaded
AlphaFold chain for accession P49588 downloaded
AlphaFold metadata for accession P33527 downloaded
AlphaFold chain for accession P33527 downloaded
AlphaFold metadata for accession Q8NE71 downloaded
AlphaFold chain for accession Q8NE71 downloaded
AlphaFold metadata for accession Q9NUJ1 downloaded
AlphaFold chain for accession Q9NUJ1 downloaded
AlphaFold metadata for accession Q8IZP0 downloaded
AlphaFold chain for accession Q8IZP0 downloaded
AlphaFold metadata for accession Q9NYB9 downloaded
AlphaFold chain for accession Q9NYB9 downloaded
AlphaFold metadata for accession Q12979 downloaded
AlphaFold chain for accession Q12979 downloaded
AlphaFold metadata for accession Q15018 downloaded
AlphaFold chain for accession Q15018 downloaded
AlphaFold metadata for accession Q13085 downloaded
AlphaFold chain for accession Q13085 downloaded
AlphaFold metadata for accession P49748 downloaded
AlphaFold chain for accession P49748 downloaded
AlphaFold metadata for accession Q96P50 downloaded
AlphaFold chain for accession Q96P50 downloaded
AlphaFold metadata for accession P24752 downloaded
AlphaFold chain for accession P24752 downloaded
AlphaFold metadata for accession P53396 downloaded
AlphaFold chain for accession P53396 downloaded
AlphaFold metadata for accession P21399 downloaded
AlphaFold chain for accession P21399 downloaded
AlphaFold metadata for accession P24666 downloaded
AlphaFold chain for accession P24666 downloaded
AlphaFold metadata for accession P33121 downloaded
AlphaFold chain for accession P33121 downloaded
AlphaFold metadata for accession O95573 downloaded
AlphaFold chain for accession O95573 downloaded
AlphaFold metadata for accession P60709 downloaded
AlphaFold chain for accession P60709 downloaded
AlphaFold metadata for accession O96019 downloaded
AlphaFold chain for accession O96019 downloaded
AlphaFold metadata for accession P12814 downloaded
AlphaFold chain for accession P12814 downloaded
AlphaFold metadata for accession O43707 downloaded
AlphaFold chain for accession O43707 downloaded
AlphaFold metadata for accession P61160 downloaded
AlphaFold chain for accession P61160 downloaded
AlphaFold metadata for accession P61158 downloaded
AlphaFold chain for accession P61158 downloaded
AlphaFold metadata for accession Q04771 downloaded
AlphaFold chain for accession Q04771 downloaded
AlphaFold metadata for accession Q13443 downloaded
AlphaFold chain for accession Q13443 downloaded
AlphaFold metadata for accession Q9UKP4 downloaded
AlphaFold chain for accession Q9UKP4 downloaded
AlphaFold metadata for accession P11766 downloaded
AlphaFold chain for accession P11766 downloaded
AlphaFold metadata for accession Q9GZN8 downloaded
AlphaFold chain for accession Q9GZN8 downloaded
AlphaFold metadata for accession Q8N556 downloaded
AlphaFold chain for accession Q8N556 downloaded
AlphaFold metadata for accession Q8WV93 downloaded
AlphaFold chain for accession Q8WV93 downloaded
AlphaFold metadata for accession P52594 downloaded
AlphaFold chain for accession P52594 downloaded
AlphaFold metadata for accession Q53H12 downloaded
AlphaFold chain for accession Q53H12 downloaded
AlphaFold metadata for accession O00116 downloaded
AlphaFold chain for accession O00116 downloaded
AlphaFold metadata for accession P23526 downloaded
AlphaFold chain for accession P23526 downloaded
AlphaFold metadata for accession Q09666 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q09666
Impossible to retrieve pdb data for accession Q09666
AlphaFold metadata for accession O95831 downloaded
AlphaFold chain for accession O95831 downloaded
AlphaFold metadata for accession Q12904 downloaded
AlphaFold chain for accession Q12904 downloaded
AlphaFold metadata for accession Q13155 downloaded
AlphaFold chain for accession Q13155 downloaded
AlphaFold metadata for accession O00170 downloaded
AlphaFold chain for accession O00170 downloaded
AlphaFold metadata for accession P15121 downloaded
AlphaFold chain for accession P15121 downloaded
AlphaFold metadata for accession P31751 downloaded
AlphaFold chain for accession P31751 downloaded
AlphaFold metadata for accession P13716 downloaded
AlphaFold chain for accession P13716 downloaded
AlphaFold metadata for accession Q13740 downloaded
AlphaFold chain for accession Q13740 downloaded
AlphaFold metadata for accession Q8IZ83 downloaded
AlphaFold chain for accession Q8IZ83 downloaded
AlphaFold metadata for accession P54886 downloaded
AlphaFold chain for accession P54886 downloaded
AlphaFold metadata for accession Q02252 downloaded
AlphaFold chain for accession Q02252 downloaded
AlphaFold metadata for accession P49189 downloaded
AlphaFold chain for accession P49189 downloaded
AlphaFold metadata for accession P04075 downloaded
AlphaFold chain for accession P04075 downloaded
AlphaFold metadata for accession P05062 downloaded
AlphaFold chain for accession P05062 downloaded
AlphaFold metadata for accession P09972 downloaded
AlphaFold chain for accession P09972 downloaded
AlphaFold metadata for accession Q92685 downloaded
AlphaFold chain for accession Q92685 downloaded
AlphaFold metadata for accession Q01484 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q01484
Impossible to retrieve pdb data for accession Q01484
AlphaFold metadata for accession O75179 downloaded
AlphaFold chain for accession O75179 downloaded
AlphaFold metadata for accession Q6AI12 downloaded
AlphaFold chain for accession Q6AI12 downloaded
AlphaFold metadata for accession Q6ZW76 downloaded
AlphaFold chain for accession Q6ZW76 downloaded
AlphaFold metadata for accession Q9NQW6 downloaded
AlphaFold chain for accession Q9NQW6 downloaded
AlphaFold metadata for accession Q9NW15 downloaded
AlphaFold chain for accession Q9NW15 downloaded
AlphaFold metadata for accession Q92688 downloaded
AlphaFold chain for accession Q92688 downloaded
AlphaFold metadata for accession Q9BTT0 downloaded
AlphaFold chain for accession Q9BTT0 downloaded
AlphaFold metadata for accession P04083 downloaded
AlphaFold chain for accession P04083 downloaded
AlphaFold metadata for accession P50995 downloaded
AlphaFold chain for accession P50995 downloaded
AlphaFold metadata for accession P07355 downloaded
AlphaFold chain for accession P07355 downloaded
AlphaFold metadata for accession P08758 downloaded
AlphaFold chain for accession P08758 downloaded
AlphaFold metadata for accession P08133 downloaded
AlphaFold chain for accession P08133 downloaded
AlphaFold metadata for accession P20073 downloaded
AlphaFold chain for accession P20073 downloaded
AlphaFold metadata for accession Q06278 downloaded
AlphaFold chain for accession Q06278 downloaded
AlphaFold metadata for accession Q10567 downloaded
AlphaFold chain for accession Q10567 downloaded
AlphaFold metadata for accession O43747 downloaded
AlphaFold chain for accession O43747 downloaded
AlphaFold metadata for accession O95782 downloaded
AlphaFold chain for accession O95782 downloaded
AlphaFold metadata for accession P63010 downloaded
AlphaFold chain for accession P63010 downloaded
AlphaFold metadata for accession O14617 downloaded
AlphaFold chain for accession O14617 downloaded
AlphaFold metadata for accession Q9Y6B7 downloaded
AlphaFold chain for accession Q9Y6B7 downloaded
AlphaFold metadata for accession Q9UPM8 downloaded
AlphaFold chain for accession Q9UPM8 downloaded
AlphaFold metadata for accession O43299 downloaded
AlphaFold chain for accession O43299 downloaded
AlphaFold metadata for accession Q92870 downloaded
AlphaFold chain for accession Q92870 downloaded
AlphaFold metadata for accession P13798 downloaded
AlphaFold chain for accession P13798 downloaded
AlphaFold metadata for accession Q96GX9 downloaded
AlphaFold chain for accession Q96GX9 downloaded
AlphaFold metadata for accession Q6UXV4 downloaded
AlphaFold chain for accession Q6UXV4 downloaded
AlphaFold metadata for accession Q9UKG1 downloaded
AlphaFold chain for accession Q9UKG1 downloaded
AlphaFold metadata for accession O60306 downloaded
AlphaFold chain for accession O60306 downloaded
AlphaFold metadata for accession Q96P48 downloaded
AlphaFold chain for accession Q96P48 downloaded
AlphaFold metadata for accession P48444 downloaded

AlphaFold chain for accession P48444 downloaded
AlphaFold metadata for accession P18085 downloaded
AlphaFold chain for accession P18085 downloaded
AlphaFold metadata for accession Q9NP61 downloaded
AlphaFold chain for accession Q9NP61 downloaded
AlphaFold metadata for accession Q13795 downloaded
AlphaFold chain for accession Q13795 downloaded
AlphaFold metadata for accession Q68EM7 downloaded
AlphaFold chain for accession Q68EM7 downloaded
AlphaFold metadata for accession Q8N392 downloaded
AlphaFold chain for accession Q8N392 downloaded
AlphaFold metadata for accession Q52LW3 downloaded
AlphaFold chain for accession Q52LW3 downloaded
AlphaFold metadata for accession Q92888 downloaded
AlphaFold chain for accession Q92888 downloaded
AlphaFold metadata for accession Q92974 downloaded
AlphaFold chain for accession Q92974 downloaded
AlphaFold metadata for accession Q14155 downloaded
AlphaFold chain for accession Q14155 downloaded
AlphaFold metadata for accession Q9Y4X5 downloaded
AlphaFold chain for accession Q9Y4X5 downloaded
AlphaFold metadata for accession Q15041 downloaded
AlphaFold chain for accession Q15041 downloaded
AlphaFold metadata for accession Q8IUR7 downloaded
AlphaFold chain for accession Q8IUR7 downloaded
AlphaFold metadata for accession Q9P291 downloaded
AlphaFold chain for accession Q9P291 downloaded
AlphaFold metadata for accession Q92747 downloaded
AlphaFold chain for accession Q92747 downloaded
AlphaFold metadata for accession O15144 downloaded
AlphaFold chain for accession O15144 downloaded
AlphaFold metadata for accession Q8N3C0 downloaded
AlphaFold chain for accession Q8N3C0 downloaded
AlphaFold metadata for accession O95260 downloaded
AlphaFold chain for accession O95260 downloaded
AlphaFold metadata for accession Q676U5 downloaded
AlphaFold chain for accession Q676U5 downloaded
AlphaFold metadata for accession Q9NT62 downloaded
AlphaFold chain for accession Q9NT62 downloaded
AlphaFold metadata for accession P31939 downloaded
AlphaFold chain for accession P31939 downloaded
AlphaFold metadata for accession Q6DD88 downloaded
AlphaFold chain for accession Q6DD88 downloaded
AlphaFold metadata for accession Q8NB49 downloaded
AlphaFold chain for accession Q8NB49 downloaded
AlphaFold metadata for accession Q9HD20 downloaded
AlphaFold chain for accession Q9HD20 downloaded
AlphaFold metadata for accession P54709 downloaded
AlphaFold chain for accession P54709 downloaded
AlphaFold metadata for accession P16615 downloaded
AlphaFold chain for accession P16615 downloaded
AlphaFold metadata for accession P20020 downloaded
AlphaFold chain for accession P20020 downloaded
AlphaFold metadata for accession P23634 downloaded
AlphaFold chain for accession P23634 downloaded
AlphaFold metadata for accession O75947 downloaded
AlphaFold chain for accession O75947 downloaded
AlphaFold metadata for accession P21281 downloaded
AlphaFold chain for accession P21281 downloaded
AlphaFold metadata for accession Q9UBB4 downloaded
AlphaFold chain for accession Q9UBB4 downloaded
AlphaFold metadata for accession P30530 downloaded
AlphaFold chain for accession P30530 downloaded
AlphaFold metadata for accession O14867 downloaded
AlphaFold chain for accession O14867 downloaded
AlphaFold metadata for accession Q9UQB8 downloaded
AlphaFold chain for accession Q9UQB8 downloaded
AlphaFold metadata for accession O75531 downloaded
AlphaFold chain for accession O75531 downloaded
AlphaFold metadata for accession P54687 downloaded
AlphaFold chain for accession P54687 downloaded
AlphaFold metadata for accession Q9P287 downloaded
AlphaFold chain for accession Q9P287 downloaded
AlphaFold metadata for accession Q9BXK5 downloaded
AlphaFold chain for accession Q9BXK5 downloaded
AlphaFold metadata for accession P11274 downloaded
AlphaFold chain for accession P11274 downloaded
AlphaFold metadata for accession Q13867 downloaded
AlphaFold chain for accession Q13867 downloaded
AlphaFold metadata for accession Q6QNY1 downloaded
AlphaFold chain for accession Q6QNY1 downloaded
AlphaFold metadata for accession Q14692 downloaded
AlphaFold chain for accession Q14692 downloaded
AlphaFold metadata for accession O95861 downloaded
AlphaFold chain for accession O95861 downloaded
AlphaFold metadata for accession P35613 downloaded
AlphaFold chain for accession P35613 downloaded
AlphaFold metadata for accession O14981 downloaded
AlphaFold chain for accession O14981 downloaded
AlphaFold metadata for accession P41223 downloaded
AlphaFold chain for accession P41223 downloaded
AlphaFold metadata for accession Q7L1Q6 downloaded
AlphaFold chain for accession Q7L1Q6 downloaded
AlphaFold metadata for accession Q9NS00 downloaded
AlphaFold chain for accession Q9NS00 downloaded
AlphaFold metadata for accession Q9Y376 downloaded
AlphaFold chain for accession Q9Y376 downloaded
AlphaFold metadata for accession Q86Y37 downloaded
AlphaFold chain for accession Q86Y37 downloaded
AlphaFold metadata for accession Q9HB71 downloaded
AlphaFold chain for accession Q9HB71 downloaded
AlphaFold metadata for accession P27797 downloaded
AlphaFold chain for accession P27797 downloaded
AlphaFold metadata for accession Q13557 downloaded
AlphaFold chain for accession Q13557 downloaded
AlphaFold metadata for accession Q13555 downloaded
AlphaFold chain for accession Q13555 downloaded
AlphaFold metadata for accession Q86VP6 downloaded
AlphaFold chain for accession Q86VP6 downloaded
AlphaFold metadata for accession Q01518 downloaded
AlphaFold chain for accession Q01518 downloaded
AlphaFold metadata for accession P40123 downloaded
AlphaFold chain for accession P40123 downloaded
AlphaFold metadata for accession P07384 downloaded
AlphaFold chain for accession P07384 downloaded
AlphaFold metadata for accession P17655 downloaded
AlphaFold chain for accession P17655 downloaded
AlphaFold metadata for accession P04632 downloaded
AlphaFold chain for accession P04632 downloaded
AlphaFold metadata for accession P52907 downloaded
AlphaFold chain for accession P52907 downloaded
AlphaFold metadata for accession P47756 downloaded
AlphaFold chain for accession P47756 downloaded
AlphaFold metadata for accession Q86X55 downloaded
AlphaFold chain for accession Q86X55 downloaded
AlphaFold metadata for accession P04040 downloaded
AlphaFold chain for accession P04040 downloaded
AlphaFold metadata for accession O75828 downloaded
AlphaFold chain for accession O75828 downloaded
AlphaFold metadata for accession P45973 downloaded
AlphaFold chain for accession P45973 downloaded
AlphaFold metadata for accession Q6P1N0 downloaded
AlphaFold chain for accession Q6P1N0 downloaded
AlphaFold metadata for accession Q8N163 downloaded
AlphaFold chain for accession Q8N163 downloaded
AlphaFold metadata for accession Q6UXH8 downloaded
AlphaFold chain for accession Q6UXH8 downloaded
AlphaFold metadata for accession O60826 downloaded
AlphaFold chain for accession O60826 downloaded
AlphaFold metadata for accession Q96A33 downloaded
AlphaFold chain for accession Q96A33 downloaded
AlphaFold metadata for accession Q6ZUT6 downloaded
AlphaFold chain for accession Q6ZUT6 downloaded
AlphaFold metadata for accession P30281 downloaded
AlphaFold chain for accession P30281 downloaded
AlphaFold metadata for accession P78371 downloaded
AlphaFold chain for accession P78371 downloaded
AlphaFold metadata for accession P49368 downloaded
AlphaFold chain for accession P49368 downloaded
AlphaFold metadata for accession P50991 downloaded
AlphaFold chain for accession P50991 downloaded
AlphaFold metadata for accession P48643 downloaded
AlphaFold chain for accession P48643 downloaded
AlphaFold metadata for accession P40227 downloaded
AlphaFold chain for accession P40227 downloaded
AlphaFold metadata for accession Q99832 downloaded
AlphaFold chain for accession Q99832 downloaded
AlphaFold metadata for accession P50990 downloaded
AlphaFold chain for accession P50990 downloaded
AlphaFold metadata for accession P48509 downloaded
AlphaFold chain for accession P48509 downloaded
AlphaFold metadata for accession P16070 downloaded
AlphaFold chain for accession P16070 downloaded
AlphaFold metadata for accession P08174 downloaded
AlphaFold chain for accession P08174 downloaded
AlphaFold metadata for accession P13987 downloaded
AlphaFold chain for accession P13987 downloaded

AlphaFold metadata for accession Q13042 downloaded
AlphaFold chain for accession Q13042 downloaded
AlphaFold metadata for accession P30260 downloaded
AlphaFold chain for accession P30260 downloaded
AlphaFold metadata for accession Q16543 downloaded
AlphaFold chain for accession Q16543 downloaded
AlphaFold metadata for accession O60508 downloaded
AlphaFold chain for accession O60508 downloaded
AlphaFold metadata for accession P60953 downloaded
AlphaFold chain for accession P60953 downloaded
AlphaFold metadata for accession Q99459 downloaded
AlphaFold chain for accession Q99459 downloaded
AlphaFold metadata for accession Q99741 downloaded
AlphaFold chain for accession Q99741 downloaded
AlphaFold metadata for accession Q00537 downloaded
AlphaFold chain for accession Q00537 downloaded
AlphaFold metadata for accession P11802 downloaded
AlphaFold chain for accession P11802 downloaded
AlphaFold metadata for accession Q96JB5 downloaded
AlphaFold chain for accession Q96JB5 downloaded
AlphaFold metadata for accession Q00534 downloaded
AlphaFold chain for accession Q00534 downloaded
AlphaFold metadata for accession P50750 downloaded
AlphaFold chain for accession P50750 downloaded
AlphaFold metadata for accession P38936 downloaded
AlphaFold chain for accession P38936 downloaded
AlphaFold metadata for accession Q9Y232 downloaded
AlphaFold chain for accession Q9Y232 downloaded
Impossible to retrieve AlphaFold metadata for accession P49454
Impossible to retrieve pdb data for accession P49454
AlphaFold metadata for accession O15078 downloaded
AlphaFold chain for accession O15078 downloaded
AlphaFold metadata for accession Q6P2H3 downloaded
AlphaFold chain for accession Q6P2H3 downloaded
AlphaFold metadata for accession Q9Y5P4 downloaded
AlphaFold chain for accession Q9Y5P4 downloaded
AlphaFold metadata for accession P23528 downloaded
AlphaFold chain for accession P23528 downloaded
AlphaFold metadata for accession Q9NZZ3 downloaded
AlphaFold chain for accession Q9NZZ3 downloaded
AlphaFold metadata for accession Q96FZ7 downloaded
AlphaFold chain for accession Q96FZ7 downloaded
AlphaFold metadata for accession Q9Y3D0 downloaded
AlphaFold chain for accession Q9Y3D0 downloaded
AlphaFold metadata for accession Q8TCG1 downloaded
AlphaFold chain for accession Q8TCG1 downloaded
AlphaFold metadata for accession Q07065 downloaded
AlphaFold chain for accession Q07065 downloaded
AlphaFold metadata for accession Q14008 downloaded
AlphaFold chain for accession Q14008 downloaded
AlphaFold metadata for accession O75122 downloaded
AlphaFold chain for accession O75122 downloaded
AlphaFold metadata for accession O14967 downloaded
AlphaFold chain for accession O14967 downloaded
AlphaFold metadata for accession O00299 downloaded
AlphaFold chain for accession O00299 downloaded
AlphaFold metadata for accession Q9Y696 downloaded
AlphaFold chain for accession Q9Y696 downloaded
AlphaFold metadata for accession O75503 downloaded
AlphaFold chain for accession O75503 downloaded
AlphaFold metadata for accession P09496 downloaded
AlphaFold chain for accession P09496 downloaded
AlphaFold metadata for accession P09497 downloaded
AlphaFold chain for accession P09497 downloaded
AlphaFold metadata for accession Q00610 downloaded
AlphaFold chain for accession Q00610 downloaded
AlphaFold metadata for accession Q96DG6 downloaded
AlphaFold chain for accession Q96DG6 downloaded
AlphaFold metadata for accession P62633 downloaded
AlphaFold chain for accession P62633 downloaded
AlphaFold metadata for accession Q99439 downloaded
AlphaFold chain for accession Q99439 downloaded
AlphaFold metadata for accession Q9H9A5 downloaded
AlphaFold chain for accession Q9H9A5 downloaded
AlphaFold metadata for accession P09543 downloaded
AlphaFold chain for accession P09543 downloaded
AlphaFold metadata for accession Q96JB2 downloaded
AlphaFold chain for accession Q96JB2 downloaded
AlphaFold metadata for accession P08572 downloaded
AlphaFold chain for accession P08572 downloaded
AlphaFold metadata for accession Q9UBI1 downloaded
AlphaFold chain for accession Q9UBI1 downloaded
AlphaFold metadata for accession Q9NX08 downloaded
AlphaFold chain for accession Q9NX08 downloaded
AlphaFold metadata for accession P21964 downloaded
AlphaFold chain for accession P21964 downloaded
AlphaFold metadata for accession Q86VU5 downloaded
AlphaFold chain for accession Q86VU5 downloaded
AlphaFold metadata for accession P53621 downloaded
AlphaFold chain for accession P53621 downloaded
AlphaFold metadata for accession P53618 downloaded
AlphaFold chain for accession P53618 downloaded
AlphaFold metadata for accession P35606 downloaded
AlphaFold chain for accession P35606 downloaded
AlphaFold metadata for accession Q9Y678 downloaded
AlphaFold chain for accession Q9Y678 downloaded
AlphaFold metadata for accession Q9UBF2 downloaded
AlphaFold chain for accession Q9UBF2 downloaded
AlphaFold metadata for accession Q9UNS2 downloaded
AlphaFold chain for accession Q9UNS2 downloaded
AlphaFold metadata for accession Q92905 downloaded
AlphaFold chain for accession Q92905 downloaded
AlphaFold metadata for accession Q9ULV4 downloaded
AlphaFold chain for accession Q9ULV4 downloaded
AlphaFold metadata for accession Q14019 downloaded
AlphaFold chain for accession Q14019 downloaded
AlphaFold metadata for accession O75131 downloaded
AlphaFold chain for accession O75131 downloaded
AlphaFold metadata for accession P31327 downloaded
AlphaFold chain for accession P31327 downloaded
AlphaFold metadata for accession Q16630 downloaded
AlphaFold chain for accession Q16630 downloaded
AlphaFold metadata for accession P50416 downloaded
AlphaFold chain for accession P50416 downloaded
AlphaFold metadata for accession Q08257 downloaded
AlphaFold chain for accession Q08257 downloaded
AlphaFold metadata for accession O75390 downloaded
AlphaFold chain for accession O75390 downloaded
AlphaFold metadata for accession O75534 downloaded
AlphaFold chain for accession O75534 downloaded
AlphaFold metadata for accession P55060 downloaded
AlphaFold chain for accession P55060 downloaded
AlphaFold metadata for accession P67870 downloaded
AlphaFold chain for accession P67870 downloaded
AlphaFold metadata for accession P21291 downloaded
AlphaFold chain for accession P21291 downloaded
AlphaFold metadata for accession P26232 downloaded
AlphaFold chain for accession P26232 downloaded
AlphaFold metadata for accession O60716 downloaded
AlphaFold chain for accession O60716 downloaded
AlphaFold metadata for accession P17812 downloaded
AlphaFold chain for accession P17812 downloaded
AlphaFold metadata for accession Q6PD62 downloaded
AlphaFold chain for accession Q6PD62 downloaded
AlphaFold metadata for accession P10619 downloaded
AlphaFold chain for accession P10619 downloaded
AlphaFold metadata for accession P07858 downloaded
AlphaFold chain for accession P07858 downloaded
AlphaFold metadata for accession P53634 downloaded
AlphaFold chain for accession P53634 downloaded
AlphaFold metadata for accession Q13616 downloaded
AlphaFold chain for accession Q13616 downloaded
AlphaFold metadata for accession Q13617 downloaded
AlphaFold chain for accession Q13617 downloaded
AlphaFold metadata for accession Q13620 downloaded
AlphaFold chain for accession Q13620 downloaded
AlphaFold metadata for accession Q93034 downloaded
AlphaFold chain for accession Q93034 downloaded
AlphaFold metadata for accession Q69YN2 downloaded
AlphaFold chain for accession Q69YN2 downloaded
AlphaFold metadata for accession P00387 downloaded
AlphaFold chain for accession P00387 downloaded
AlphaFold metadata for accession Q9NUQ9 downloaded
AlphaFold chain for accession Q9NUQ9 downloaded
AlphaFold metadata for accession P51398 downloaded
AlphaFold chain for accession P51398 downloaded
AlphaFold metadata for accession Q6PI48 downloaded
AlphaFold chain for accession Q6PI48 downloaded
AlphaFold metadata for accession Q16643 downloaded
AlphaFold chain for accession Q16643 downloaded
AlphaFold metadata for accession Q9UJU6 downloaded
AlphaFold chain for accession Q9UJU6 downloaded
AlphaFold metadata for accession Q58WW2 downloaded
AlphaFold chain for accession Q58WW2 downloaded
AlphaFold metadata for accession P27707 downloaded
AlphaFold chain for accession P27707 downloaded
AlphaFold metadata for accession Q14203 downloaded

AlphaFold chain for accession Q14203 downloaded
AlphaFold metadata for accession Q96GG9 downloaded
AlphaFold chain for accession Q96GG9 downloaded
AlphaFold metadata for accession O94760 downloaded
AlphaFold chain for accession O94760 downloaded
AlphaFold metadata for accession Q16531 downloaded
AlphaFold chain for accession Q16531 downloaded
AlphaFold metadata for accession P39656 downloaded
AlphaFold chain for accession P39656 downloaded
AlphaFold metadata for accession Q92499 downloaded
AlphaFold chain for accession Q92499 downloaded
AlphaFold metadata for accession Q92841 downloaded
AlphaFold chain for accession Q92841 downloaded
AlphaFold metadata for accession Q9GZR7 downloaded
AlphaFold chain for accession Q9GZR7 downloaded
AlphaFold metadata for accession Q13838 downloaded
AlphaFold chain for accession Q13838 downloaded
AlphaFold metadata for accession O00571 downloaded
AlphaFold chain for accession O00571 downloaded
AlphaFold metadata for accession Q7L014 downloaded
AlphaFold chain for accession Q7L014 downloaded
AlphaFold metadata for accession P17844 downloaded
AlphaFold chain for accession P17844 downloaded
AlphaFold metadata for accession Q8TDD1 downloaded
AlphaFold chain for accession Q8TDD1 downloaded
AlphaFold metadata for accession P35659 downloaded
AlphaFold chain for accession P35659 downloaded
AlphaFold metadata for accession P23743 downloaded
AlphaFold chain for accession P23743 downloaded
AlphaFold metadata for accession Q15392 downloaded
AlphaFold chain for accession Q15392 downloaded
AlphaFold metadata for accession Q9UBM7 downloaded
AlphaFold chain for accession Q9UBM7 downloaded
AlphaFold metadata for accession O43143 downloaded
AlphaFold chain for accession O43143 downloaded
AlphaFold metadata for accession O60231 downloaded
AlphaFold chain for accession O60231 downloaded
AlphaFold metadata for accession Q6P158 downloaded
AlphaFold chain for accession Q6P158 downloaded
AlphaFold metadata for accession Q08211 downloaded
AlphaFold chain for accession Q08211 downloaded
AlphaFold metadata for accession O60610 downloaded
AlphaFold chain for accession O60610 downloaded
AlphaFold metadata for accession Q9Y2L1 downloaded
AlphaFold chain for accession Q9Y2L1 downloaded
AlphaFold metadata for accession O60832 downloaded
AlphaFold chain for accession O60832 downloaded
AlphaFold metadata for accession Q96QB1 downloaded
AlphaFold chain for accession Q96QB1 downloaded
AlphaFold metadata for accession P36957 downloaded
AlphaFold chain for accession P36957 downloaded
AlphaFold metadata for accession Q96MX6 downloaded
AlphaFold chain for accession Q96MX6 downloaded
AlphaFold metadata for accession O60884 downloaded
AlphaFold chain for accession O60884 downloaded
AlphaFold metadata for accession P25685 downloaded
AlphaFold chain for accession P25685 downloaded
AlphaFold metadata for accession Q9UDY4 downloaded
AlphaFold chain for accession Q9UDY4 downloaded
AlphaFold metadata for accession O75953 downloaded
AlphaFold chain for accession O75953 downloaded
AlphaFold metadata for accession O75165 downloaded
AlphaFold chain for accession O75165 downloaded
AlphaFold metadata for accession O00429 downloaded
AlphaFold chain for accession O00429 downloaded
AlphaFold metadata for accession Q96BY6 downloaded
AlphaFold chain for accession Q96BY6 downloaded
AlphaFold metadata for accession Q96N67 downloaded
AlphaFold chain for accession Q96N67 downloaded
AlphaFold metadata for accession Q9BZ29 downloaded
AlphaFold chain for accession Q9BZ29 downloaded
AlphaFold metadata for accession Q9NY33 downloaded
AlphaFold chain for accession Q9NY33 downloaded
AlphaFold metadata for accession Q16555 downloaded
AlphaFold chain for accession Q16555 downloaded
AlphaFold metadata for accession Q01658 downloaded
AlphaFold chain for accession Q01658 downloaded
AlphaFold metadata for accession Q9Y295 downloaded
AlphaFold chain for accession Q9Y295 downloaded
AlphaFold metadata for accession Q9NRR4 downloaded
AlphaFold chain for accession Q9NRR4 downloaded
AlphaFold metadata for accession Q14126 downloaded
AlphaFold chain for accession Q14126 downloaded
AlphaFold metadata for accession P15924 downloaded
No AlphaFold model with same sequence length as UniProt for accession P15924
Impossible to retrieve pdb data for accession P15924
AlphaFold metadata for accession Q03001 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q03001
Impossible to retrieve pdb data for accession Q03001
AlphaFold metadata for accession P60981 downloaded
AlphaFold chain for accession P60981 downloaded
AlphaFold metadata for accession P33316 downloaded
AlphaFold chain for accession P33316 downloaded
AlphaFold metadata for accession Q7RTS9 downloaded
AlphaFold chain for accession Q7RTS9 downloaded
Impossible to retrieve AlphaFold metadata for accession Q14204
Impossible to retrieve pdb data for accession Q14204
AlphaFold metadata for accession P63167 downloaded
AlphaFold chain for accession P63167 downloaded
AlphaFold metadata for accession Q96FJ2 downloaded
AlphaFold chain for accession Q96FJ2 downloaded
AlphaFold metadata for accession O75923 downloaded
AlphaFold chain for accession O75923 downloaded
AlphaFold metadata for accession O95905 downloaded
AlphaFold chain for accession O95905 downloaded
AlphaFold metadata for accession Q13011 downloaded
AlphaFold chain for accession Q13011 downloaded
AlphaFold metadata for accession P30084 downloaded
AlphaFold chain for accession P30084 downloaded
AlphaFold metadata for accession O75521 downloaded
AlphaFold chain for accession O75521 downloaded
AlphaFold metadata for accession Q5VYK3 downloaded
AlphaFold chain for accession Q5VYK3 downloaded
AlphaFold metadata for accession Q6P2E9 downloaded
AlphaFold chain for accession Q6P2E9 downloaded
AlphaFold metadata for accession Q15075 downloaded
AlphaFold chain for accession Q15075 downloaded
AlphaFold metadata for accession O75530 downloaded
AlphaFold chain for accession O75530 downloaded
AlphaFold metadata for accession P68104 downloaded
AlphaFold chain for accession P68104 downloaded
AlphaFold metadata for accession P29692 downloaded
AlphaFold chain for accession P29692 downloaded
AlphaFold metadata for accession P13639 downloaded
AlphaFold chain for accession P13639 downloaded
AlphaFold metadata for accession Q7Z2Z2 downloaded
AlphaFold chain for accession Q7Z2Z2 downloaded
AlphaFold metadata for accession Q15029 downloaded
AlphaFold chain for accession Q15029 downloaded
AlphaFold metadata for accession Q9BY44 downloaded
AlphaFold chain for accession Q9BY44 downloaded
AlphaFold metadata for accession P05198 downloaded
AlphaFold chain for accession P05198 downloaded
AlphaFold metadata for accession P20042 downloaded
AlphaFold chain for accession P20042 downloaded
AlphaFold metadata for accession Q14152 downloaded
AlphaFold chain for accession Q14152 downloaded
AlphaFold metadata for accession P55884 downloaded
AlphaFold chain for accession P55884 downloaded
AlphaFold metadata for accession O15371 downloaded
AlphaFold chain for accession O15371 downloaded
AlphaFold metadata for accession O00303 downloaded
AlphaFold chain for accession O00303 downloaded
AlphaFold metadata for accession O75821 downloaded
AlphaFold chain for accession O75821 downloaded
AlphaFold metadata for accession O75822 downloaded
AlphaFold chain for accession O75822 downloaded
AlphaFold metadata for accession Q7L2H7 downloaded
AlphaFold chain for accession Q7L2H7 downloaded
AlphaFold metadata for accession Q04637 downloaded
AlphaFold chain for accession Q04637 downloaded
AlphaFold metadata for accession Q15056 downloaded
AlphaFold chain for accession Q15056 downloaded
AlphaFold metadata for accession Q9BQ52 downloaded
AlphaFold chain for accession Q9BQ52 downloaded
AlphaFold metadata for accession O95163 downloaded
AlphaFold chain for accession O95163 downloaded
AlphaFold metadata for accession Q9BV81 downloaded
AlphaFold chain for accession Q9BV81 downloaded
AlphaFold metadata for accession Q9HC35 downloaded
AlphaFold chain for accession Q9HC35 downloaded
AlphaFold metadata for accession O14682 downloaded
AlphaFold chain for accession O14682 downloaded
AlphaFold metadata for accession O94919 downloaded

AlphaFold chain for accession O94919 downloaded
AlphaFold metadata for accession P06733 downloaded
AlphaFold chain for accession P06733 downloaded
AlphaFold metadata for accession P09104 downloaded
AlphaFold chain for accession P09104 downloaded
AlphaFold metadata for accession P29317 downloaded
AlphaFold chain for accession P29317 downloaded
AlphaFold metadata for accession P07814 downloaded
AlphaFold chain for accession P07814 downloaded
AlphaFold metadata for accession P07992 downloaded
AlphaFold chain for accession P07992 downloaded
AlphaFold metadata for accession P84090 downloaded
AlphaFold chain for accession P84090 downloaded
AlphaFold metadata for accession O94905 downloaded
AlphaFold chain for accession O94905 downloaded
AlphaFold metadata for accession Q96HE7 downloaded
AlphaFold chain for accession Q96HE7 downloaded
AlphaFold metadata for accession P10768 downloaded
AlphaFold chain for accession P10768 downloaded
AlphaFold metadata for accession Q9BSJ8 downloaded
AlphaFold chain for accession Q9BSJ8 downloaded
AlphaFold metadata for accession P62495 downloaded
AlphaFold chain for accession P62495 downloaded
AlphaFold metadata for accession O95571 downloaded
AlphaFold chain for accession O95571 downloaded
AlphaFold metadata for accession Q01844 downloaded
AlphaFold chain for accession Q01844 downloaded
AlphaFold metadata for accession Q96A65 downloaded
AlphaFold chain for accession Q96A65 downloaded
AlphaFold metadata for accession O00471 downloaded
AlphaFold chain for accession O00471 downloaded
AlphaFold metadata for accession Q01780 downloaded
AlphaFold chain for accession Q01780 downloaded
AlphaFold metadata for accession Q13868 downloaded
AlphaFold chain for accession Q13868 downloaded
AlphaFold metadata for accession Q5RKV6 downloaded
AlphaFold chain for accession Q5RKV6 downloaded
AlphaFold metadata for accession Q15024 downloaded
AlphaFold chain for accession Q15024 downloaded
AlphaFold metadata for accession P13726 downloaded
AlphaFold chain for accession P13726 downloaded
AlphaFold metadata for accession Q01469 downloaded
AlphaFold chain for accession Q01469 downloaded
AlphaFold metadata for accession Q13158 downloaded
AlphaFold chain for accession Q13158 downloaded
AlphaFold metadata for accession Q96CS3 downloaded
AlphaFold chain for accession Q96CS3 downloaded
AlphaFold metadata for accession P16930 downloaded
AlphaFold chain for accession P16930 downloaded
AlphaFold metadata for accession Q6P587 downloaded
AlphaFold chain for accession Q6P587 downloaded
AlphaFold metadata for accession Q8IWE2 downloaded
AlphaFold chain for accession Q8IWE2 downloaded
AlphaFold metadata for accession Q9H4H8 downloaded
AlphaFold chain for accession Q9H4H8 downloaded
AlphaFold metadata for accession Q658Y4 downloaded
AlphaFold chain for accession Q658Y4 downloaded
AlphaFold metadata for accession Q52LJ0 downloaded
AlphaFold chain for accession Q52LJ0 downloaded
AlphaFold metadata for accession P49327 downloaded
AlphaFold chain for accession P49327 downloaded
AlphaFold metadata for accession Q8WUP2 downloaded
AlphaFold chain for accession Q8WUP2 downloaded
Impossible to retrieve AlphaFold metadata for accession P35555
Impossible to retrieve pdb data for accession P35555
AlphaFold metadata for accession Q96ME1 downloaded
AlphaFold chain for accession Q96ME1 downloaded
AlphaFold metadata for accession Q8TB52 downloaded
AlphaFold chain for accession Q8TB52 downloaded
AlphaFold metadata for accession Q8N3Y1 downloaded
AlphaFold chain for accession Q8N3Y1 downloaded
AlphaFold metadata for accession P37268 downloaded
AlphaFold chain for accession P37268 downloaded
AlphaFold metadata for accession P22830 downloaded
AlphaFold chain for accession P22830 downloaded
AlphaFold metadata for accession Q96AC1 downloaded
AlphaFold chain for accession Q96AC1 downloaded
AlphaFold metadata for accession P09038 downloaded
AlphaFold chain for accession P09038 downloaded
AlphaFold metadata for accession P07954 downloaded
AlphaFold chain for accession P07954 downloaded
AlphaFold metadata for accession Q5W0V3 downloaded
AlphaFold chain for accession Q5W0V3 downloaded
AlphaFold metadata for accession Q14192 downloaded
AlphaFold chain for accession Q14192 downloaded
AlphaFold metadata for accession Q02790 downloaded
AlphaFold chain for accession Q02790 downloaded
AlphaFold metadata for accession Q14318 downloaded
AlphaFold chain for accession Q14318 downloaded
AlphaFold metadata for accession Q13045 downloaded
AlphaFold chain for accession Q13045 downloaded
AlphaFold metadata for accession P21333 downloaded
AlphaFold chain for accession P21333 downloaded
AlphaFold metadata for accession O75369 downloaded
AlphaFold chain for accession O75369 downloaded
AlphaFold metadata for accession Q14315 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q14315
Impossible to retrieve pdb data for accession Q14315
AlphaFold metadata for accession P02751 downloaded
AlphaFold chain for accession P02751 downloaded
AlphaFold metadata for accession Q96RU3 downloaded
AlphaFold chain for accession Q96RU3 downloaded
AlphaFold metadata for accession Q53EP0 downloaded
AlphaFold chain for accession Q53EP0 downloaded
AlphaFold metadata for accession Q16658 downloaded
AlphaFold chain for accession Q16658 downloaded
AlphaFold metadata for accession Q9BTV5 downloaded
AlphaFold chain for accession Q9BTV5 downloaded
AlphaFold metadata for accession Q9C0B1 downloaded
AlphaFold chain for accession Q9C0B1 downloaded
AlphaFold metadata for accession Q8IY81 downloaded
AlphaFold chain for accession Q8IY81 downloaded
AlphaFold metadata for accession Q96AE4 downloaded
AlphaFold chain for accession Q96AE4 downloaded
AlphaFold metadata for accession Q96I24 downloaded
AlphaFold chain for accession Q96I24 downloaded
AlphaFold metadata for accession P35637 downloaded
AlphaFold chain for accession P35637 downloaded
AlphaFold metadata for accession P51114 downloaded
AlphaFold chain for accession P51114 downloaded
AlphaFold metadata for accession P11413 downloaded
AlphaFold chain for accession P11413 downloaded
AlphaFold metadata for accession Q06546 downloaded
AlphaFold chain for accession Q06546 downloaded
AlphaFold metadata for accession Q8TAE8 downloaded
AlphaFold chain for accession Q8TAE8 downloaded
AlphaFold metadata for accession Q14376 downloaded
AlphaFold chain for accession Q14376 downloaded
AlphaFold metadata for accession Q14697 downloaded
AlphaFold chain for accession Q14697 downloaded
AlphaFold metadata for accession P04406 downloaded
AlphaFold chain for accession P04406 downloaded
AlphaFold metadata for accession Q14C86 downloaded
AlphaFold chain for accession Q14C86 downloaded
AlphaFold metadata for accession P41250 downloaded
AlphaFold chain for accession P41250 downloaded
AlphaFold metadata for accession P22102 downloaded
AlphaFold chain for accession P22102 downloaded
AlphaFold metadata for accession P50440 downloaded
AlphaFold chain for accession P50440 downloaded
AlphaFold metadata for accession Q9HCG7 downloaded
AlphaFold chain for accession Q9HCG7 downloaded
AlphaFold metadata for accession Q04446 downloaded
AlphaFold chain for accession Q04446 downloaded
AlphaFold metadata for accession Q92538 downloaded
AlphaFold chain for accession Q92538 downloaded
AlphaFold metadata for accession Q92616 downloaded
AlphaFold chain for accession Q92616 downloaded
AlphaFold metadata for accession P23434 downloaded
AlphaFold chain for accession P23434 downloaded
AlphaFold metadata for accession P50395 downloaded
AlphaFold chain for accession P50395 downloaded
AlphaFold metadata for accession Q8TEQ6 downloaded
AlphaFold chain for accession Q8TEQ6 downloaded
AlphaFold metadata for accession Q06210 downloaded
AlphaFold chain for accession Q06210 downloaded
AlphaFold metadata for accession O94808 downloaded
AlphaFold chain for accession O94808 downloaded
AlphaFold metadata for accession Q13630 downloaded
AlphaFold chain for accession Q13630 downloaded
AlphaFold metadata for accession Q9Y2X7 downloaded
AlphaFold chain for accession Q9Y2X7 downloaded
AlphaFold metadata for accession Q92896 downloaded
AlphaFold chain for accession Q92896 downloaded
AlphaFold metadata for accession Q04760 downloaded

AlphaFold chain for accession Q04760 downloaded
AlphaFold metadata for accession P35754 downloaded
AlphaFold chain for accession P35754 downloaded
AlphaFold metadata for accession Q9NZD2 downloaded
AlphaFold chain for accession Q9NZD2 downloaded
AlphaFold metadata for accession P00367 downloaded
AlphaFold chain for accession P00367 downloaded
AlphaFold metadata for accession P36959 downloaded
AlphaFold chain for accession P36959 downloaded
AlphaFold metadata for accession Q9P2T1 downloaded
AlphaFold chain for accession Q9P2T1 downloaded
AlphaFold metadata for accession P49915 downloaded
AlphaFold chain for accession P49915 downloaded
AlphaFold metadata for accession P29992 downloaded
AlphaFold chain for accession P29992 downloaded
AlphaFold metadata for accession P63096 downloaded
AlphaFold chain for accession P63096 downloaded
AlphaFold metadata for accession P04899 downloaded
AlphaFold chain for accession P04899 downloaded
AlphaFold metadata for accession P08754 downloaded
AlphaFold chain for accession P08754 downloaded
AlphaFold metadata for accession P50148 downloaded
AlphaFold chain for accession P50148 downloaded
AlphaFold metadata for accession Q5JWF2 downloaded
AlphaFold chain for accession Q5JWF2 downloaded
AlphaFold metadata for accession P62873 downloaded
AlphaFold chain for accession P62873 downloaded
AlphaFold metadata for accession P62879 downloaded
AlphaFold chain for accession P62879 downloaded
AlphaFold metadata for accession Q9HAV0 downloaded
AlphaFold chain for accession Q9HAV0 downloaded
AlphaFold metadata for accession Q9UBI6 downloaded
AlphaFold chain for accession Q9UBI6 downloaded
AlphaFold metadata for accession P36915 downloaded
AlphaFold chain for accession P36915 downloaded
AlphaFold metadata for accession Q9BVP2 downloaded
AlphaFold chain for accession Q9BVP2 downloaded
AlphaFold metadata for accession Q9NVN8 downloaded
AlphaFold chain for accession Q9NVN8 downloaded
AlphaFold metadata for accession O15228 downloaded
AlphaFold chain for accession O15228 downloaded
AlphaFold metadata for accession Q13439 downloaded
AlphaFold chain for accession Q13439 downloaded
AlphaFold metadata for accession Q9H8Y8 downloaded
AlphaFold chain for accession Q9H8Y8 downloaded
AlphaFold metadata for accession P00505 downloaded
AlphaFold chain for accession P00505 downloaded
AlphaFold metadata for accession P43304 downloaded
AlphaFold chain for accession P43304 downloaded
AlphaFold metadata for accession Q13098 downloaded
AlphaFold chain for accession Q13098 downloaded
AlphaFold metadata for accession P49841 downloaded
AlphaFold chain for accession P49841 downloaded
AlphaFold metadata for accession P15170 downloaded
AlphaFold chain for accession P15170 downloaded
AlphaFold metadata for accession Q8IYD1 downloaded
AlphaFold chain for accession Q8IYD1 downloaded
AlphaFold metadata for accession P28161 downloaded
AlphaFold chain for accession P28161 downloaded
AlphaFold metadata for accession P78417 downloaded
AlphaFold chain for accession P78417 downloaded
AlphaFold metadata for accession P09211 downloaded
AlphaFold chain for accession P09211 downloaded
AlphaFold metadata for accession Q9Y5Q9 downloaded
AlphaFold chain for accession Q9Y5Q9 downloaded
AlphaFold metadata for accession Q4G148 downloaded
AlphaFold chain for accession Q4G148 downloaded
AlphaFold metadata for accession P40939 downloaded
AlphaFold chain for accession P40939 downloaded
AlphaFold metadata for accession Q16775 downloaded
AlphaFold chain for accession Q16775 downloaded
AlphaFold metadata for accession P12081 downloaded
AlphaFold chain for accession P12081 downloaded
AlphaFold metadata for accession O14929 downloaded
AlphaFold chain for accession O14929 downloaded
AlphaFold metadata for accession Q9Y450 downloaded
AlphaFold chain for accession Q9Y450 downloaded
AlphaFold metadata for accession P51610 downloaded
AlphaFold chain for accession P51610 downloaded
AlphaFold metadata for accession P51858 downloaded
AlphaFold chain for accession P51858 downloaded
AlphaFold metadata for accession Q7Z4V5 downloaded
AlphaFold chain for accession Q7Z4V5 downloaded
AlphaFold metadata for accession Q9H583 downloaded
AlphaFold chain for accession Q9H583 downloaded
AlphaFold metadata for accession Q7Z4Q2 downloaded
AlphaFold chain for accession Q7Z4Q2 downloaded
AlphaFold metadata for accession Q9ULT8 downloaded
AlphaFold chain for accession Q9ULT8 downloaded
AlphaFold metadata for accession O14964 downloaded
AlphaFold chain for accession O14964 downloaded
AlphaFold metadata for accession P49773 downloaded
AlphaFold chain for accession P49773 downloaded
AlphaFold metadata for accession P19367 downloaded
AlphaFold chain for accession P19367 downloaded
AlphaFold metadata for accession P52789 downloaded
AlphaFold chain for accession P52789 downloaded
AlphaFold metadata for accession P01889 downloaded
AlphaFold chain for accession P01889 downloaded
AlphaFold metadata for accession P35914 downloaded
AlphaFold chain for accession P35914 downloaded
AlphaFold metadata for accession P30519 downloaded
AlphaFold chain for accession P30519 downloaded
AlphaFold metadata for accession P09651 downloaded
AlphaFold chain for accession P09651 downloaded
AlphaFold metadata for accession P22626 downloaded
AlphaFold chain for accession P22626 downloaded
AlphaFold metadata for accession P51991 downloaded
AlphaFold chain for accession P51991 downloaded
AlphaFold metadata for accession O14979 downloaded
AlphaFold chain for accession O14979 downloaded
AlphaFold metadata for accession P52597 downloaded
AlphaFold chain for accession P52597 downloaded
AlphaFold metadata for accession P31943 downloaded
AlphaFold chain for accession P31943 downloaded
AlphaFold metadata for accession P55795 downloaded
AlphaFold chain for accession P55795 downloaded
AlphaFold metadata for accession P61978 downloaded
AlphaFold chain for accession P61978 downloaded
AlphaFold metadata for accession Q00839 downloaded
AlphaFold chain for accession Q00839 downloaded
AlphaFold metadata for accession Q9BUJ2 downloaded
AlphaFold chain for accession Q9BUJ2 downloaded
AlphaFold metadata for accession Q1KMD3 downloaded
AlphaFold chain for accession Q1KMD3 downloaded
AlphaFold metadata for accession Q96ED9 downloaded
AlphaFold chain for accession Q96ED9 downloaded
AlphaFold metadata for accession P00492 downloaded
AlphaFold chain for accession P00492 downloaded
AlphaFold metadata for accession Q969F9 downloaded
AlphaFold chain for accession Q969F9 downloaded
AlphaFold metadata for accession Q6YN16 downloaded
AlphaFold chain for accession Q6YN16 downloaded
AlphaFold metadata for accession P07900 downloaded
AlphaFold chain for accession P07900 downloaded
AlphaFold metadata for accession P34932 downloaded
AlphaFold chain for accession P34932 downloaded
AlphaFold metadata for accession O95757 downloaded
AlphaFold chain for accession O95757 downloaded
AlphaFold metadata for accession P17066 downloaded
AlphaFold chain for accession P17066 downloaded
AlphaFold metadata for accession P11142 downloaded
AlphaFold chain for accession P11142 downloaded
AlphaFold metadata for accession P38646 downloaded
AlphaFold chain for accession P38646 downloaded
AlphaFold metadata for accession P10809 downloaded
AlphaFold chain for accession P10809 downloaded
AlphaFold metadata for accession Q92598 downloaded
AlphaFold chain for accession Q92598 downloaded
Impossible to retrieve AlphaFold metadata for accession P42858
Impossible to retrieve pdb data for accession P42858
Impossible to retrieve AlphaFold metadata for accession Q7Z6Z7
Impossible to retrieve pdb data for accession Q7Z6Z7
AlphaFold metadata for accession Q9Y4L1 downloaded
AlphaFold chain for accession Q9Y4L1 downloaded
AlphaFold metadata for accession P41252 downloaded
AlphaFold chain for accession P41252 downloaded
AlphaFold metadata for accession O75874 downloaded
AlphaFold chain for accession O75874 downloaded
AlphaFold metadata for accession P48735 downloaded
AlphaFold chain for accession P48735 downloaded
AlphaFold metadata for accession P50213 downloaded
AlphaFold chain for accession P50213 downloaded
AlphaFold metadata for accession O43837 downloaded
AlphaFold chain for accession O43837 downloaded
AlphaFold metadata for accession Q13907 downloaded

AlphaFold chain for accession Q13907 downloaded
AlphaFold metadata for accession O14879 downloaded
AlphaFold chain for accession O14879 downloaded
AlphaFold metadata for accession Q13325 downloaded
AlphaFold chain for accession Q13325 downloaded
AlphaFold metadata for accession Q9NZI8 downloaded
AlphaFold chain for accession Q9NZI8 downloaded
AlphaFold metadata for accession Q9Y6M1 downloaded
AlphaFold chain for accession Q9Y6M1 downloaded
AlphaFold metadata for accession O00425 downloaded
AlphaFold chain for accession O00425 downloaded
AlphaFold metadata for accession Q16270 downloaded
AlphaFold chain for accession Q16270 downloaded
AlphaFold metadata for accession Q13418 downloaded
AlphaFold chain for accession Q13418 downloaded
AlphaFold metadata for accession Q9H0C8 downloaded
AlphaFold chain for accession Q9H0C8 downloaded
AlphaFold metadata for accession Q16891 downloaded
AlphaFold chain for accession Q16891 downloaded
AlphaFold metadata for accession Q27J81 downloaded
AlphaFold chain for accession Q27J81 downloaded
AlphaFold metadata for accession O15357 downloaded
AlphaFold chain for accession O15357 downloaded
AlphaFold metadata for accession Q9NVM9 downloaded
AlphaFold chain for accession Q9NVM9 downloaded
AlphaFold metadata for accession Q8TEX9 downloaded
AlphaFold chain for accession Q8TEX9 downloaded
AlphaFold metadata for accession O00410 downloaded
AlphaFold chain for accession O00410 downloaded
AlphaFold metadata for accession O95373 downloaded
AlphaFold chain for accession O95373 downloaded
AlphaFold metadata for accession P46940 downloaded
AlphaFold chain for accession P46940 downloaded
AlphaFold metadata for accession Q86VI3 downloaded
AlphaFold chain for accession Q86VI3 downloaded
AlphaFold metadata for accession Q8IU81 downloaded
AlphaFold chain for accession Q8IU81 downloaded
AlphaFold metadata for accession Q9H1B7 downloaded
AlphaFold chain for accession Q9H1B7 downloaded
AlphaFold metadata for accession P53990 downloaded
AlphaFold chain for accession P53990 downloaded
AlphaFold metadata for accession Q9UKX5 downloaded
AlphaFold chain for accession Q9UKX5 downloaded
AlphaFold metadata for accession P17301 downloaded
AlphaFold chain for accession P17301 downloaded
AlphaFold metadata for accession P26006 downloaded
AlphaFold chain for accession P26006 downloaded
AlphaFold metadata for accession P23229 downloaded
AlphaFold chain for accession P23229 downloaded
AlphaFold metadata for accession P05556 downloaded
AlphaFold chain for accession P05556 downloaded
AlphaFold metadata for accession Q9BY32 downloaded
AlphaFold chain for accession Q9BY32 downloaded
AlphaFold metadata for accession Q15811 downloaded
AlphaFold chain for accession Q15811 downloaded
AlphaFold metadata for accession P26440 downloaded
AlphaFold chain for accession P26440 downloaded
AlphaFold metadata for accession P23458 downloaded
AlphaFold chain for accession P23458 downloaded
AlphaFold metadata for accession Q63ZY3 downloaded
AlphaFold chain for accession Q63ZY3 downloaded
AlphaFold metadata for accession Q7L273 downloaded
AlphaFold chain for accession Q7L273 downloaded
AlphaFold metadata for accession P41229 downloaded
AlphaFold chain for accession P41229 downloaded
AlphaFold metadata for accession Q06136 downloaded
AlphaFold chain for accession Q06136 downloaded
AlphaFold metadata for accession P50053 downloaded
AlphaFold chain for accession P50053 downloaded
AlphaFold metadata for accession Q92945 downloaded
AlphaFold chain for accession Q92945 downloaded
AlphaFold metadata for accession Q8IYS2 downloaded
AlphaFold chain for accession Q8IYS2 downloaded
AlphaFold metadata for accession Q02241 downloaded
AlphaFold chain for accession Q02241 downloaded
AlphaFold metadata for accession Q9BW19 downloaded
AlphaFold chain for accession Q9BW19 downloaded
AlphaFold metadata for accession Q07866 downloaded
AlphaFold chain for accession Q07866 downloaded
AlphaFold metadata for accession Q9NSK0 downloaded
AlphaFold chain for accession Q9NSK0 downloaded
AlphaFold metadata for accession P52294 downloaded
AlphaFold chain for accession P52294 downloaded
AlphaFold metadata for accession O00629 downloaded
AlphaFold chain for accession O00629 downloaded
AlphaFold metadata for accession O15131 downloaded
AlphaFold chain for accession O15131 downloaded
AlphaFold metadata for accession Q14974 downloaded
AlphaFold chain for accession Q14974 downloaded
AlphaFold metadata for accession Q86UP2 downloaded
AlphaFold chain for accession Q86UP2 downloaded
AlphaFold metadata for accession Q9UN81 downloaded
AlphaFold chain for accession Q9UN81 downloaded
AlphaFold metadata for accession Q9Y2Q5 downloaded
AlphaFold chain for accession Q9Y2Q5 downloaded
AlphaFold metadata for accession P28838 downloaded
AlphaFold chain for accession P28838 downloaded
AlphaFold metadata for accession Q9P2J5 downloaded
AlphaFold chain for accession Q9P2J5 downloaded
AlphaFold metadata for accession Q9Y4W2 downloaded
AlphaFold chain for accession Q9Y4W2 downloaded
AlphaFold metadata for accession Q14847 downloaded
AlphaFold chain for accession Q14847 downloaded
AlphaFold metadata for accession P00338 downloaded
AlphaFold chain for accession P00338 downloaded
AlphaFold metadata for accession O95202 downloaded
AlphaFold chain for accession O95202 downloaded
AlphaFold metadata for accession P09382 downloaded
AlphaFold chain for accession P09382 downloaded
AlphaFold metadata for accession Q9UGP4 downloaded
AlphaFold chain for accession Q9UGP4 downloaded
AlphaFold metadata for accession P48059 downloaded
AlphaFold chain for accession P48059 downloaded
AlphaFold metadata for accession Q9NUP9 downloaded
AlphaFold chain for accession Q9NUP9 downloaded
AlphaFold metadata for accession P02545 downloaded
AlphaFold chain for accession P02545 downloaded
AlphaFold metadata for accession Q8WWI1 downloaded
AlphaFold chain for accession Q8WWI1 downloaded
AlphaFold metadata for accession P36776 downloaded
AlphaFold chain for accession P36776 downloaded
AlphaFold metadata for accession P28300 downloaded
AlphaFold chain for accession P28300 downloaded
AlphaFold metadata for accession Q8NF37 downloaded
AlphaFold chain for accession Q8NF37 downloaded
AlphaFold metadata for accession Q7L5N7 downloaded
AlphaFold chain for accession Q7L5N7 downloaded
Impossible to retrieve AlphaFold metadata for accession P50851
Impossible to retrieve pdb data for accession P50851
AlphaFold metadata for accession Q96II8 downloaded
AlphaFold chain for accession Q96II8 downloaded
AlphaFold metadata for accession Q07954 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q07954
Impossible to retrieve pdb data for accession Q07954
AlphaFold metadata for accession P42704 downloaded
AlphaFold chain for accession P42704 downloaded
AlphaFold metadata for accession Q15345 downloaded
AlphaFold chain for accession Q15345 downloaded
AlphaFold metadata for accession Q96AG4 downloaded
AlphaFold chain for accession Q96AG4 downloaded
AlphaFold metadata for accession Q3MHD2 downloaded
AlphaFold chain for accession Q3MHD2 downloaded
AlphaFold metadata for accession P48449 downloaded
AlphaFold chain for accession P48449 downloaded
AlphaFold metadata for accession Q9Y383 downloaded
AlphaFold chain for accession Q9Y383 downloaded
AlphaFold metadata for accession P20645 downloaded
AlphaFold chain for accession P20645 downloaded
Impossible to retrieve AlphaFold metadata for accession Q9UPN3
Impossible to retrieve pdb data for accession Q9UPN3
AlphaFold metadata for accession O75367 downloaded
AlphaFold chain for accession O75367 downloaded
AlphaFold metadata for accession Q9BXY0 downloaded
AlphaFold chain for accession Q9BXY0 downloaded
AlphaFold metadata for accession O00462 downloaded
AlphaFold chain for accession O00462 downloaded
AlphaFold metadata for accession P55145 downloaded
AlphaFold chain for accession P55145 downloaded
Impossible to retrieve AlphaFold metadata for accession P78559
Impossible to retrieve pdb data for accession P78559
AlphaFold metadata for accession P46821 downloaded
AlphaFold chain for accession P46821 downloaded
AlphaFold metadata for accession Q66K74 downloaded
AlphaFold chain for accession Q66K74 downloaded
AlphaFold metadata for accession Q9NYL2 downloaded

AlphaFold chain for accession Q9NYL2 downloaded
AlphaFold metadata for accession P31153 downloaded
AlphaFold chain for accession P31153 downloaded
AlphaFold metadata for accession Q9NZL9 downloaded
AlphaFold chain for accession Q9NZL9 downloaded
AlphaFold metadata for accession P43243 downloaded
AlphaFold chain for accession P43243 downloaded
AlphaFold metadata for accession Q68D91 downloaded
AlphaFold chain for accession Q68D91 downloaded
AlphaFold metadata for accession Q9NR56 downloaded
AlphaFold chain for accession Q9NR56 downloaded
AlphaFold metadata for accession Q9HCC0 downloaded
AlphaFold chain for accession Q9HCC0 downloaded
AlphaFold metadata for accession P49736 downloaded
AlphaFold chain for accession P49736 downloaded
AlphaFold metadata for accession P25205 downloaded
AlphaFold chain for accession P25205 downloaded
AlphaFold metadata for accession Q14566 downloaded
AlphaFold chain for accession Q14566 downloaded
AlphaFold metadata for accession P33993 downloaded
AlphaFold chain for accession P33993 downloaded
AlphaFold metadata for accession Q9ULC4 downloaded
AlphaFold chain for accession Q9ULC4 downloaded
AlphaFold metadata for accession P40925 downloaded
AlphaFold chain for accession P40925 downloaded
AlphaFold metadata for accession P40926 downloaded
AlphaFold chain for accession P40926 downloaded
AlphaFold metadata for accession O60244 downloaded
AlphaFold chain for accession O60244 downloaded
AlphaFold metadata for accession Q9H204 downloaded
AlphaFold chain for accession Q9H204 downloaded
AlphaFold metadata for accession Q9Y3C7 downloaded
AlphaFold chain for accession Q9Y3C7 downloaded
AlphaFold metadata for accession Q5JRA6 downloaded
AlphaFold chain for accession Q5JRA6 downloaded
AlphaFold metadata for accession P14174 downloaded
AlphaFold chain for accession P14174 downloaded
AlphaFold metadata for accession Q99797 downloaded
AlphaFold chain for accession Q99797 downloaded
AlphaFold metadata for accession Q4VC31 downloaded
AlphaFold chain for accession Q4VC31 downloaded
Impossible to retrieve AlphaFold metadata for accession P46013
Impossible to retrieve pdb data for accession P46013
AlphaFold metadata for accession P40692 downloaded
AlphaFold chain for accession P40692 downloaded
AlphaFold metadata for accession Q8NB16 downloaded
AlphaFold chain for accession Q8NB16 downloaded
AlphaFold metadata for accession Q96T76 downloaded
AlphaFold chain for accession Q96T76 downloaded
AlphaFold metadata for accession Q9BU76 downloaded
AlphaFold chain for accession Q9BU76 downloaded
AlphaFold metadata for accession P22033 downloaded
AlphaFold chain for accession P22033 downloaded
AlphaFold metadata for accession Q9UBG0 downloaded
AlphaFold chain for accession Q9UBG0 downloaded
AlphaFold metadata for accession Q9HC36 downloaded
AlphaFold chain for accession Q9HC36 downloaded
AlphaFold metadata for accession Q5T653 downloaded
AlphaFold chain for accession Q5T653 downloaded
AlphaFold metadata for accession Q9BZE1 downloaded
AlphaFold chain for accession Q9BZE1 downloaded
AlphaFold metadata for accession Q9NYK5 downloaded
AlphaFold chain for accession Q9NYK5 downloaded
AlphaFold metadata for accession Q9Y6G3 downloaded
AlphaFold chain for accession Q9Y6G3 downloaded
AlphaFold metadata for accession Q9HD33 downloaded
AlphaFold chain for accession Q9HD33 downloaded
AlphaFold metadata for accession Q96EL3 downloaded
AlphaFold chain for accession Q96EL3 downloaded
AlphaFold metadata for accession Q14197 downloaded
AlphaFold chain for accession Q14197 downloaded
AlphaFold metadata for accession Q9NP92 downloaded
AlphaFold chain for accession Q9NP92 downloaded
AlphaFold metadata for accession P20585 downloaded
AlphaFold chain for accession P20585 downloaded
AlphaFold metadata for accession P52701 downloaded
AlphaFold chain for accession P52701 downloaded
AlphaFold metadata for accession P02795 downloaded
AlphaFold chain for accession P02795 downloaded
AlphaFold metadata for accession O94776 downloaded
AlphaFold chain for accession O94776 downloaded
AlphaFold metadata for accession Q13126 downloaded
AlphaFold chain for accession Q13126 downloaded
AlphaFold metadata for accession Q9NZJ7 downloaded
AlphaFold chain for accession Q9NZJ7 downloaded
AlphaFold metadata for accession P11586 downloaded
AlphaFold chain for accession P11586 downloaded
AlphaFold metadata for accession P42345 downloaded
AlphaFold chain for accession P42345 downloaded
AlphaFold metadata for accession P42285 downloaded
AlphaFold chain for accession P42285 downloaded
AlphaFold metadata for accession Q13505 downloaded
AlphaFold chain for accession Q13505 downloaded
AlphaFold metadata for accession Q969V5 downloaded
AlphaFold chain for accession Q969V5 downloaded
AlphaFold metadata for accession Q03426 downloaded
AlphaFold chain for accession Q03426 downloaded
AlphaFold metadata for accession Q14764 downloaded
AlphaFold chain for accession Q14764 downloaded
AlphaFold metadata for accession P35579 downloaded
AlphaFold chain for accession P35579 downloaded
AlphaFold metadata for accession O14950 downloaded
AlphaFold chain for accession O14950 downloaded
AlphaFold metadata for accession P14649 downloaded
AlphaFold chain for accession P14649 downloaded
AlphaFold metadata for accession P24844 downloaded
AlphaFold chain for accession P24844 downloaded
AlphaFold metadata for accession Q15746 downloaded
AlphaFold chain for accession Q15746 downloaded
AlphaFold metadata for accession Q9HD67 downloaded
AlphaFold chain for accession Q9HD67 downloaded
AlphaFold metadata for accession Q92614 downloaded
AlphaFold chain for accession Q92614 downloaded
AlphaFold metadata for accession O43795 downloaded
AlphaFold chain for accession O43795 downloaded
AlphaFold metadata for accession O00159 downloaded
AlphaFold chain for accession O00159 downloaded
AlphaFold metadata for accession Q9UM54 downloaded
AlphaFold chain for accession Q9UM54 downloaded
AlphaFold metadata for accession B2RTY4 downloaded
AlphaFold chain for accession B2RTY4 downloaded
AlphaFold metadata for accession Q9NZM1 downloaded
AlphaFold chain for accession Q9NZM1 downloaded
AlphaFold metadata for accession Q9BXJ9 downloaded
AlphaFold chain for accession Q9BXJ9 downloaded
AlphaFold metadata for accession P17050 downloaded
AlphaFold chain for accession P17050 downloaded
AlphaFold metadata for accession P43490 downloaded
AlphaFold chain for accession P43490 downloaded
AlphaFold metadata for accession P55209 downloaded
AlphaFold chain for accession P55209 downloaded
AlphaFold metadata for accession P54920 downloaded
AlphaFold chain for accession P54920 downloaded
AlphaFold metadata for accession Q9BPX3 downloaded
AlphaFold chain for accession Q9BPX3 downloaded
AlphaFold metadata for accession P19338 downloaded
AlphaFold chain for accession P19338 downloaded
AlphaFold metadata for accession Q9Y618 downloaded
AlphaFold chain for accession Q9Y618 downloaded
AlphaFold metadata for accession P49821 downloaded
AlphaFold chain for accession P49821 downloaded
AlphaFold metadata for accession Q9NVZ3 downloaded
AlphaFold chain for accession Q9NVZ3 downloaded
AlphaFold metadata for accession Q8TDX7 downloaded
AlphaFold chain for accession Q8TDX7 downloaded
AlphaFold metadata for accession Q8WX92 downloaded
AlphaFold chain for accession Q8WX92 downloaded
AlphaFold metadata for accession O14524 downloaded
AlphaFold chain for accession O14524 downloaded
AlphaFold metadata for accession Q0ZGT2 downloaded
AlphaFold chain for accession Q0ZGT2 downloaded
AlphaFold metadata for accession Q00653 downloaded
AlphaFold chain for accession Q00653 downloaded
AlphaFold metadata for accession Q96TA1 downloaded
AlphaFold chain for accession Q96TA1 downloaded
AlphaFold metadata for accession Q9BPW8 downloaded
AlphaFold chain for accession Q9BPW8 downloaded
AlphaFold metadata for accession Q9UFN0 downloaded
AlphaFold chain for accession Q9UFN0 downloaded
AlphaFold metadata for accession Q9NQR4 downloaded
AlphaFold chain for accession Q9NQR4 downloaded
AlphaFold metadata for accession Q9BYT8 downloaded
AlphaFold chain for accession Q9BYT8 downloaded
AlphaFold metadata for accession P15531 downloaded
AlphaFold chain for accession P15531 downloaded
AlphaFold metadata for accession Q9Y5B8 downloaded

AlphaFold chain for accession Q9Y5B8 downloaded
AlphaFold metadata for accession Q13423 downloaded
AlphaFold chain for accession Q13423 downloaded
AlphaFold metadata for accession Q9ULX3 downloaded
AlphaFold chain for accession Q9ULX3 downloaded
AlphaFold metadata for accession O60936 downloaded
AlphaFold chain for accession O60936 downloaded
AlphaFold metadata for accession Q9H6R4 downloaded
AlphaFold chain for accession Q9H6R4 downloaded
AlphaFold metadata for accession O00567 downloaded
AlphaFold chain for accession O00567 downloaded
AlphaFold metadata for accession O75607 downloaded
AlphaFold chain for accession O75607 downloaded
AlphaFold metadata for accession Q8WTW4 downloaded
AlphaFold chain for accession Q8WTW4 downloaded
AlphaFold metadata for accession P10589 downloaded
AlphaFold chain for accession P10589 downloaded
AlphaFold metadata for accession O95478 downloaded
AlphaFold chain for accession O95478 downloaded
AlphaFold metadata for accession Q15738 downloaded
AlphaFold chain for accession Q15738 downloaded
AlphaFold metadata for accession Q5TFE4 downloaded
AlphaFold chain for accession Q5TFE4 downloaded
AlphaFold metadata for accession P21589 downloaded
AlphaFold chain for accession P21589 downloaded
AlphaFold metadata for accession P53384 downloaded
AlphaFold chain for accession P53384 downloaded
AlphaFold metadata for accession Q96RS6 downloaded
AlphaFold chain for accession Q96RS6 downloaded
AlphaFold metadata for accession Q14980 downloaded
AlphaFold chain for accession Q14980 downloaded
AlphaFold metadata for accession O75694 downloaded
AlphaFold chain for accession O75694 downloaded
AlphaFold metadata for accession Q12769 downloaded
AlphaFold chain for accession Q12769 downloaded
AlphaFold metadata for accession Q5SRE5 downloaded
AlphaFold chain for accession Q5SRE5 downloaded
AlphaFold metadata for accession Q8NFH4 downloaded
AlphaFold chain for accession Q8NFH4 downloaded
AlphaFold metadata for accession Q99567 downloaded
AlphaFold chain for accession Q99567 downloaded
AlphaFold metadata for accession Q8N1F7 downloaded
AlphaFold chain for accession Q8N1F7 downloaded
AlphaFold metadata for accession P61970 downloaded
AlphaFold chain for accession P61970 downloaded
AlphaFold metadata for accession Q9NPJ8 downloaded
AlphaFold chain for accession Q9NPJ8 downloaded
AlphaFold metadata for accession P04181 downloaded
AlphaFold chain for accession P04181 downloaded
AlphaFold metadata for accession O75147 downloaded
AlphaFold chain for accession O75147 downloaded
AlphaFold metadata for accession Q5BJF6 downloaded
AlphaFold chain for accession Q5BJF6 downloaded
AlphaFold metadata for accession Q02218 downloaded
AlphaFold chain for accession Q02218 downloaded
AlphaFold metadata for accession O60890 downloaded
AlphaFold chain for accession O60890 downloaded
AlphaFold metadata for accession Q96CV9 downloaded
AlphaFold chain for accession Q96CV9 downloaded
AlphaFold metadata for accession Q9Y5N6 downloaded
AlphaFold chain for accession Q9Y5N6 downloaded
AlphaFold metadata for accession Q969R2 downloaded
AlphaFold chain for accession Q969R2 downloaded
AlphaFold metadata for accession Q9BZF1 downloaded
AlphaFold chain for accession Q9BZF1 downloaded
AlphaFold metadata for accession Q96FW1 downloaded
AlphaFold chain for accession Q96FW1 downloaded
AlphaFold metadata for accession Q32P28 downloaded
AlphaFold chain for accession Q32P28 downloaded
AlphaFold metadata for accession Q92791 downloaded
AlphaFold chain for accession Q92791 downloaded
AlphaFold metadata for accession P07237 downloaded
AlphaFold chain for accession P07237 downloaded
AlphaFold metadata for accession Q9UQ80 downloaded
AlphaFold chain for accession Q9UQ80 downloaded
AlphaFold metadata for accession Q13310 downloaded
AlphaFold chain for accession Q13310 downloaded
AlphaFold metadata for accession Q86U42 downloaded
AlphaFold chain for accession Q86U42 downloaded
AlphaFold metadata for accession Q9UNF0 downloaded
AlphaFold chain for accession Q9UNF0 downloaded
AlphaFold metadata for accession P43034 downloaded
AlphaFold chain for accession P43034 downloaded
AlphaFold metadata for accession Q15102 downloaded
AlphaFold chain for accession Q15102 downloaded
AlphaFold metadata for accession P22234 downloaded
AlphaFold chain for accession P22234 downloaded
AlphaFold metadata for accession Q13153 downloaded
AlphaFold chain for accession Q13153 downloaded
AlphaFold metadata for accession Q8WX93 downloaded
AlphaFold chain for accession Q8WX93 downloaded
AlphaFold metadata for accession Q15365 downloaded
AlphaFold chain for accession Q15365 downloaded
AlphaFold metadata for accession Q15366 downloaded
AlphaFold chain for accession Q15366 downloaded
AlphaFold metadata for accession P57721 downloaded
AlphaFold chain for accession P57721 downloaded
AlphaFold metadata for accession Q15154 downloaded
AlphaFold chain for accession Q15154 downloaded
AlphaFold metadata for accession P22061 downloaded
AlphaFold chain for accession P22061 downloaded
AlphaFold metadata for accession P12004 downloaded
AlphaFold chain for accession P12004 downloaded
AlphaFold metadata for accession Q14690 downloaded
AlphaFold chain for accession Q14690 downloaded
AlphaFold metadata for accession Q9BRP1 downloaded
AlphaFold chain for accession Q9BRP1 downloaded
AlphaFold metadata for accession Q8WUM4 downloaded
AlphaFold chain for accession Q8WUM4 downloaded
AlphaFold metadata for accession Q5VU43 downloaded
AlphaFold chain for accession Q5VU43 downloaded
AlphaFold metadata for accession P08559 downloaded
AlphaFold chain for accession P08559 downloaded
AlphaFold metadata for accession P30101 downloaded
AlphaFold chain for accession P30101 downloaded
AlphaFold metadata for accession O00151 downloaded
AlphaFold chain for accession O00151 downloaded
AlphaFold metadata for accession Q96HC4 downloaded
AlphaFold chain for accession Q96HC4 downloaded
AlphaFold metadata for accession Q86YH6 downloaded
AlphaFold chain for accession Q86YH6 downloaded
AlphaFold metadata for accession Q8NEN9 downloaded
AlphaFold chain for accession Q8NEN9 downloaded
AlphaFold metadata for accession P30086 downloaded
AlphaFold chain for accession P30086 downloaded
AlphaFold metadata for accession Q9BRX2 downloaded
AlphaFold chain for accession Q9BRX2 downloaded
AlphaFold metadata for accession P12955 downloaded
AlphaFold chain for accession P12955 downloaded
AlphaFold metadata for accession O00541 downloaded
AlphaFold chain for accession O00541 downloaded
AlphaFold metadata for accession P56589 downloaded
AlphaFold chain for accession P56589 downloaded
AlphaFold metadata for accession O15067 downloaded
AlphaFold chain for accession O15067 downloaded
AlphaFold metadata for accession Q99471 downloaded
AlphaFold chain for accession Q99471 downloaded
AlphaFold metadata for accession P08237 downloaded
AlphaFold chain for accession P08237 downloaded
AlphaFold metadata for accession Q01813 downloaded
AlphaFold chain for accession Q01813 downloaded
AlphaFold metadata for accession P07737 downloaded
AlphaFold chain for accession P07737 downloaded
AlphaFold metadata for accession P18669 downloaded
AlphaFold chain for accession P18669 downloaded
AlphaFold metadata for accession P52209 downloaded
AlphaFold chain for accession P52209 downloaded
AlphaFold metadata for accession P00558 downloaded
AlphaFold chain for accession P00558 downloaded
AlphaFold metadata for accession O95336 downloaded
AlphaFold chain for accession O95336 downloaded
AlphaFold metadata for accession Q6PCE3 downloaded
AlphaFold chain for accession Q6PCE3 downloaded
AlphaFold metadata for accession O95394 downloaded
AlphaFold chain for accession O95394 downloaded
AlphaFold metadata for accession Q8IXK0 downloaded
AlphaFold chain for accession Q8IXK0 downloaded
AlphaFold metadata for accession P46020 downloaded
AlphaFold chain for accession P46020 downloaded
AlphaFold metadata for accession P42336 downloaded
AlphaFold chain for accession P42336 downloaded
AlphaFold metadata for accession Q13526 downloaded
AlphaFold chain for accession Q13526 downloaded
AlphaFold metadata for accession P48739 downloaded
AlphaFold chain for accession P48739 downloaded
AlphaFold metadata for accession P14618 downloaded

AlphaFold chain for accession P14618 downloaded
AlphaFold metadata for accession Q9Y263 downloaded
AlphaFold chain for accession Q9Y263 downloaded
AlphaFold metadata for accession P00749 downloaded
AlphaFold chain for accession P00749 downloaded
AlphaFold metadata for accession Q01970 downloaded
AlphaFold chain for accession Q01970 downloaded
AlphaFold metadata for accession Q15147 downloaded
AlphaFold chain for accession Q15147 downloaded
Impossible to retrieve AlphaFold metadata for accession Q15149
Impossible to retrieve pdb data for accession Q15149
AlphaFold metadata for accession O60664 downloaded
AlphaFold chain for accession O60664 downloaded
AlphaFold metadata for accession Q02809 downloaded
AlphaFold chain for accession Q02809 downloaded
AlphaFold metadata for accession O00469 downloaded
AlphaFold chain for accession O00469 downloaded
AlphaFold metadata for accession O43660 downloaded
AlphaFold chain for accession O43660 downloaded
AlphaFold metadata for accession P13797 downloaded
AlphaFold chain for accession P13797 downloaded
AlphaFold metadata for accession Q8IYS1 downloaded
AlphaFold chain for accession Q8IYS1 downloaded
AlphaFold metadata for accession O75439 downloaded
AlphaFold chain for accession O75439 downloaded
AlphaFold metadata for accession P54278 downloaded
AlphaFold chain for accession P54278 downloaded
AlphaFold metadata for accession P00491 downloaded
AlphaFold chain for accession P00491 downloaded
AlphaFold metadata for accession Q8TCS8 downloaded
AlphaFold chain for accession Q8TCS8 downloaded
AlphaFold metadata for accession Q9H488 downloaded
AlphaFold chain for accession Q9H488 downloaded
AlphaFold metadata for accession P06746 downloaded
AlphaFold chain for accession P06746 downloaded
AlphaFold metadata for accession P28340 downloaded
AlphaFold chain for accession P28340 downloaded
AlphaFold metadata for accession Q9GZS1 downloaded
AlphaFold chain for accession Q9GZS1 downloaded
AlphaFold metadata for accession Q99575 downloaded
AlphaFold chain for accession Q99575 downloaded
AlphaFold metadata for accession P0CG39 downloaded
AlphaFold chain for accession P0CG39 downloaded
AlphaFold metadata for accession Q15181 downloaded
AlphaFold chain for accession Q15181 downloaded
AlphaFold metadata for accession Q9H2U2 downloaded
AlphaFold chain for accession Q9H2U2 downloaded
AlphaFold metadata for accession P62937 downloaded
AlphaFold chain for accession P62937 downloaded
AlphaFold metadata for accession P23284 downloaded
AlphaFold chain for accession P23284 downloaded
AlphaFold metadata for accession O43447 downloaded
AlphaFold chain for accession O43447 downloaded
AlphaFold metadata for accession Q9Y3C6 downloaded
AlphaFold chain for accession Q9Y3C6 downloaded
AlphaFold metadata for accession Q8IXY8 downloaded
AlphaFold chain for accession Q8IXY8 downloaded
AlphaFold metadata for accession Q6PFW1 downloaded
AlphaFold chain for accession Q6PFW1 downloaded
AlphaFold metadata for accession P62136 downloaded
AlphaFold chain for accession P62136 downloaded
AlphaFold metadata for accession O14974 downloaded
AlphaFold chain for accession O14974 downloaded
AlphaFold metadata for accession Q9BZL4 downloaded
AlphaFold chain for accession Q9BZL4 downloaded
AlphaFold metadata for accession Q96C90 downloaded
AlphaFold chain for accession Q96C90 downloaded
AlphaFold metadata for accession Q15435 downloaded
AlphaFold chain for accession Q15435 downloaded
AlphaFold metadata for accession P62714 downloaded
AlphaFold chain for accession P62714 downloaded
AlphaFold metadata for accession P30153 downloaded
AlphaFold chain for accession P30153 downloaded
AlphaFold metadata for accession Q5MIZ7 downloaded
AlphaFold chain for accession Q5MIZ7 downloaded
AlphaFold metadata for accession P53041 downloaded
AlphaFold chain for accession P53041 downloaded
AlphaFold metadata for accession O00743 downloaded
AlphaFold chain for accession O00743 downloaded
AlphaFold metadata for accession O43663 downloaded
AlphaFold chain for accession O43663 downloaded
AlphaFold metadata for accession Q13162 downloaded
AlphaFold chain for accession Q13162 downloaded
AlphaFold metadata for accession P30041 downloaded
AlphaFold chain for accession P30041 downloaded
AlphaFold metadata for accession P49643 downloaded
AlphaFold chain for accession P49643 downloaded
AlphaFold metadata for accession P10644 downloaded
AlphaFold chain for accession P10644 downloaded
AlphaFold metadata for accession P31323 downloaded
AlphaFold chain for accession P31323 downloaded
AlphaFold metadata for accession P14314 downloaded
AlphaFold chain for accession P14314 downloaded
Impossible to retrieve AlphaFold metadata for accession P78527
Impossible to retrieve pdb data for accession P78527
AlphaFold metadata for accession Q99873 downloaded
AlphaFold chain for accession Q99873 downloaded
AlphaFold metadata for accession O14744 downloaded
AlphaFold chain for accession O14744 downloaded
AlphaFold metadata for accession Q9UNN8 downloaded
AlphaFold chain for accession Q9UNN8 downloaded
AlphaFold metadata for accession Q8NAV1 downloaded
AlphaFold chain for accession Q8NAV1 downloaded
AlphaFold metadata for accession O94906 downloaded
AlphaFold chain for accession O94906 downloaded
AlphaFold metadata for accession P60891 downloaded
AlphaFold chain for accession P60891 downloaded
AlphaFold metadata for accession P11908 downloaded
AlphaFold chain for accession P11908 downloaded
AlphaFold metadata for accession Q14558 downloaded
AlphaFold chain for accession Q14558 downloaded
AlphaFold metadata for accession P07602 downloaded
AlphaFold chain for accession P07602 downloaded
AlphaFold metadata for accession P25786 downloaded
AlphaFold chain for accession P25786 downloaded
AlphaFold metadata for accession P25789 downloaded
AlphaFold chain for accession P25789 downloaded
AlphaFold metadata for accession P60900 downloaded
AlphaFold chain for accession P60900 downloaded
AlphaFold metadata for accession O14818 downloaded
AlphaFold chain for accession O14818 downloaded
AlphaFold metadata for accession P49721 downloaded
AlphaFold chain for accession P49721 downloaded
AlphaFold metadata for accession P49720 downloaded
AlphaFold chain for accession P49720 downloaded
AlphaFold metadata for accession P28070 downloaded
AlphaFold chain for accession P28070 downloaded
AlphaFold metadata for accession P28072 downloaded
AlphaFold chain for accession P28072 downloaded
AlphaFold metadata for accession P62195 downloaded
AlphaFold chain for accession P62195 downloaded
AlphaFold metadata for accession P62333 downloaded
AlphaFold chain for accession P62333 downloaded
AlphaFold metadata for accession O75832 downloaded
AlphaFold chain for accession O75832 downloaded
AlphaFold metadata for accession O00231 downloaded
AlphaFold chain for accession O00231 downloaded
AlphaFold metadata for accession Q9UNM6 downloaded
AlphaFold chain for accession Q9UNM6 downloaded
AlphaFold metadata for accession Q13200 downloaded
AlphaFold chain for accession Q13200 downloaded
AlphaFold metadata for accession O43242 downloaded
AlphaFold chain for accession O43242 downloaded
AlphaFold metadata for accession P55036 downloaded
AlphaFold chain for accession P55036 downloaded
AlphaFold metadata for accession Q15008 downloaded
AlphaFold chain for accession Q15008 downloaded
AlphaFold metadata for accession P48556 downloaded
AlphaFold chain for accession P48556 downloaded
AlphaFold metadata for accession O00233 downloaded
AlphaFold chain for accession O00233 downloaded
AlphaFold metadata for accession P26599 downloaded
AlphaFold chain for accession P26599 downloaded
AlphaFold metadata for accession O95758 downloaded
AlphaFold chain for accession O95758 downloaded
AlphaFold metadata for accession Q15185 downloaded
AlphaFold chain for accession Q15185 downloaded
AlphaFold metadata for accession Q12974 downloaded
AlphaFold chain for accession Q12974 downloaded
AlphaFold metadata for accession P18031 downloaded
AlphaFold chain for accession P18031 downloaded
AlphaFold metadata for accession Q06124 downloaded
AlphaFold chain for accession Q06124 downloaded
AlphaFold metadata for accession Q15678 downloaded
AlphaFold chain for accession Q15678 downloaded
AlphaFold metadata for accession P23467 downloaded

AlphaFold chain for accession P23467 downloaded
AlphaFold metadata for accession Q9Y3E5 downloaded
AlphaFold chain for accession Q9Y3E5 downloaded
AlphaFold metadata for accession Q13610 downloaded
AlphaFold chain for accession Q13610 downloaded
AlphaFold metadata for accession P49023 downloaded
AlphaFold chain for accession P49023 downloaded
AlphaFold metadata for accession P11216 downloaded
AlphaFold chain for accession P11216 downloaded
AlphaFold metadata for accession P47897 downloaded
AlphaFold chain for accession P47897 downloaded
AlphaFold metadata for accession Q9BXR0 downloaded
AlphaFold chain for accession Q9BXR0 downloaded
AlphaFold metadata for accession Q9BXF6 downloaded
AlphaFold chain for accession Q9BXF6 downloaded
AlphaFold metadata for accession Q969Q5 downloaded
AlphaFold chain for accession Q969Q5 downloaded
AlphaFold metadata for accession Q13637 downloaded
AlphaFold chain for accession Q13637 downloaded
AlphaFold metadata for accession P20337 downloaded
AlphaFold chain for accession P20337 downloaded
AlphaFold metadata for accession Q15042 downloaded
AlphaFold chain for accession Q15042 downloaded
AlphaFold metadata for accession Q9H2M9 downloaded
AlphaFold chain for accession Q9H2M9 downloaded
AlphaFold metadata for accession Q9UI14 downloaded
AlphaFold chain for accession Q9UI14 downloaded
AlphaFold metadata for accession P63244 downloaded
AlphaFold chain for accession P63244 downloaded
AlphaFold metadata for accession O60216 downloaded
AlphaFold chain for accession O60216 downloaded
AlphaFold metadata for accession Q92878 downloaded
AlphaFold chain for accession Q92878 downloaded
AlphaFold metadata for accession Q06609 downloaded
AlphaFold chain for accession Q06609 downloaded
AlphaFold metadata for accession P04049 downloaded
AlphaFold chain for accession P04049 downloaded
AlphaFold metadata for accession Q9P0K7 downloaded
AlphaFold chain for accession Q9P0K7 downloaded
AlphaFold metadata for accession Q15311 downloaded
AlphaFold chain for accession Q15311 downloaded
AlphaFold metadata for accession P62826 downloaded
AlphaFold chain for accession P62826 downloaded
Impossible to retrieve AlphaFold metadata for accession P49792
Impossible to retrieve pdb data for accession P49792
AlphaFold metadata for accession P46060 downloaded
AlphaFold chain for accession P46060 downloaded
AlphaFold metadata for accession P62834 downloaded
AlphaFold chain for accession P62834 downloaded
AlphaFold metadata for accession P61224 downloaded
AlphaFold chain for accession P61224 downloaded
AlphaFold metadata for accession P52306 downloaded
AlphaFold chain for accession P52306 downloaded
AlphaFold metadata for accession P54136 downloaded
AlphaFold chain for accession P54136 downloaded
AlphaFold metadata for accession P20936 downloaded
AlphaFold chain for accession P20936 downloaded
AlphaFold metadata for accession Q14644 downloaded
AlphaFold chain for accession Q14644 downloaded
AlphaFold metadata for accession P06400 downloaded
AlphaFold chain for accession P06400 downloaded
AlphaFold metadata for accession Q16576 downloaded
AlphaFold chain for accession Q16576 downloaded
AlphaFold metadata for accession Q8N0V3 downloaded
AlphaFold chain for accession Q8N0V3 downloaded
AlphaFold metadata for accession Q96PK6 downloaded
AlphaFold chain for accession Q96PK6 downloaded
AlphaFold metadata for accession Q96I25 downloaded
AlphaFold chain for accession Q96I25 downloaded
AlphaFold metadata for accession Q5T8P6 downloaded
AlphaFold chain for accession Q5T8P6 downloaded
AlphaFold metadata for accession Q9NW13 downloaded
AlphaFold chain for accession Q9NW13 downloaded
AlphaFold metadata for accession Q9HBH5 downloaded
AlphaFold chain for accession Q9HBH5 downloaded
AlphaFold metadata for accession P46063 downloaded
AlphaFold chain for accession P46063 downloaded
AlphaFold metadata for accession Q9Y3B8 downloaded
AlphaFold chain for accession Q9Y3B8 downloaded
AlphaFold metadata for accession Q6R327 downloaded
AlphaFold chain for accession Q6R327 downloaded
AlphaFold metadata for accession P52758 downloaded
AlphaFold chain for accession P52758 downloaded
AlphaFold metadata for accession A6NDU8 downloaded
AlphaFold chain for accession A6NDU8 downloaded
AlphaFold metadata for accession Q9NVW2 downloaded
AlphaFold chain for accession Q9NVW2 downloaded
AlphaFold metadata for accession Q9Y508 downloaded
AlphaFold chain for accession Q9Y508 downloaded
AlphaFold metadata for accession Q99942 downloaded
AlphaFold chain for accession Q99942 downloaded
AlphaFold metadata for accession P13489 downloaded
AlphaFold chain for accession P13489 downloaded
AlphaFold metadata for accession P10155 downloaded
AlphaFold chain for accession P10155 downloaded
AlphaFold metadata for accession O75116 downloaded
AlphaFold chain for accession O75116 downloaded
AlphaFold metadata for accession Q96AT9 downloaded
AlphaFold chain for accession Q96AT9 downloaded
AlphaFold metadata for accession P27635 downloaded
AlphaFold chain for accession P27635 downloaded
AlphaFold metadata for accession P30050 downloaded
AlphaFold chain for accession P30050 downloaded
AlphaFold metadata for accession P40429 downloaded
AlphaFold chain for accession P40429 downloaded
AlphaFold metadata for accession P50914 downloaded
AlphaFold chain for accession P50914 downloaded
AlphaFold metadata for accession Q02543 downloaded
AlphaFold chain for accession Q02543 downloaded
AlphaFold metadata for accession P62829 downloaded
AlphaFold chain for accession P62829 downloaded
AlphaFold metadata for accession P83731 downloaded
AlphaFold chain for accession P83731 downloaded
AlphaFold metadata for accession P46776 downloaded
AlphaFold chain for accession P46776 downloaded
AlphaFold metadata for accession P46779 downloaded
AlphaFold chain for accession P46779 downloaded
AlphaFold metadata for accession P39023 downloaded
AlphaFold chain for accession P39023 downloaded
AlphaFold metadata for accession P62888 downloaded
AlphaFold chain for accession P62888 downloaded
AlphaFold metadata for accession P62910 downloaded
AlphaFold chain for accession P62910 downloaded
AlphaFold metadata for accession P18077 downloaded
AlphaFold chain for accession P18077 downloaded
AlphaFold metadata for accession Q9Y3U8 downloaded
AlphaFold chain for accession Q9Y3U8 downloaded
AlphaFold metadata for accession P46777 downloaded
AlphaFold chain for accession P46777 downloaded
AlphaFold metadata for accession P32969 downloaded
AlphaFold chain for accession P32969 downloaded
AlphaFold metadata for accession P05388 downloaded
AlphaFold chain for accession P05388 downloaded
AlphaFold metadata for accession P04843 downloaded
AlphaFold chain for accession P04843 downloaded
AlphaFold metadata for accession P04844 downloaded
AlphaFold chain for accession P04844 downloaded
AlphaFold metadata for accession O95059 downloaded
AlphaFold chain for accession O95059 downloaded
AlphaFold metadata for accession Q8N5L8 downloaded
AlphaFold chain for accession Q8N5L8 downloaded
AlphaFold metadata for accession Q9NQG5 downloaded
AlphaFold chain for accession Q9NQG5 downloaded
AlphaFold metadata for accession P25398 downloaded
AlphaFold chain for accession P25398 downloaded
AlphaFold metadata for accession P62263 downloaded
AlphaFold chain for accession P62263 downloaded
AlphaFold metadata for accession P62249 downloaded
AlphaFold chain for accession P62249 downloaded
AlphaFold metadata for accession P60866 downloaded
AlphaFold chain for accession P60866 downloaded
AlphaFold metadata for accession P63220 downloaded
AlphaFold chain for accession P63220 downloaded
AlphaFold metadata for accession P42677 downloaded
AlphaFold chain for accession P42677 downloaded
AlphaFold metadata for accession P62857 downloaded
AlphaFold chain for accession P62857 downloaded
AlphaFold metadata for accession P23396 downloaded
AlphaFold chain for accession P23396 downloaded
AlphaFold metadata for accession P61247 downloaded
AlphaFold chain for accession P61247 downloaded
AlphaFold metadata for accession P62701 downloaded
AlphaFold chain for accession P62701 downloaded
AlphaFold metadata for accession P46782 downloaded
AlphaFold chain for accession P46782 downloaded
AlphaFold metadata for accession P62241 downloaded

AlphaFold chain for accession P62241 downloaded
AlphaFold metadata for accession P10301 downloaded
AlphaFold chain for accession P10301 downloaded
AlphaFold metadata for accession Q9P2E9 downloaded
AlphaFold chain for accession Q9P2E9 downloaded
AlphaFold metadata for accession P23921 downloaded
AlphaFold chain for accession P23921 downloaded
AlphaFold metadata for accession Q5JTH9 downloaded
AlphaFold chain for accession Q5JTH9 downloaded
AlphaFold metadata for accession O76021 downloaded
AlphaFold chain for accession O76021 downloaded
AlphaFold metadata for accession Q9NQC3 downloaded
AlphaFold chain for accession Q9NQC3 downloaded
AlphaFold metadata for accession Q9Y265 downloaded
AlphaFold chain for accession Q9Y265 downloaded
AlphaFold metadata for accession A6NKF1 downloaded
AlphaFold chain for accession A6NKF1 downloaded
Impossible to retrieve AlphaFold metadata for accession Q9NZJ4
Impossible to retrieve pdb data for accession Q9NZJ4
AlphaFold metadata for accession Q9UBE0 downloaded
AlphaFold chain for accession Q9UBE0 downloaded
AlphaFold metadata for accession Q5K651 downloaded
AlphaFold chain for accession Q5K651 downloaded
AlphaFold metadata for accession Q6SZW1 downloaded
AlphaFold chain for accession Q6SZW1 downloaded
AlphaFold metadata for accession Q15020 downloaded
AlphaFold chain for accession Q15020 downloaded
AlphaFold metadata for accession Q9Y3A5 downloaded
AlphaFold chain for accession Q9Y3A5 downloaded
AlphaFold metadata for accession Q14108 downloaded
AlphaFold chain for accession Q14108 downloaded
AlphaFold metadata for accession Q12765 downloaded
AlphaFold chain for accession Q12765 downloaded
AlphaFold metadata for accession Q9NVU7 downloaded
AlphaFold chain for accession Q9NVU7 downloaded
AlphaFold metadata for accession P31040 downloaded
AlphaFold chain for accession P31040 downloaded
AlphaFold metadata for accession P55735 downloaded
AlphaFold chain for accession P55735 downloaded
AlphaFold metadata for accession Q15437 downloaded
AlphaFold chain for accession Q15437 downloaded
AlphaFold metadata for accession Q9Y6Y8 downloaded
AlphaFold chain for accession Q9Y6Y8 downloaded
AlphaFold metadata for accession P53992 downloaded
AlphaFold chain for accession P53992 downloaded
AlphaFold metadata for accession O94855 downloaded
AlphaFold chain for accession O94855 downloaded
AlphaFold metadata for accession O94979 downloaded
AlphaFold chain for accession O94979 downloaded
AlphaFold metadata for accession Q99442 downloaded
AlphaFold chain for accession Q99442 downloaded
AlphaFold metadata for accession Q9UGP8 downloaded
AlphaFold chain for accession Q9UGP8 downloaded
AlphaFold metadata for accession Q96T21 downloaded
AlphaFold chain for accession Q96T21 downloaded
AlphaFold metadata for accession Q93073 downloaded
AlphaFold chain for accession Q93073 downloaded
AlphaFold metadata for accession O75326 downloaded
AlphaFold chain for accession O75326 downloaded
AlphaFold metadata for accession Q9H4L4 downloaded
AlphaFold chain for accession Q9H4L4 downloaded
AlphaFold metadata for accession Q15019 downloaded
AlphaFold chain for accession Q15019 downloaded
AlphaFold metadata for accession Q16181 downloaded
AlphaFold chain for accession Q16181 downloaded
AlphaFold metadata for accession P05120 downloaded
AlphaFold chain for accession P05120 downloaded
AlphaFold metadata for accession P35237 downloaded
AlphaFold chain for accession P35237 downloaded
AlphaFold metadata for accession Q15047 downloaded
AlphaFold chain for accession Q15047 downloaded
AlphaFold metadata for accession Q15459 downloaded
AlphaFold chain for accession Q15459 downloaded
AlphaFold metadata for accession Q15428 downloaded
AlphaFold chain for accession Q15428 downloaded
AlphaFold metadata for accession Q12874 downloaded
AlphaFold chain for accession Q12874 downloaded
AlphaFold metadata for accession O75533 downloaded
AlphaFold chain for accession O75533 downloaded
AlphaFold metadata for accession O43765 downloaded
AlphaFold chain for accession O43765 downloaded
AlphaFold metadata for accession Q9Y3L3 downloaded
AlphaFold chain for accession Q9Y3L3 downloaded
AlphaFold metadata for accession Q99961 downloaded
AlphaFold chain for accession Q99961 downloaded
AlphaFold metadata for accession P29353 downloaded
AlphaFold chain for accession P29353 downloaded
AlphaFold metadata for accession P34896 downloaded
AlphaFold chain for accession P34896 downloaded
AlphaFold metadata for accession P34897 downloaded
AlphaFold chain for accession P34897 downloaded
AlphaFold metadata for accession O60292 downloaded
AlphaFold chain for accession O60292 downloaded
AlphaFold metadata for accession P63208 downloaded
AlphaFold chain for accession P63208 downloaded
AlphaFold metadata for accession Q9H936 downloaded
AlphaFold chain for accession Q9H936 downloaded
AlphaFold metadata for accession Q6NUK1 downloaded
AlphaFold chain for accession Q6NUK1 downloaded
AlphaFold metadata for accession P05141 downloaded
AlphaFold chain for accession P05141 downloaded
AlphaFold metadata for accession Q9Y6M5 downloaded
AlphaFold chain for accession Q9Y6M5 downloaded
AlphaFold metadata for accession Q8NEW0 downloaded
AlphaFold chain for accession Q8NEW0 downloaded
AlphaFold metadata for accession O00400 downloaded
AlphaFold chain for accession O00400 downloaded
AlphaFold metadata for accession Q9BWU0 downloaded
AlphaFold chain for accession Q9BWU0 downloaded
AlphaFold metadata for accession Q96CW6 downloaded
AlphaFold chain for accession Q96CW6 downloaded
AlphaFold metadata for accession Q08AF3 downloaded
AlphaFold chain for accession Q08AF3 downloaded
AlphaFold metadata for accession Q9H2G2 downloaded
AlphaFold chain for accession Q9H2G2 downloaded
AlphaFold metadata for accession Q14683 downloaded
AlphaFold chain for accession Q14683 downloaded
AlphaFold metadata for accession Q9UQE7 downloaded
AlphaFold chain for accession Q9UQE7 downloaded
AlphaFold metadata for accession Q9NTJ3 downloaded
AlphaFold chain for accession Q9NTJ3 downloaded
AlphaFold metadata for accession A6NHR9 downloaded
AlphaFold chain for accession A6NHR9 downloaded
AlphaFold metadata for accession Q96Q15 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q96Q15
Impossible to retrieve pdb data for accession Q96Q15
AlphaFold metadata for accession P52788 downloaded
AlphaFold chain for accession P52788 downloaded
AlphaFold metadata for accession Q9HAU4 downloaded
AlphaFold chain for accession Q9HAU4 downloaded
AlphaFold metadata for accession Q7KZF4 downloaded
AlphaFold chain for accession Q7KZF4 downloaded
AlphaFold metadata for accession O75643 downloaded
AlphaFold chain for accession O75643 downloaded
AlphaFold metadata for accession P09234 downloaded
AlphaFold chain for accession P09234 downloaded
AlphaFold metadata for accession P62316 downloaded
AlphaFold chain for accession P62316 downloaded
AlphaFold metadata for accession P62318 downloaded
AlphaFold chain for accession P62318 downloaded
AlphaFold metadata for accession Q13596 downloaded
AlphaFold chain for accession Q13596 downloaded
AlphaFold metadata for accession Q9UNH7 downloaded
AlphaFold chain for accession Q9UNH7 downloaded
AlphaFold metadata for accession P18583 downloaded
AlphaFold chain for accession P18583 downloaded
AlphaFold metadata for accession Q86XZ4 downloaded
AlphaFold chain for accession Q86XZ4 downloaded
AlphaFold metadata for accession Q9NUQ6 downloaded
AlphaFold chain for accession Q9NUQ6 downloaded
AlphaFold metadata for accession Q5M775 downloaded
AlphaFold chain for accession Q5M775 downloaded
AlphaFold metadata for accession Q13813 downloaded
AlphaFold chain for accession Q13813 downloaded
AlphaFold metadata for accession Q01082 downloaded
AlphaFold chain for accession Q01082 downloaded
AlphaFold metadata for accession O15269 downloaded
AlphaFold chain for accession O15269 downloaded
AlphaFold metadata for accession Q13501 downloaded
AlphaFold chain for accession Q13501 downloaded
Impossible to retrieve AlphaFold metadata for accession Q6ZRS2
Impossible to retrieve pdb data for accession Q6ZRS2
AlphaFold metadata for accession P30626 downloaded
AlphaFold chain for accession P30626 downloaded
AlphaFold metadata for accession P09132 downloaded

AlphaFold chain for accession P09132 downloaded
AlphaFold metadata for accession P61011 downloaded
AlphaFold chain for accession P61011 downloaded
AlphaFold metadata for accession Q9UHB9 downloaded
AlphaFold chain for accession Q9UHB9 downloaded
AlphaFold metadata for accession O76094 downloaded
AlphaFold chain for accession O76094 downloaded
AlphaFold metadata for accession P49458 downloaded
AlphaFold chain for accession P49458 downloaded
AlphaFold metadata for accession P08240 downloaded
AlphaFold chain for accession P08240 downloaded
AlphaFold metadata for accession Q9Y5M8 downloaded
AlphaFold chain for accession Q9Y5M8 downloaded
AlphaFold metadata for accession Q9BXP5 downloaded
AlphaFold chain for accession Q9BXP5 downloaded
AlphaFold metadata for accession Q07955 downloaded
AlphaFold chain for accession Q07955 downloaded
AlphaFold metadata for accession P84103 downloaded
AlphaFold chain for accession P84103 downloaded
AlphaFold metadata for accession Q08170 downloaded
AlphaFold chain for accession Q08170 downloaded
AlphaFold metadata for accession Q13242 downloaded
AlphaFold chain for accession Q13242 downloaded
AlphaFold metadata for accession P05455 downloaded
AlphaFold chain for accession P05455 downloaded
AlphaFold metadata for accession Q8WVM7 downloaded
AlphaFold chain for accession Q8WVM7 downloaded
AlphaFold metadata for accession O95210 downloaded
AlphaFold chain for accession O95210 downloaded
AlphaFold metadata for accession P31948 downloaded
AlphaFold chain for accession P31948 downloaded
AlphaFold metadata for accession O94804 downloaded
AlphaFold chain for accession O94804 downloaded
AlphaFold metadata for accession Q9Y6E0 downloaded
AlphaFold chain for accession Q9Y6E0 downloaded
AlphaFold metadata for accession Q9UEW8 downloaded
AlphaFold chain for accession Q9UEW8 downloaded
AlphaFold metadata for accession Q9UNE7 downloaded
AlphaFold chain for accession Q9UNE7 downloaded
AlphaFold metadata for accession Q86Y82 downloaded
AlphaFold chain for accession Q86Y82 downloaded
AlphaFold metadata for accession Q9P2W9 downloaded
AlphaFold chain for accession Q9P2W9 downloaded
AlphaFold metadata for accession Q12846 downloaded
AlphaFold chain for accession Q12846 downloaded
AlphaFold metadata for accession Q13190 downloaded
AlphaFold chain for accession Q13190 downloaded
AlphaFold metadata for accession O15400 downloaded
AlphaFold chain for accession O15400 downloaded
AlphaFold metadata for accession O00186 downloaded
AlphaFold chain for accession O00186 downloaded
AlphaFold metadata for accession Q9Y2Z0 downloaded
AlphaFold chain for accession Q9Y2Z0 downloaded
AlphaFold metadata for accession O94901 downloaded
AlphaFold chain for accession O94901 downloaded
AlphaFold metadata for accession Q9Y5B9 downloaded
AlphaFold chain for accession Q9Y5B9 downloaded
AlphaFold metadata for accession O00267 downloaded
AlphaFold chain for accession O00267 downloaded
AlphaFold metadata for accession Q9H7C4 downloaded
AlphaFold chain for accession Q9H7C4 downloaded
AlphaFold metadata for accession Q8NF91 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q8NF91
Impossible to retrieve pdb data for accession Q8NF91
AlphaFold metadata for accession O15056 downloaded
AlphaFold chain for accession O15056 downloaded
AlphaFold metadata for accession Q9BSH4 downloaded
AlphaFold chain for accession Q9BSH4 downloaded
AlphaFold metadata for accession Q01995 downloaded
AlphaFold chain for accession Q01995 downloaded
AlphaFold metadata for accession P37837 downloaded
AlphaFold chain for accession P37837 downloaded
AlphaFold metadata for accession Q9C0D5 downloaded
AlphaFold chain for accession Q9C0D5 downloaded
AlphaFold metadata for accession Q9UL54 downloaded
AlphaFold chain for accession Q9UL54 downloaded
AlphaFold metadata for accession Q03519 downloaded
AlphaFold chain for accession Q03519 downloaded
AlphaFold metadata for accession Q13148 downloaded
AlphaFold chain for accession Q13148 downloaded
AlphaFold metadata for accession P26639 downloaded
AlphaFold chain for accession P26639 downloaded
AlphaFold metadata for accession Q9UK61 downloaded
AlphaFold chain for accession Q9UK61 downloaded
AlphaFold metadata for accession Q9BYX2 downloaded
AlphaFold chain for accession Q9BYX2 downloaded
AlphaFold metadata for accession O60343 downloaded
AlphaFold chain for accession O60343 downloaded
AlphaFold metadata for accession O75347 downloaded
AlphaFold chain for accession O75347 downloaded
AlphaFold metadata for accession Q99426 downloaded
AlphaFold chain for accession Q99426 downloaded
AlphaFold metadata for accession Q15814 downloaded
AlphaFold chain for accession Q15814 downloaded
AlphaFold metadata for accession Q9BTW9 downloaded
AlphaFold chain for accession Q9BTW9 downloaded
AlphaFold metadata for accession Q9Y4P3 downloaded
AlphaFold chain for accession Q9Y4P3 downloaded
AlphaFold metadata for accession P23193 downloaded
AlphaFold chain for accession P23193 downloaded
AlphaFold metadata for accession Q9BQ70 downloaded
AlphaFold chain for accession Q9BQ70 downloaded
AlphaFold metadata for accession Q9Y4R8 downloaded
AlphaFold chain for accession Q9Y4R8 downloaded
AlphaFold metadata for accession Q12800 downloaded
AlphaFold chain for accession Q12800 downloaded
AlphaFold metadata for accession Q9UBB9 downloaded
AlphaFold chain for accession Q9UBB9 downloaded
AlphaFold metadata for accession P21980 downloaded
AlphaFold chain for accession P21980 downloaded
AlphaFold metadata for accession Q6I9Y2 downloaded
AlphaFold chain for accession Q6I9Y2 downloaded
AlphaFold metadata for accession Q9NXG2 downloaded
AlphaFold chain for accession Q9NXG2 downloaded
AlphaFold metadata for accession P04216 downloaded
AlphaFold chain for accession P04216 downloaded
AlphaFold metadata for accession P62072 downloaded
AlphaFold chain for accession P62072 downloaded
AlphaFold metadata for accession O75663 downloaded
AlphaFold chain for accession O75663 downloaded
AlphaFold metadata for accession P29401 downloaded
AlphaFold chain for accession P29401 downloaded
AlphaFold metadata for accession Q9Y490 downloaded
AlphaFold chain for accession Q9Y490 downloaded
AlphaFold metadata for accession Q99805 downloaded
AlphaFold chain for accession Q99805 downloaded
AlphaFold metadata for accession O94876 downloaded
AlphaFold chain for accession O94876 downloaded
AlphaFold metadata for accession Q9ULS5 downloaded
AlphaFold chain for accession Q9ULS5 downloaded
AlphaFold metadata for accession Q9Y3B3 downloaded
AlphaFold chain for accession Q9Y3B3 downloaded
AlphaFold metadata for accession Q6NUQ4 downloaded
AlphaFold chain for accession Q6NUQ4 downloaded
AlphaFold metadata for accession P42166 downloaded
AlphaFold chain for accession P42166 downloaded
AlphaFold metadata for accession Q92973 downloaded
AlphaFold chain for accession Q92973 downloaded
AlphaFold metadata for accession O14787 downloaded
AlphaFold chain for accession O14787 downloaded
AlphaFold metadata for accession Q9Y5L0 downloaded
AlphaFold chain for accession Q9Y5L0 downloaded
AlphaFold metadata for accession O94826 downloaded
AlphaFold chain for accession O94826 downloaded
AlphaFold metadata for accession Q92547 downloaded
AlphaFold chain for accession Q92547 downloaded
AlphaFold metadata for accession Q9NXH8 downloaded
AlphaFold chain for accession Q9NXH8 downloaded
AlphaFold metadata for accession Q12888 downloaded
AlphaFold chain for accession Q12888 downloaded
AlphaFold metadata for accession Q53FA7 downloaded
AlphaFold chain for accession Q53FA7 downloaded
AlphaFold metadata for accession P60174 downloaded
AlphaFold chain for accession P60174 downloaded
AlphaFold metadata for accession P67936 downloaded
AlphaFold chain for accession P67936 downloaded
AlphaFold metadata for accession P29144 downloaded
AlphaFold chain for accession P29144 downloaded
AlphaFold metadata for accession P12270 downloaded
AlphaFold chain for accession P12270 downloaded
AlphaFold metadata for accession Q5T0D9 downloaded
AlphaFold chain for accession Q5T0D9 downloaded
AlphaFold metadata for accession P13693 downloaded
AlphaFold chain for accession P13693 downloaded
AlphaFold metadata for accession Q12931 downloaded

AlphaFold chain for accession Q12931 downloaded
AlphaFold metadata for accession Q8WVT3 downloaded
AlphaFold chain for accession Q8WVT3 downloaded
AlphaFold metadata for accession Q15643 downloaded
AlphaFold chain for accession Q15643 downloaded
AlphaFold metadata for accession Q9UJA5 downloaded
AlphaFold chain for accession Q9UJA5 downloaded
AlphaFold metadata for accession Q96FX7 downloaded
AlphaFold chain for accession Q96FX7 downloaded
AlphaFold metadata for accession P43897 downloaded
AlphaFold chain for accession P43897 downloaded
AlphaFold metadata for accession Q99598 downloaded
AlphaFold chain for accession Q99598 downloaded
AlphaFold metadata for accession Q16762 downloaded
AlphaFold chain for accession Q16762 downloaded
AlphaFold metadata for accession Q5R3I4 downloaded
AlphaFold chain for accession Q5R3I4 downloaded
AlphaFold metadata for accession Q15361 downloaded
AlphaFold chain for accession Q15361 downloaded
AlphaFold metadata for accession Q8NG68 downloaded
AlphaFold chain for accession Q8NG68 downloaded
AlphaFold metadata for accession P07437 downloaded
AlphaFold chain for accession P07437 downloaded
AlphaFold metadata for accession Q9BUF5 downloaded
AlphaFold chain for accession Q9BUF5 downloaded
AlphaFold metadata for accession P23258 downloaded
AlphaFold chain for accession P23258 downloaded
AlphaFold metadata for accession Q12792 downloaded
AlphaFold chain for accession Q12792 downloaded
AlphaFold metadata for accession O95881 downloaded
AlphaFold chain for accession O95881 downloaded
AlphaFold metadata for accession O14530 downloaded
AlphaFold chain for accession O14530 downloaded
AlphaFold metadata for accession Q9BZF9 downloaded
AlphaFold chain for accession Q9BZF9 downloaded
AlphaFold metadata for accession P22314 downloaded
AlphaFold chain for accession P22314 downloaded
AlphaFold metadata for accession Q9UBT2 downloaded
AlphaFold chain for accession Q9UBT2 downloaded
AlphaFold metadata for accession Q8TBC4 downloaded
AlphaFold chain for accession Q8TBC4 downloaded
AlphaFold metadata for accession A0AVT1 downloaded
AlphaFold chain for accession A0AVT1 downloaded
AlphaFold metadata for accession Q9BSL1 downloaded
AlphaFold chain for accession Q9BSL1 downloaded
AlphaFold metadata for accession Q8TF42 downloaded
AlphaFold chain for accession Q8TF42 downloaded
AlphaFold metadata for accession P61086 downloaded
AlphaFold chain for accession P61086 downloaded
AlphaFold metadata for accession P61081 downloaded
AlphaFold chain for accession P61081 downloaded
AlphaFold metadata for accession P61088 downloaded
AlphaFold chain for accession P61088 downloaded
AlphaFold metadata for accession Q15386 downloaded
AlphaFold chain for accession Q15386 downloaded
AlphaFold metadata for accession O95155 downloaded
AlphaFold chain for accession O95155 downloaded
AlphaFold metadata for accession Q9NPG3 downloaded
AlphaFold chain for accession Q9NPG3 downloaded
AlphaFold metadata for accession Q9NZI7 downloaded
AlphaFold chain for accession Q9NZI7 downloaded
AlphaFold metadata for accession Q5T4S7 downloaded
No AlphaFold model with same sequence length as UniProt for accession Q5T4S7
Impossible to retrieve pdb data for accession Q5T4S7
AlphaFold metadata for accession Q8N806 downloaded
AlphaFold chain for accession Q8N806 downloaded
AlphaFold metadata for accession P09936 downloaded
AlphaFold chain for accession P09936 downloaded
AlphaFold metadata for accession Q8IX04 downloaded
AlphaFold chain for accession Q8IX04 downloaded
AlphaFold metadata for accession O94874 downloaded
AlphaFold chain for accession O94874 downloaded
AlphaFold metadata for accession O60701 downloaded
AlphaFold chain for accession O60701 downloaded
AlphaFold metadata for accession Q96T88 downloaded
AlphaFold chain for accession Q96T88 downloaded
AlphaFold metadata for accession Q9H3U1 downloaded
AlphaFold chain for accession Q9H3U1 downloaded
AlphaFold metadata for accession Q92900 downloaded
AlphaFold chain for accession Q92900 downloaded
AlphaFold metadata for accession P31930 downloaded
AlphaFold chain for accession P31930 downloaded
AlphaFold metadata for accession P22695 downloaded
AlphaFold chain for accession P22695 downloaded
AlphaFold metadata for accession O94763 downloaded
AlphaFold chain for accession O94763 downloaded
AlphaFold metadata for accession P06132 downloaded
AlphaFold chain for accession P06132 downloaded
AlphaFold metadata for accession Q96K76 downloaded
AlphaFold chain for accession Q96K76 downloaded
AlphaFold metadata for accession Q93009 downloaded
AlphaFold chain for accession Q93009 downloaded
AlphaFold metadata for accession Q93008 downloaded
AlphaFold chain for accession Q93008 downloaded
AlphaFold metadata for accession P46939 downloaded
No AlphaFold model with same sequence length as UniProt for accession P46939
Impossible to retrieve pdb data for accession P46939
AlphaFold metadata for accession Q08AM6 downloaded
AlphaFold chain for accession Q08AM6 downloaded
AlphaFold metadata for accession Q9P0L0 downloaded
AlphaFold chain for accession Q9P0L0 downloaded
AlphaFold metadata for accession O95292 downloaded
AlphaFold chain for accession O95292 downloaded
AlphaFold metadata for accession P26640 downloaded
AlphaFold chain for accession P26640 downloaded
AlphaFold metadata for accession P50552 downloaded
AlphaFold chain for accession P50552 downloaded
AlphaFold metadata for accession Q99536 downloaded
AlphaFold chain for accession Q99536 downloaded
AlphaFold metadata for accession P13611 downloaded
No AlphaFold model with same sequence length as UniProt for accession P13611
Impossible to retrieve pdb data for accession P13611
AlphaFold metadata for accession P18206 downloaded
AlphaFold chain for accession P18206 downloaded
AlphaFold metadata for accession P55072 downloaded
AlphaFold chain for accession P55072 downloaded
AlphaFold metadata for accession P21796 downloaded
AlphaFold chain for accession P21796 downloaded
AlphaFold metadata for accession P45880 downloaded
AlphaFold chain for accession P45880 downloaded
AlphaFold metadata for accession P08670 downloaded
AlphaFold chain for accession P08670 downloaded
AlphaFold metadata for accession Q9BQB6 downloaded
AlphaFold chain for accession Q9BQB6 downloaded
AlphaFold metadata for accession Q9UK41 downloaded
AlphaFold chain for accession Q9UK41 downloaded
AlphaFold metadata for accession Q96QK1 downloaded
AlphaFold chain for accession Q96QK1 downloaded
AlphaFold metadata for accession O75351 downloaded
AlphaFold chain for accession O75351 downloaded
AlphaFold metadata for accession Q9UID3 downloaded
AlphaFold chain for accession Q9UID3 downloaded
AlphaFold metadata for accession Q9NP79 downloaded
AlphaFold chain for accession Q9NP79 downloaded
AlphaFold metadata for accession P23381 downloaded
AlphaFold chain for accession P23381 downloaded
AlphaFold metadata for accession Q2M389 downloaded
AlphaFold chain for accession Q2M389 downloaded
AlphaFold metadata for accession Q8IWB7 downloaded
AlphaFold chain for accession Q8IWB7 downloaded
AlphaFold metadata for accession O75083 downloaded
AlphaFold chain for accession O75083 downloaded
AlphaFold metadata for accession Q9BZH6 downloaded
AlphaFold chain for accession Q9BZH6 downloaded
AlphaFold metadata for accession Q5JSH3 downloaded
AlphaFold chain for accession Q5JSH3 downloaded
AlphaFold metadata for accession P61964 downloaded
AlphaFold chain for accession P61964 downloaded
AlphaFold metadata for accession Q8IWA0 downloaded
AlphaFold chain for accession Q8IWA0 downloaded
AlphaFold metadata for accession Q9H4A3 downloaded
AlphaFold chain for accession Q9H4A3 downloaded
AlphaFold metadata for accession Q9NQW7 downloaded
AlphaFold chain for accession Q9NQW7 downloaded
AlphaFold metadata for accession Q9HAV4 downloaded
AlphaFold chain for accession Q9HAV4 downloaded
AlphaFold metadata for accession O43592 downloaded
AlphaFold chain for accession O43592 downloaded
AlphaFold metadata for accession Q13426 downloaded
AlphaFold chain for accession Q13426 downloaded
AlphaFold metadata for accession Q8IZH2 downloaded
AlphaFold chain for accession Q8IZH2 downloaded
AlphaFold metadata for accession P54577 downloaded
AlphaFold chain for accession P54577 downloaded
AlphaFold metadata for accession Q9Y2Z4 downloaded

AlphaFold chain for accession Q9Y2Z4 downloaded
AlphaFold metadata for accession O15498 downloaded
AlphaFold chain for accession O15498 downloaded
AlphaFold metadata for accession Q04917 downloaded
AlphaFold chain for accession Q04917 downloaded
AlphaFold metadata for accession P27348 downloaded
AlphaFold chain for accession P27348 downloaded
AlphaFold metadata for accession P63104 downloaded
AlphaFold chain for accession P63104 downloaded
AlphaFold metadata for accession Q8NAP3 downloaded
AlphaFold chain for accession Q8NAP3 downloaded
AlphaFold metadata for accession Q8IWR0 downloaded
AlphaFold chain for accession Q8IWR0 downloaded
AlphaFold metadata for accession Q7Z2W4 downloaded
AlphaFold chain for accession Q7Z2W4 downloaded
AlphaFold metadata for accession Q96KR1 downloaded
AlphaFold chain for accession Q96KR1 downloaded
AlphaFold metadata for accession Q8N5A5 downloaded
AlphaFold chain for accession Q8N5A5 downloaded
AlphaFold metadata for accession Q8TF68 downloaded
AlphaFold chain for accession Q8TF68 downloaded
AlphaFold metadata for accession Q2TB10 downloaded
AlphaFold chain for accession Q2TB10 downloaded
AlphaFold metadata for accession Q15942 downloaded
AlphaFold chain for accession Q15942 downloaded
     protein accession number gene name cysteine site AlphaFold_model_ID  \
0                      P49588     AARS1          C773       AF-P49588-F1
1                      P49588     AARS1          C903       AF-P49588-F1
2                      P33527     ABCC1          C744       AF-P33527-F1
3                      Q8NE71     ABCF1          C655       AF-Q8NE71-F1
4                      Q9NUJ1    ABHD10          C100       AF-Q9NUJ1-F1
...                       ...       ...           ...                ...
1719                   Q96KR1       ZFR          C922       AF-Q96KR1-F1
1720                   Q8N5A5     ZGPAT          C377       AF-Q8N5A5-F1
1721                   Q8TF68    ZNF384          C435       AF-Q8TF68-F1
1722                   Q2TB10    ZNF800          C359       AF-Q2TB10-F1
1723                   Q15942       ZYX          C384       AF-Q15942-F1

                                     proximity_residues
0     {740: 19.66, 760: 19.97, 761: 18.45, 762: 16.5...
1     {837: 19.04, 838: 16.9, 839: 19.15, 840: 18.87...
2     {673: 17.89, 674: 19.89, 675: 19.65, 708: 19.0...
3     {439: 19.08, 479: 17.14, 480: 16.88, 481: 17.1...
4     {14: 19.44, 15: 19.27, 16: 16.45, 17: 17.71, 1...
...                                                 ...
1719  {12: 18.29, 13: 17.56, 14: 15.82, 15: 17.88, 1...
1720  {363: 17.48, 364: 16.04, 365: 13.77, 366: 10.5...
1721  {424: 18.95, 425: 18.81, 427: 17.65, 428: 18.3...
1722  {291: 18.62, 292: 18.3, 308: 19.8, 309: 16.77,...
1723  {1: 18.25, 2: 19.81, 53: 18.26, 54: 18.0, 55: ...

[1724 rows x 5 columns]

Total accessions with no output: 14
Total accessions with no model of the correct length: 11

### 3.5 - Extract features present in residues in proximity to the cysteines

In [21]:
def listAppend(featureType, description, begin, end=None):
    ### Append the description and position of a feature to a cysteine's list
    global feature_lists, feature_counts
    if end:
        feature_lists[featureType].append(f'{description} ({begin}-{end})')
    else:
        feature_lists[featureType].append(f'{description} ({begin})')
    feature_counts[featureType] += 1

In [22]:
def isoform(index):
    ### Extract the chosen canonical isoform of a protein that has alternative splicing
    for comment in EBI_output["EBI_data"][index]["comments"]:
        if comment["type"] == "ALTERNATIVE_PRODUCTS":
            for isoform in comment["isoforms"]:
                if isoform["sequenceStatus"] == "displayed":
                    return isoform["ids"]

In [23]:
AlphaFoldModelIDS = []
domains = []
ptms = []
feature_counts = {"domains": 0, "ptms": 0}

for i in range(len(AlphaFold_output)):
    proximity_residues = AlphaFold_output["proximity_residues"][i]
    feature_lists = {"domains": [], "ptms": []}

    # Loop over domains and PTMs of the protein, select those that are spatially close to the cysteine
    for j in EBI_output["EBI_data"][i]["features"]:
        try:
            begin = int(j["begin"])
        except:  # when beginning of a feature is "?"
            begin = 0
        try:
            end = int(j["end"])
        except:  # when end of a feature is "?"
            end = 9999        
        if j["molecule"] and j["molecule"] != isoform(i):
            break # if feature is in an isoform that is not the canonical

        if j["category"] == "DOMAINS_AND_SITES":
            # Binding sites in proximity to the cysteine
            if j["type"] in ["BINDING", "SITE", "ACT_SITE"]:
                if begin in proximity_residues.keys():
                    if j["type"] == "BINDING":
                        description = f'{j["ligand"]["name"]} binding site'
                    elif j["type"] == "ACT_SITE" and not j["description"]:
                        description = "Active site"
                    else:
                        description = j["description"]
                    listAppend("domains", description, f'{begin}, {proximity_residues[begin]:.2f} Å')
            # Domains that include residues close to the cysteine
            else:
                if any(x in proximity_residues.keys() for x in list(range(begin, end+1))):
                    residues_in_domain = {residue: distance for residue, distance in proximity_residues.items() if begin <= residue <= end}
                    closest_residue = min(residues_in_domain, key=residues_in_domain.get)
                    try:
                        if j["type"] == "DNA_BIND" and not j["description"]:
                            listAppend("domains", "DNA binding", begin, f'{end}) - ({closest_residue}, {proximity_residues[closest_residue]:.2f} Å')
                        else:
                            listAppend("domains", j["description"], begin, f'{end}) - ({closest_residue}, {proximity_residues[closest_residue]:.2f} Å')
                    except:  # for those domains that don't have a description
                        if j["type"] == "COILED":
                            listAppend("domains", "Coiled coil", begin, f'{end}) - ({closest_residue}, {proximity_residues[closest_residue]:.2f} Å')

        if j["category"] == "PTM":
            # Disulfide bonds
            if j["type"] == "DISULFID":
                if begin in proximity_residues.keys():
                    listAppend("ptms", "Disulfide bond", f'{begin}, {proximity_residues[begin]:.2f} Å ', f' {end}')
                elif end in proximity_residues.keys():
                    listAppend("ptms", "Disulfide bond", f'{begin} ', f' {end}, {proximity_residues[end]:.2f} Å')
            # PTMs in proximity to the cysteine
            else:
                if begin in proximity_residues.keys():
                    ptm_name = j["description"].split(";")[0]
                    listAppend("ptms", ptm_name, f'{begin}, {proximity_residues[begin]:.2f} Å')

    AlphaFoldModelIDS.append(AlphaFold_output["AlphaFold_model_ID"][i])
    domains.append(feature_lists["domains"])
    ptms.append(feature_lists["ptms"])

AlphaFold_features = pd.DataFrame({"AlphaFold_model_ID": AlphaFoldModelIDS, "nearby_domains": domains, "nearby_PTMs": ptms})
print(f'{feature_counts["domains"]} nearby domains and {feature_counts["ptms"]} nearby PTMs extracted in total')

4613 nearby domains and 1881 nearby PTMs extracted in total

### 3.6 - Create a DataFrame with all the new features appended to the input data and save it

In [24]:
final_output = pd.concat([input_data, AIUPred_features, EBI_features, AlphaFold_features], axis=1)

# Change the order of columns
cols = list(final_output.columns)
new_cols = [cols[-12], cols[-11], cols[-5], cols[-3], cols[-4], cols[-6], cols[-10], cols[-9], cols[-8], cols[-7], cols[-2], cols[-1]]
final_output = final_output[new_cols]

final_output.to_excel("Analysis_output.xlsx")
final_output

,protein accession number,gene name,full_name,AlphaFold_model_ID,subcellular_loc,protein_length,cysteine site,sensitive,cysteine_within,disorder_value,nearby_domains,nearby_PTMs
0,P49588,AARS1,"Alanine--tRNA ligase, cytoplasmic",AF-P49588-F1,"[Cytoplasm, Nucleus]",968,C773,No,No,0.16,"[Nuclear localization signal (750-763) - (763,...",[]
1,P49588,AARS1,"Alanine--tRNA ligase, cytoplasmic",AF-P49588-F1,"[Cytoplasm, Nucleus]",968,C903,No,No,0.13,[],"[N6-acetyllysine (876, 10.35 Å), N6,N6,N6-trim..."
2,P33527,ABCC1,ATP-binding cassette sub-family C member 1,AF-P33527-F1,"[Cell membrane, Basolateral cell membrane]",1531,C744,No,No,0.05,"[ABC transporter 1 (644-868) - (744, 0.00 Å), ...",[]
3,Q8NE71,ABCF1,ATP-binding cassette sub-family F member 1,AF-Q8NE71-F1,"[Cytoplasm, Nucleus, nucleoplasm, Nucleus enve...",845,C655,No,No,0.06,"[ABC transporter 1 (304-548) - (484, 10.64 Å),...",[]
4,Q9NUJ1,ABHD10,"Palmitoyl-protein thioesterase ABHD10, mitocho...",AF-Q9NUJ1-F1,[Mitochondrion],306,C100,No,No,0.03,"[AB hydrolase-1 (78-178) - (100, 0.00 Å)]",[]
...,...,...,...,...,...,...,...,...,...,...,...,...
1719,Q96KR1,ZFR,Zinc finger RNA-binding protein,AF-Q96KR1-F1,"[Nucleus, Cytoplasm, Cytoplasmic granule, Chro...",1074,C922,Yes,No,0.04,"[DZF (703-1073) - (922, 0.00 Å), Disordered (7...",[]
1720,Q8N5A5,ZGPAT,Zinc finger CCCH-type with G patch domain-cont...,AF-Q8N5A5-F1,"[Nucleus, Nucleus]",531,C377,Yes,Yes,0.35,"[G-patch (333-379) - (377, 0.00 Å), Disordered...","[Phosphoserine (373, 6.34 Å)]"
1721,Q8TF68,ZNF384,Zinc finger protein 384,AF-Q8TF68-F1,[Nucleus],577,C435,Yes,Yes,0.26,"[C2H2-type 7 (403-425) - (425, 18.81 Å), C2H2-...",[]
1722,Q2TB10,ZNF800,Zinc finger protein 800,AF-Q2TB10-F1,"[Nucleus, Chromosome]",664,C359,Yes,Yes,0.37,"[C2H2-type 3 (287-310) - (310, 15.94 Å), C2H2-...",[]
1723,Q15942,ZYX,Zyxin,AF-Q15942-F1,"[Cytoplasm, Cytoplasm, cytoskeleton, Nucleus, ...",572,C384,Yes,Yes,0.31,"[LIM zinc-binding 1 (384-443) - (384, 0.00 Å),...","[N-acetylalanine (2, 19.81 Å)]"

### 3.7 - A few considerations on the findings from scraping data from AIUPred.

In [25]:
print(f'Out of the {len(np.unique(final_output[accession_column]))} proteins in the data set, \
{len(np.unique(final_output[final_output["sensitive"] == "Yes"][accession_column]))} are sensitive to oxidation, \
with a total of {final_output[final_output["sensitive"] == "Yes"].shape[0]} cysteines in them.\n\
Of the {final_output.shape[0]} total cysteines in the data set, \
{final_output[final_output["cysteine_within"] == "Yes"].shape[0]} lie in a region affected by the oxidative environment.')

Out of the 1166 proteins in the data set, 408 are sensitive to oxidation, with a total of 643 cysteines in them.
Of the 1724 total cysteines in the data set, 148 lie in a region affected by the oxidative environment.